package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Account  implements java.io.Serializable {


     private Integer id;
     private Double numConsumedBudgetC;
     private Boolean chkClientWithoutVisitRouteC;
     private String pckCustomerWarehouseCodeC;
     private String lkpRdcC;
     private String lastname;
     private Double shippinglongitude;
     private String pckAfternoonClosingTimeC;
     private Boolean chkWindowDressingC;
     private String pckPaymentMethodC;
     private Date dttRouteLastModifiedC;
     private Date dttInitVisitRouteC;
     private String pckMorningDeliveryClosingTimeC;
     private String shippingstate;
     private String petxLanguageC;
     private String pckAfternoonOpeningTimeC;
     private String parentid;
     private String lkpRdcBackupC;
     private String txtBankNumberC;
     private String pckSalesEntityC;
     private String txtCifNifC;
     private String recordtypeid;
     private String shippingpostalcode;
     private String billingcity;
     private String pckMorningDeliveryOpeningTimeC;
     private String pckChannelC;
     private String txtVisitWeeksC;
     private Double billinglatitude;
     private Date dttInitCallRouteC;
     private String shippingcountry;
     private Boolean chkHomeDeliveryC;
     private String pckPaymentTypeC;
     private String pckChainC;
     private Boolean chkClientWithoutCallRouteC;
     private String pckTamC;
     private Boolean chkOnlineSalesC;
     private String pckMorningClosingTimeC;
     private String lkpIsC;
     private Double numRankingClienteC;
     private String name;
     private String pckAfternoonDeliveryClosingTimeC;
     private String mulDeliveryAdditionalInfoC;
     private String lkpClientToReplaceC;
     private String pckMorningOpeningTimeC;
     private String txtShipToRouteDescriptionC;
     private String pckAfternoonDeliveryOpeningTimeC;
     private String ownerid;
     private String pckPreferredTimeToCallC;
     private String mulWorkingBrandsC;
     private String pckAreaC;
     private String phoneSapPhone3C;
     private Boolean isdeleted;
     private String lkpLastOrderC;
     private String pckAccountTypeC;
     private Date systemmodstamp;
     private String phoneSapPhone2C;
     private String phoneSapPhone1C;
     private String shippingstreet;
     private String billingpostalcode;
     private Double billinglongitude;
     private String txtSapidC;
     private String mulInterestsC;
     private Double perPesoClienteC;
     private String frmlParentCustomerCodeC;
     private String txtCallWeeksC;
     private Date createddate;
     private String billingstate;
     private Boolean chkHasVeterinarianC;
     private String pckCustomerStatusC;
     private String mailSapEmail3C;
     private String shippingcity;
     private String pckWarnAmountC;
     private String mailSapEmail2C;
     private Double shippinglatitude;
     private String txtPartitaIvaC;
     private String lkpIsBackupC;
     private String mailSapEmail1C;
     private String txtSdiC;
     private String mulShipToRouteDaysC;
     private Boolean chkHairdresserC;
     private String billingcountry;
     private Boolean chkSalesEqualizationTaxC;
     private String pckSubchainC;
     private String pckProductRangeC;
     private Double numPetfoodMetersC;
     private String billingstreet;
     private String mulOpeningAdditionalInfoC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String pckTypePc;
     private String pckRdcC;
     private String pckCustomerComissionCodeC;
     private String txtBloqueoPedidoC;

    public Account() {
    }

	
    public Account(Integer id) {
        this.id = id;
    }
    public Account(Integer id, Double numConsumedBudgetC, Boolean chkClientWithoutVisitRouteC, String pckCustomerWarehouseCodeC, String lkpRdcC, String lastname, Double shippinglongitude, String pckAfternoonClosingTimeC, Boolean chkWindowDressingC, String pckPaymentMethodC, Date dttRouteLastModifiedC, Date dttInitVisitRouteC, String pckMorningDeliveryClosingTimeC, String shippingstate, String petxLanguageC, String pckAfternoonOpeningTimeC, String parentid, String lkpRdcBackupC, String txtBankNumberC, String pckSalesEntityC, String txtCifNifC, String recordtypeid, String shippingpostalcode, String billingcity, String pckMorningDeliveryOpeningTimeC, String pckChannelC, String txtVisitWeeksC, Double billinglatitude, Date dttInitCallRouteC, String shippingcountry, Boolean chkHomeDeliveryC, String pckPaymentTypeC, String pckChainC, Boolean chkClientWithoutCallRouteC, String pckTamC, Boolean chkOnlineSalesC, String pckMorningClosingTimeC, String lkpIsC, Double numRankingClienteC, String name, String pckAfternoonDeliveryClosingTimeC, String mulDeliveryAdditionalInfoC, String lkpClientToReplaceC, String pckMorningOpeningTimeC, String txtShipToRouteDescriptionC, String pckAfternoonDeliveryOpeningTimeC, String ownerid, String pckPreferredTimeToCallC, String mulWorkingBrandsC, String pckAreaC, String phoneSapPhone3C, Boolean isdeleted, String lkpLastOrderC, String pckAccountTypeC, Date systemmodstamp, String phoneSapPhone2C, String phoneSapPhone1C, String shippingstreet, String billingpostalcode, Double billinglongitude, String txtSapidC, String mulInterestsC, Double perPesoClienteC, String frmlParentCustomerCodeC, String txtCallWeeksC, Date createddate, String billingstate, Boolean chkHasVeterinarianC, String pckCustomerStatusC, String mailSapEmail3C, String shippingcity, String pckWarnAmountC, String mailSapEmail2C, Double shippinglatitude, String txtPartitaIvaC, String lkpIsBackupC, String mailSapEmail1C, String txtSdiC, String mulShipToRouteDaysC, Boolean chkHairdresserC, String billingcountry, Boolean chkSalesEqualizationTaxC, String pckSubchainC, String pckProductRangeC, Double numPetfoodMetersC, String billingstreet, String mulOpeningAdditionalInfoC, String sfid, String hcLastop, String hcErr, String pckTypePc, String pckRdcC, String pckCustomerComissionCodeC, String txtBloqueoPedidoC) {
       this.id = id;
       this.numConsumedBudgetC = numConsumedBudgetC;
       this.chkClientWithoutVisitRouteC = chkClientWithoutVisitRouteC;
       this.pckCustomerWarehouseCodeC = pckCustomerWarehouseCodeC;
       this.lkpRdcC = lkpRdcC;
       this.lastname = lastname;
       this.shippinglongitude = shippinglongitude;
       this.pckAfternoonClosingTimeC = pckAfternoonClosingTimeC;
       this.chkWindowDressingC = chkWindowDressingC;
       this.pckPaymentMethodC = pckPaymentMethodC;
       this.dttRouteLastModifiedC = dttRouteLastModifiedC;
       this.dttInitVisitRouteC = dttInitVisitRouteC;
       this.pckMorningDeliveryClosingTimeC = pckMorningDeliveryClosingTimeC;
       this.shippingstate = shippingstate;
       this.petxLanguageC = petxLanguageC;
       this.pckAfternoonOpeningTimeC = pckAfternoonOpeningTimeC;
       this.parentid = parentid;
       this.lkpRdcBackupC = lkpRdcBackupC;
       this.txtBankNumberC = txtBankNumberC;
       this.pckSalesEntityC = pckSalesEntityC;
       this.txtCifNifC = txtCifNifC;
       this.recordtypeid = recordtypeid;
       this.shippingpostalcode = shippingpostalcode;
       this.billingcity = billingcity;
       this.pckMorningDeliveryOpeningTimeC = pckMorningDeliveryOpeningTimeC;
       this.pckChannelC = pckChannelC;
       this.txtVisitWeeksC = txtVisitWeeksC;
       this.billinglatitude = billinglatitude;
       this.dttInitCallRouteC = dttInitCallRouteC;
       this.shippingcountry = shippingcountry;
       this.chkHomeDeliveryC = chkHomeDeliveryC;
       this.pckPaymentTypeC = pckPaymentTypeC;
       this.pckChainC = pckChainC;
       this.chkClientWithoutCallRouteC = chkClientWithoutCallRouteC;
       this.pckTamC = pckTamC;
       this.chkOnlineSalesC = chkOnlineSalesC;
       this.pckMorningClosingTimeC = pckMorningClosingTimeC;
       this.lkpIsC = lkpIsC;
       this.numRankingClienteC = numRankingClienteC;
       this.name = name;
       this.pckAfternoonDeliveryClosingTimeC = pckAfternoonDeliveryClosingTimeC;
       this.mulDeliveryAdditionalInfoC = mulDeliveryAdditionalInfoC;
       this.lkpClientToReplaceC = lkpClientToReplaceC;
       this.pckMorningOpeningTimeC = pckMorningOpeningTimeC;
       this.txtShipToRouteDescriptionC = txtShipToRouteDescriptionC;
       this.pckAfternoonDeliveryOpeningTimeC = pckAfternoonDeliveryOpeningTimeC;
       this.ownerid = ownerid;
       this.pckPreferredTimeToCallC = pckPreferredTimeToCallC;
       this.mulWorkingBrandsC = mulWorkingBrandsC;
       this.pckAreaC = pckAreaC;
       this.phoneSapPhone3C = phoneSapPhone3C;
       this.isdeleted = isdeleted;
       this.lkpLastOrderC = lkpLastOrderC;
       this.pckAccountTypeC = pckAccountTypeC;
       this.systemmodstamp = systemmodstamp;
       this.phoneSapPhone2C = phoneSapPhone2C;
       this.phoneSapPhone1C = phoneSapPhone1C;
       this.shippingstreet = shippingstreet;
       this.billingpostalcode = billingpostalcode;
       this.billinglongitude = billinglongitude;
       this.txtSapidC = txtSapidC;
       this.mulInterestsC = mulInterestsC;
       this.perPesoClienteC = perPesoClienteC;
       this.frmlParentCustomerCodeC = frmlParentCustomerCodeC;
       this.txtCallWeeksC = txtCallWeeksC;
       this.createddate = createddate;
       this.billingstate = billingstate;
       this.chkHasVeterinarianC = chkHasVeterinarianC;
       this.pckCustomerStatusC = pckCustomerStatusC;
       this.mailSapEmail3C = mailSapEmail3C;
       this.shippingcity = shippingcity;
       this.pckWarnAmountC = pckWarnAmountC;
       this.mailSapEmail2C = mailSapEmail2C;
       this.shippinglatitude = shippinglatitude;
       this.txtPartitaIvaC = txtPartitaIvaC;
       this.lkpIsBackupC = lkpIsBackupC;
       this.mailSapEmail1C = mailSapEmail1C;
       this.txtSdiC = txtSdiC;
       this.mulShipToRouteDaysC = mulShipToRouteDaysC;
       this.chkHairdresserC = chkHairdresserC;
       this.billingcountry = billingcountry;
       this.chkSalesEqualizationTaxC = chkSalesEqualizationTaxC;
       this.pckSubchainC = pckSubchainC;
       this.pckProductRangeC = pckProductRangeC;
       this.numPetfoodMetersC = numPetfoodMetersC;
       this.billingstreet = billingstreet;
       this.mulOpeningAdditionalInfoC = mulOpeningAdditionalInfoC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.pckTypePc = pckTypePc;
       this.pckRdcC = pckRdcC;
       this.pckCustomerComissionCodeC = pckCustomerComissionCodeC;
       this.txtBloqueoPedidoC = txtBloqueoPedidoC;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="num_consumed_budget__c", precision=17, scale=17)
    public Double getNumConsumedBudgetC() {
        return this.numConsumedBudgetC;
    }
    
    public void setNumConsumedBudgetC(Double numConsumedBudgetC) {
        this.numConsumedBudgetC = numConsumedBudgetC;
    }

    
    @Column(name="chk_client_without_visit_route__c")
    public Boolean getChkClientWithoutVisitRouteC() {
        return this.chkClientWithoutVisitRouteC;
    }
    
    public void setChkClientWithoutVisitRouteC(Boolean chkClientWithoutVisitRouteC) {
        this.chkClientWithoutVisitRouteC = chkClientWithoutVisitRouteC;
    }

    
    @Column(name="pck_customer_warehouse_code__c")
    public String getPckCustomerWarehouseCodeC() {
        return this.pckCustomerWarehouseCodeC;
    }
    
    public void setPckCustomerWarehouseCodeC(String pckCustomerWarehouseCodeC) {
        this.pckCustomerWarehouseCodeC = pckCustomerWarehouseCodeC;
    }

    
    @Column(name="lkp_rdc__c", length=18)
    public String getLkpRdcC() {
        return this.lkpRdcC;
    }
    
    public void setLkpRdcC(String lkpRdcC) {
        this.lkpRdcC = lkpRdcC;
    }

    
    @Column(name="lastname", length=80)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="shippinglongitude", precision=17, scale=17)
    public Double getShippinglongitude() {
        return this.shippinglongitude;
    }
    
    public void setShippinglongitude(Double shippinglongitude) {
        this.shippinglongitude = shippinglongitude;
    }

    
    @Column(name="pck_afternoon_closing_time__c")
    public String getPckAfternoonClosingTimeC() {
        return this.pckAfternoonClosingTimeC;
    }
    
    public void setPckAfternoonClosingTimeC(String pckAfternoonClosingTimeC) {
        this.pckAfternoonClosingTimeC = pckAfternoonClosingTimeC;
    }

    
    @Column(name="chk_window_dressing__c")
    public Boolean getChkWindowDressingC() {
        return this.chkWindowDressingC;
    }
    
    public void setChkWindowDressingC(Boolean chkWindowDressingC) {
        this.chkWindowDressingC = chkWindowDressingC;
    }

    
    @Column(name="pck_payment_method__c")
    public String getPckPaymentMethodC() {
        return this.pckPaymentMethodC;
    }
    
    public void setPckPaymentMethodC(String pckPaymentMethodC) {
        this.pckPaymentMethodC = pckPaymentMethodC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_route_last_modified__c", length=29)
    public Date getDttRouteLastModifiedC() {
        return this.dttRouteLastModifiedC;
    }
    
    public void setDttRouteLastModifiedC(Date dttRouteLastModifiedC) {
        this.dttRouteLastModifiedC = dttRouteLastModifiedC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_init_visit_route__c", length=29)
    public Date getDttInitVisitRouteC() {
        return this.dttInitVisitRouteC;
    }
    
    public void setDttInitVisitRouteC(Date dttInitVisitRouteC) {
        this.dttInitVisitRouteC = dttInitVisitRouteC;
    }

    
    @Column(name="pck_morning_delivery_closing_time__c")
    public String getPckMorningDeliveryClosingTimeC() {
        return this.pckMorningDeliveryClosingTimeC;
    }
    
    public void setPckMorningDeliveryClosingTimeC(String pckMorningDeliveryClosingTimeC) {
        this.pckMorningDeliveryClosingTimeC = pckMorningDeliveryClosingTimeC;
    }

    
    @Column(name="shippingstate", length=80)
    public String getShippingstate() {
        return this.shippingstate;
    }
    
    public void setShippingstate(String shippingstate) {
        this.shippingstate = shippingstate;
    }

    
    @Column(name="petx_language__c")
    public String getPetxLanguageC() {
        return this.petxLanguageC;
    }
    
    public void setPetxLanguageC(String petxLanguageC) {
        this.petxLanguageC = petxLanguageC;
    }

    
    @Column(name="pck_afternoon_opening_time__c")
    public String getPckAfternoonOpeningTimeC() {
        return this.pckAfternoonOpeningTimeC;
    }
    
    public void setPckAfternoonOpeningTimeC(String pckAfternoonOpeningTimeC) {
        this.pckAfternoonOpeningTimeC = pckAfternoonOpeningTimeC;
    }

    
    @Column(name="parentid", length=18)
    public String getParentid() {
        return this.parentid;
    }
    
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    
    @Column(name="lkp_rdc_backup__c", length=18)
    public String getLkpRdcBackupC() {
        return this.lkpRdcBackupC;
    }
    
    public void setLkpRdcBackupC(String lkpRdcBackupC) {
        this.lkpRdcBackupC = lkpRdcBackupC;
    }

    
    @Column(name="txt_bank_number__c", length=27)
    public String getTxtBankNumberC() {
        return this.txtBankNumberC;
    }
    
    public void setTxtBankNumberC(String txtBankNumberC) {
        this.txtBankNumberC = txtBankNumberC;
    }

    
    @Column(name="pck_sales_entity__c")
    public String getPckSalesEntityC() {
        return this.pckSalesEntityC;
    }
    
    public void setPckSalesEntityC(String pckSalesEntityC) {
        this.pckSalesEntityC = pckSalesEntityC;
    }

    
    @Column(name="txt_cif_nif__c", length=16)
    public String getTxtCifNifC() {
        return this.txtCifNifC;
    }
    
    public void setTxtCifNifC(String txtCifNifC) {
        this.txtCifNifC = txtCifNifC;
    }

    
    @Column(name="recordtypeid", length=18)
    public String getRecordtypeid() {
        return this.recordtypeid;
    }
    
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }

    
    @Column(name="shippingpostalcode", length=20)
    public String getShippingpostalcode() {
        return this.shippingpostalcode;
    }
    
    public void setShippingpostalcode(String shippingpostalcode) {
        this.shippingpostalcode = shippingpostalcode;
    }

    
    @Column(name="billingcity", length=40)
    public String getBillingcity() {
        return this.billingcity;
    }
    
    public void setBillingcity(String billingcity) {
        this.billingcity = billingcity;
    }

    
    @Column(name="pck_morning_delivery_opening_time__c")
    public String getPckMorningDeliveryOpeningTimeC() {
        return this.pckMorningDeliveryOpeningTimeC;
    }
    
    public void setPckMorningDeliveryOpeningTimeC(String pckMorningDeliveryOpeningTimeC) {
        this.pckMorningDeliveryOpeningTimeC = pckMorningDeliveryOpeningTimeC;
    }

    
    @Column(name="pck_channel__c")
    public String getPckChannelC() {
        return this.pckChannelC;
    }
    
    public void setPckChannelC(String pckChannelC) {
        this.pckChannelC = pckChannelC;
    }

    
    @Column(name="txt_visit_weeks__c", length=12)
    public String getTxtVisitWeeksC() {
        return this.txtVisitWeeksC;
    }
    
    public void setTxtVisitWeeksC(String txtVisitWeeksC) {
        this.txtVisitWeeksC = txtVisitWeeksC;
    }

    
    @Column(name="billinglatitude", precision=17, scale=17)
    public Double getBillinglatitude() {
        return this.billinglatitude;
    }
    
    public void setBillinglatitude(Double billinglatitude) {
        this.billinglatitude = billinglatitude;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_init_call_route__c", length=29)
    public Date getDttInitCallRouteC() {
        return this.dttInitCallRouteC;
    }
    
    public void setDttInitCallRouteC(Date dttInitCallRouteC) {
        this.dttInitCallRouteC = dttInitCallRouteC;
    }

    
    @Column(name="shippingcountry", length=80)
    public String getShippingcountry() {
        return this.shippingcountry;
    }
    
    public void setShippingcountry(String shippingcountry) {
        this.shippingcountry = shippingcountry;
    }

    
    @Column(name="chk_home_delivery__c")
    public Boolean getChkHomeDeliveryC() {
        return this.chkHomeDeliveryC;
    }
    
    public void setChkHomeDeliveryC(Boolean chkHomeDeliveryC) {
        this.chkHomeDeliveryC = chkHomeDeliveryC;
    }

    
    @Column(name="pck_payment_type__c")
    public String getPckPaymentTypeC() {
        return this.pckPaymentTypeC;
    }
    
    public void setPckPaymentTypeC(String pckPaymentTypeC) {
        this.pckPaymentTypeC = pckPaymentTypeC;
    }

    
    @Column(name="pck_chain__c")
    public String getPckChainC() {
        return this.pckChainC;
    }
    
    public void setPckChainC(String pckChainC) {
        this.pckChainC = pckChainC;
    }

    
    @Column(name="chk_client_without_call_route__c")
    public Boolean getChkClientWithoutCallRouteC() {
        return this.chkClientWithoutCallRouteC;
    }
    
    public void setChkClientWithoutCallRouteC(Boolean chkClientWithoutCallRouteC) {
        this.chkClientWithoutCallRouteC = chkClientWithoutCallRouteC;
    }

    
    @Column(name="pck_tam__c")
    public String getPckTamC() {
        return this.pckTamC;
    }
    
    public void setPckTamC(String pckTamC) {
        this.pckTamC = pckTamC;
    }

    
    @Column(name="chk_online_sales__c")
    public Boolean getChkOnlineSalesC() {
        return this.chkOnlineSalesC;
    }
    
    public void setChkOnlineSalesC(Boolean chkOnlineSalesC) {
        this.chkOnlineSalesC = chkOnlineSalesC;
    }

    
    @Column(name="pck_morning_closing_time__c")
    public String getPckMorningClosingTimeC() {
        return this.pckMorningClosingTimeC;
    }
    
    public void setPckMorningClosingTimeC(String pckMorningClosingTimeC) {
        this.pckMorningClosingTimeC = pckMorningClosingTimeC;
    }

    
    @Column(name="lkp_is__c", length=18)
    public String getLkpIsC() {
        return this.lkpIsC;
    }
    
    public void setLkpIsC(String lkpIsC) {
        this.lkpIsC = lkpIsC;
    }

    
    @Column(name="num_ranking_cliente__c", precision=17, scale=17)
    public Double getNumRankingClienteC() {
        return this.numRankingClienteC;
    }
    
    public void setNumRankingClienteC(Double numRankingClienteC) {
        this.numRankingClienteC = numRankingClienteC;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="pck_afternoon_delivery_closing_time__c")
    public String getPckAfternoonDeliveryClosingTimeC() {
        return this.pckAfternoonDeliveryClosingTimeC;
    }
    
    public void setPckAfternoonDeliveryClosingTimeC(String pckAfternoonDeliveryClosingTimeC) {
        this.pckAfternoonDeliveryClosingTimeC = pckAfternoonDeliveryClosingTimeC;
    }

    
    @Column(name="mul_delivery_additional_info__c", length=4099)
    public String getMulDeliveryAdditionalInfoC() {
        return this.mulDeliveryAdditionalInfoC;
    }
    
    public void setMulDeliveryAdditionalInfoC(String mulDeliveryAdditionalInfoC) {
        this.mulDeliveryAdditionalInfoC = mulDeliveryAdditionalInfoC;
    }

    
    @Column(name="lkp_client_to_replace__c", length=18)
    public String getLkpClientToReplaceC() {
        return this.lkpClientToReplaceC;
    }
    
    public void setLkpClientToReplaceC(String lkpClientToReplaceC) {
        this.lkpClientToReplaceC = lkpClientToReplaceC;
    }

    
    @Column(name="pck_morning_opening_time__c")
    public String getPckMorningOpeningTimeC() {
        return this.pckMorningOpeningTimeC;
    }
    
    public void setPckMorningOpeningTimeC(String pckMorningOpeningTimeC) {
        this.pckMorningOpeningTimeC = pckMorningOpeningTimeC;
    }

    
    @Column(name="txt_ship_to_route_description__c", length=40)
    public String getTxtShipToRouteDescriptionC() {
        return this.txtShipToRouteDescriptionC;
    }
    
    public void setTxtShipToRouteDescriptionC(String txtShipToRouteDescriptionC) {
        this.txtShipToRouteDescriptionC = txtShipToRouteDescriptionC;
    }

    
    @Column(name="pck_afternoon_delivery_opening_time__c")
    public String getPckAfternoonDeliveryOpeningTimeC() {
        return this.pckAfternoonDeliveryOpeningTimeC;
    }
    
    public void setPckAfternoonDeliveryOpeningTimeC(String pckAfternoonDeliveryOpeningTimeC) {
        this.pckAfternoonDeliveryOpeningTimeC = pckAfternoonDeliveryOpeningTimeC;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="pck_preferred_time_to_call__c")
    public String getPckPreferredTimeToCallC() {
        return this.pckPreferredTimeToCallC;
    }
    
    public void setPckPreferredTimeToCallC(String pckPreferredTimeToCallC) {
        this.pckPreferredTimeToCallC = pckPreferredTimeToCallC;
    }

    
    @Column(name="mul_working_brands__c", length=4099)
    public String getMulWorkingBrandsC() {
        return this.mulWorkingBrandsC;
    }
    
    public void setMulWorkingBrandsC(String mulWorkingBrandsC) {
        this.mulWorkingBrandsC = mulWorkingBrandsC;
    }

    
    @Column(name="pck_area__c")
    public String getPckAreaC() {
        return this.pckAreaC;
    }
    
    public void setPckAreaC(String pckAreaC) {
        this.pckAreaC = pckAreaC;
    }

    
    @Column(name="phone_sap_phone_3__c", length=40)
    public String getPhoneSapPhone3C() {
        return this.phoneSapPhone3C;
    }
    
    public void setPhoneSapPhone3C(String phoneSapPhone3C) {
        this.phoneSapPhone3C = phoneSapPhone3C;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="lkp_last_order__c", length=18)
    public String getLkpLastOrderC() {
        return this.lkpLastOrderC;
    }
    
    public void setLkpLastOrderC(String lkpLastOrderC) {
        this.lkpLastOrderC = lkpLastOrderC;
    }

    
    @Column(name="pck_account_type__c")
    public String getPckAccountTypeC() {
        return this.pckAccountTypeC;
    }
    
    public void setPckAccountTypeC(String pckAccountTypeC) {
        this.pckAccountTypeC = pckAccountTypeC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="phone_sap_phone_2__c", length=40)
    public String getPhoneSapPhone2C() {
        return this.phoneSapPhone2C;
    }
    
    public void setPhoneSapPhone2C(String phoneSapPhone2C) {
        this.phoneSapPhone2C = phoneSapPhone2C;
    }

    
    @Column(name="phone_sap_phone_1__c", length=40)
    public String getPhoneSapPhone1C() {
        return this.phoneSapPhone1C;
    }
    
    public void setPhoneSapPhone1C(String phoneSapPhone1C) {
        this.phoneSapPhone1C = phoneSapPhone1C;
    }

    
    @Column(name="shippingstreet")
    public String getShippingstreet() {
        return this.shippingstreet;
    }
    
    public void setShippingstreet(String shippingstreet) {
        this.shippingstreet = shippingstreet;
    }

    
    @Column(name="billingpostalcode", length=20)
    public String getBillingpostalcode() {
        return this.billingpostalcode;
    }
    
    public void setBillingpostalcode(String billingpostalcode) {
        this.billingpostalcode = billingpostalcode;
    }

    
    @Column(name="billinglongitude", precision=17, scale=17)
    public Double getBillinglongitude() {
        return this.billinglongitude;
    }
    
    public void setBillinglongitude(Double billinglongitude) {
        this.billinglongitude = billinglongitude;
    }

    
    @Column(name="txt_sapid__c", length=16)
    public String getTxtSapidC() {
        return this.txtSapidC;
    }
    
    public void setTxtSapidC(String txtSapidC) {
        this.txtSapidC = txtSapidC;
    }

    
    @Column(name="mul_interests__c", length=4099)
    public String getMulInterestsC() {
        return this.mulInterestsC;
    }
    
    public void setMulInterestsC(String mulInterestsC) {
        this.mulInterestsC = mulInterestsC;
    }

    
    @Column(name="per_peso_cliente__c", precision=17, scale=17)
    public Double getPerPesoClienteC() {
        return this.perPesoClienteC;
    }
    
    public void setPerPesoClienteC(Double perPesoClienteC) {
        this.perPesoClienteC = perPesoClienteC;
    }

    
    @Column(name="frml_parent_customer_code__c", length=1300)
    public String getFrmlParentCustomerCodeC() {
        return this.frmlParentCustomerCodeC;
    }
    
    public void setFrmlParentCustomerCodeC(String frmlParentCustomerCodeC) {
        this.frmlParentCustomerCodeC = frmlParentCustomerCodeC;
    }

    
    @Column(name="txt_call_weeks__c", length=12)
    public String getTxtCallWeeksC() {
        return this.txtCallWeeksC;
    }
    
    public void setTxtCallWeeksC(String txtCallWeeksC) {
        this.txtCallWeeksC = txtCallWeeksC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="billingstate", length=80)
    public String getBillingstate() {
        return this.billingstate;
    }
    
    public void setBillingstate(String billingstate) {
        this.billingstate = billingstate;
    }

    
    @Column(name="chk_has_veterinarian__c")
    public Boolean getChkHasVeterinarianC() {
        return this.chkHasVeterinarianC;
    }
    
    public void setChkHasVeterinarianC(Boolean chkHasVeterinarianC) {
        this.chkHasVeterinarianC = chkHasVeterinarianC;
    }

    
    @Column(name="pck_customer_status__c")
    public String getPckCustomerStatusC() {
        return this.pckCustomerStatusC;
    }
    
    public void setPckCustomerStatusC(String pckCustomerStatusC) {
        this.pckCustomerStatusC = pckCustomerStatusC;
    }

    
    @Column(name="mail_sap_email_3__c", length=80)
    public String getMailSapEmail3C() {
        return this.mailSapEmail3C;
    }
    
    public void setMailSapEmail3C(String mailSapEmail3C) {
        this.mailSapEmail3C = mailSapEmail3C;
    }

    
    @Column(name="shippingcity", length=40)
    public String getShippingcity() {
        return this.shippingcity;
    }
    
    public void setShippingcity(String shippingcity) {
        this.shippingcity = shippingcity;
    }

    
    @Column(name="pck_warn_amount__c")
    public String getPckWarnAmountC() {
        return this.pckWarnAmountC;
    }
    
    public void setPckWarnAmountC(String pckWarnAmountC) {
        this.pckWarnAmountC = pckWarnAmountC;
    }

    
    @Column(name="mail_sap_email_2__c", length=80)
    public String getMailSapEmail2C() {
        return this.mailSapEmail2C;
    }
    
    public void setMailSapEmail2C(String mailSapEmail2C) {
        this.mailSapEmail2C = mailSapEmail2C;
    }

    
    @Column(name="shippinglatitude", precision=17, scale=17)
    public Double getShippinglatitude() {
        return this.shippinglatitude;
    }
    
    public void setShippinglatitude(Double shippinglatitude) {
        this.shippinglatitude = shippinglatitude;
    }

    
    @Column(name="txt_partita_iva__c", length=11)
    public String getTxtPartitaIvaC() {
        return this.txtPartitaIvaC;
    }
    
    public void setTxtPartitaIvaC(String txtPartitaIvaC) {
        this.txtPartitaIvaC = txtPartitaIvaC;
    }

    
    @Column(name="lkp_is_backup__c", length=18)
    public String getLkpIsBackupC() {
        return this.lkpIsBackupC;
    }
    
    public void setLkpIsBackupC(String lkpIsBackupC) {
        this.lkpIsBackupC = lkpIsBackupC;
    }

    
    @Column(name="mail_sap_email_1__c", length=80)
    public String getMailSapEmail1C() {
        return this.mailSapEmail1C;
    }
    
    public void setMailSapEmail1C(String mailSapEmail1C) {
        this.mailSapEmail1C = mailSapEmail1C;
    }

    
    @Column(name="txt_sdi__c", length=18)
    public String getTxtSdiC() {
        return this.txtSdiC;
    }
    
    public void setTxtSdiC(String txtSdiC) {
        this.txtSdiC = txtSdiC;
    }

    
    @Column(name="mul_ship_to_route_days__c", length=4099)
    public String getMulShipToRouteDaysC() {
        return this.mulShipToRouteDaysC;
    }
    
    public void setMulShipToRouteDaysC(String mulShipToRouteDaysC) {
        this.mulShipToRouteDaysC = mulShipToRouteDaysC;
    }

    
    @Column(name="chk_hairdresser__c")
    public Boolean getChkHairdresserC() {
        return this.chkHairdresserC;
    }
    
    public void setChkHairdresserC(Boolean chkHairdresserC) {
        this.chkHairdresserC = chkHairdresserC;
    }

    
    @Column(name="billingcountry", length=80)
    public String getBillingcountry() {
        return this.billingcountry;
    }
    
    public void setBillingcountry(String billingcountry) {
        this.billingcountry = billingcountry;
    }

    
    @Column(name="chk_sales_equalization_tax__c")
    public Boolean getChkSalesEqualizationTaxC() {
        return this.chkSalesEqualizationTaxC;
    }
    
    public void setChkSalesEqualizationTaxC(Boolean chkSalesEqualizationTaxC) {
        this.chkSalesEqualizationTaxC = chkSalesEqualizationTaxC;
    }

    
    @Column(name="pck_subchain__c")
    public String getPckSubchainC() {
        return this.pckSubchainC;
    }
    
    public void setPckSubchainC(String pckSubchainC) {
        this.pckSubchainC = pckSubchainC;
    }

    
    @Column(name="pck_product_range__c", length=4099)
    public String getPckProductRangeC() {
        return this.pckProductRangeC;
    }
    
    public void setPckProductRangeC(String pckProductRangeC) {
        this.pckProductRangeC = pckProductRangeC;
    }

    
    @Column(name="num_petfood_meters__c", precision=17, scale=17)
    public Double getNumPetfoodMetersC() {
        return this.numPetfoodMetersC;
    }
    
    public void setNumPetfoodMetersC(Double numPetfoodMetersC) {
        this.numPetfoodMetersC = numPetfoodMetersC;
    }

    
    @Column(name="billingstreet")
    public String getBillingstreet() {
        return this.billingstreet;
    }
    
    public void setBillingstreet(String billingstreet) {
        this.billingstreet = billingstreet;
    }

    
    @Column(name="mul_opening_additional_info__c", length=4099)
    public String getMulOpeningAdditionalInfoC() {
        return this.mulOpeningAdditionalInfoC;
    }
    
    public void setMulOpeningAdditionalInfoC(String mulOpeningAdditionalInfoC) {
        this.mulOpeningAdditionalInfoC = mulOpeningAdditionalInfoC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="pck_type__pc")
    public String getPckTypePc() {
        return this.pckTypePc;
    }
    
    public void setPckTypePc(String pckTypePc) {
        this.pckTypePc = pckTypePc;
    }

    
    @Column(name="pck_rdc__c")
    public String getPckRdcC() {
        return this.pckRdcC;
    }
    
    public void setPckRdcC(String pckRdcC) {
        this.pckRdcC = pckRdcC;
    }

    
    @Column(name="pck_customer_comission_code__c")
    public String getPckCustomerComissionCodeC() {
        return this.pckCustomerComissionCodeC;
    }
    
    public void setPckCustomerComissionCodeC(String pckCustomerComissionCodeC) {
        this.pckCustomerComissionCodeC = pckCustomerComissionCodeC;
    }

    
    @Column(name="txt_bloqueo_pedido__c", length=2)
    public String getTxtBloqueoPedidoC() {
        return this.txtBloqueoPedidoC;
    }
    
    public void setTxtBloqueoPedidoC(String txtBloqueoPedidoC) {
        this.txtBloqueoPedidoC = txtBloqueoPedidoC;
    }




}


