package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AcuerdoComercialC generated by hbm2java
 */
@Entity
@Table(name="acuerdo_comercial__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class AcuerdoComercialC  implements java.io.Serializable {


     private Integer id;
     private Double objetivoC;
     private String name;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private Date createddate;
     private String accountC;
     private Double consecucionC;
     private Date fechaFinC;
     private Date fechaInicioC;
     private String subbrandC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private Date fechaFinCalculoC;
     private Date fechaInicioCalculoC;

    public AcuerdoComercialC() {
    }

	
    public AcuerdoComercialC(Integer id) {
        this.id = id;
    }
    public AcuerdoComercialC(Integer id, Double objetivoC, String name, Boolean isdeleted, Date systemmodstamp, Date createddate, String accountC, Double consecucionC, Date fechaFinC, Date fechaInicioC, String subbrandC, String sfid, String hcLastop, String hcErr, Date fechaFinCalculoC, Date fechaInicioCalculoC) {
       this.id = id;
       this.objetivoC = objetivoC;
       this.name = name;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.createddate = createddate;
       this.accountC = accountC;
       this.consecucionC = consecucionC;
       this.fechaFinC = fechaFinC;
       this.fechaInicioC = fechaInicioC;
       this.subbrandC = subbrandC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.fechaFinCalculoC = fechaFinCalculoC;
       this.fechaInicioCalculoC = fechaInicioCalculoC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="objetivo__c", precision=17, scale=17)
    public Double getObjetivoC() {
        return this.objetivoC;
    }
    
    public void setObjetivoC(Double objetivoC) {
        this.objetivoC = objetivoC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="account__c", length=18)
    public String getAccountC() {
        return this.accountC;
    }
    
    public void setAccountC(String accountC) {
        this.accountC = accountC;
    }

    
    @Column(name="consecucion__c", precision=17, scale=17)
    public Double getConsecucionC() {
        return this.consecucionC;
    }
    
    public void setConsecucionC(Double consecucionC) {
        this.consecucionC = consecucionC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin__c", length=13)
    public Date getFechaFinC() {
        return this.fechaFinC;
    }
    
    public void setFechaFinC(Date fechaFinC) {
        this.fechaFinC = fechaFinC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio__c", length=13)
    public Date getFechaInicioC() {
        return this.fechaInicioC;
    }
    
    public void setFechaInicioC(Date fechaInicioC) {
        this.fechaInicioC = fechaInicioC;
    }

    
    @Column(name="subbrand__c", length=18)
    public String getSubbrandC() {
        return this.subbrandC;
    }
    
    public void setSubbrandC(String subbrandC) {
        this.subbrandC = subbrandC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin_calculo__c", length=13)
    public Date getFechaFinCalculoC() {
        return this.fechaFinCalculoC;
    }
    
    public void setFechaFinCalculoC(Date fechaFinCalculoC) {
        this.fechaFinCalculoC = fechaFinCalculoC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio_calculo__c", length=13)
    public Date getFechaInicioCalculoC() {
        return this.fechaInicioCalculoC;
    }
    
    public void setFechaInicioCalculoC(Date fechaInicioCalculoC) {
        this.fechaInicioCalculoC = fechaInicioCalculoC;
    }




}


