package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AcuerdoComercialIntermedia generated by hbm2java
 */
@Entity
@Table(name="acuerdo_comercial_intermedia"
    ,schema="salesforce"
)
public class AcuerdoComercialIntermedia  implements java.io.Serializable {


     private AcuerdoComercialIntermediaId id;

    public AcuerdoComercialIntermedia() {
    }

    public AcuerdoComercialIntermedia(AcuerdoComercialIntermediaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code") ), 
        @AttributeOverride(name="subbrand", column=@Column(name="subbrand") ), 
        @AttributeOverride(name="fechaInicio", column=@Column(name="fecha_inicio", length=13) ), 
        @AttributeOverride(name="fechaFin", column=@Column(name="fecha_fin", length=13) ), 
        @AttributeOverride(name="sfidCustomer", column=@Column(name="sfid_customer") ), 
        @AttributeOverride(name="sfidSubbrand", column=@Column(name="sfid_subbrand") ) } )
    public AcuerdoComercialIntermediaId getId() {
        return this.id;
    }
    
    public void setId(AcuerdoComercialIntermediaId id) {
        this.id = id;
    }




}


