package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AssortmentsC generated by hbm2java
 */
@Entity
@Table(name="assortments__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class AssortmentsC  implements java.io.Serializable {


     private Integer id;
     private Date datEndDateC;
     private String pckChainC;
     private Boolean frmlActiveC;
     private String name;
     private Boolean isdeleted;
     private Date datStartDateC;
     private String pckAccountTypeC;
     private Date systemmodstamp;
     private String txtDescriptionC;
     private Date createddate;
     private String pckSubchainC;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public AssortmentsC() {
    }

	
    public AssortmentsC(Integer id) {
        this.id = id;
    }
    public AssortmentsC(Integer id, Date datEndDateC, String pckChainC, Boolean frmlActiveC, String name, Boolean isdeleted, Date datStartDateC, String pckAccountTypeC, Date systemmodstamp, String txtDescriptionC, Date createddate, String pckSubchainC, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.datEndDateC = datEndDateC;
       this.pckChainC = pckChainC;
       this.frmlActiveC = frmlActiveC;
       this.name = name;
       this.isdeleted = isdeleted;
       this.datStartDateC = datStartDateC;
       this.pckAccountTypeC = pckAccountTypeC;
       this.systemmodstamp = systemmodstamp;
       this.txtDescriptionC = txtDescriptionC;
       this.createddate = createddate;
       this.pckSubchainC = pckSubchainC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dat_end_date__c", length=13)
    public Date getDatEndDateC() {
        return this.datEndDateC;
    }
    
    public void setDatEndDateC(Date datEndDateC) {
        this.datEndDateC = datEndDateC;
    }

    
    @Column(name="pck_chain__c", length=4099)
    public String getPckChainC() {
        return this.pckChainC;
    }
    
    public void setPckChainC(String pckChainC) {
        this.pckChainC = pckChainC;
    }

    
    @Column(name="frml_active__c")
    public Boolean getFrmlActiveC() {
        return this.frmlActiveC;
    }
    
    public void setFrmlActiveC(Boolean frmlActiveC) {
        this.frmlActiveC = frmlActiveC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dat_start_date__c", length=13)
    public Date getDatStartDateC() {
        return this.datStartDateC;
    }
    
    public void setDatStartDateC(Date datStartDateC) {
        this.datStartDateC = datStartDateC;
    }

    
    @Column(name="pck_account_type__c", length=4099)
    public String getPckAccountTypeC() {
        return this.pckAccountTypeC;
    }
    
    public void setPckAccountTypeC(String pckAccountTypeC) {
        this.pckAccountTypeC = pckAccountTypeC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="txt_description__c")
    public String getTxtDescriptionC() {
        return this.txtDescriptionC;
    }
    
    public void setTxtDescriptionC(String txtDescriptionC) {
        this.txtDescriptionC = txtDescriptionC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="pck_subchain__c", length=4099)
    public String getPckSubchainC() {
        return this.pckSubchainC;
    }
    
    public void setPckSubchainC(String pckSubchainC) {
        this.pckSubchainC = pckSubchainC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


