package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Case generated by hbm2java
 */
@Entity
@Table(name="case"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Case  implements java.io.Serializable {


     private Integer id;
     private String petxCaseTypeC;
     private Boolean chkClientWithoutVisitRouteC;
     private Date dttInitVisitRouteC;
     private String lkpOrderC;
     private String priority;
     private String recordtypeid;
     private String origin;
     private String txtVisitWeeksC;
     private Date dttInitCallRouteC;
     private String accountid;
     private Boolean chkClientWithoutCallRouteC;
     private String subject;
     private String ownerid;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private String pckCaseSubtypeC;
     private String status;
     private String txtCallWeeksC;
     private Date createddate;
     private String caseTypeC;
     private String type;
     private String contactid;
     private String caseSubTypeC;
     private String description;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String lkpContactPersonC;

    public Case() {
    }

	
    public Case(Integer id) {
        this.id = id;
    }
    public Case(Integer id, String petxCaseTypeC, Boolean chkClientWithoutVisitRouteC, Date dttInitVisitRouteC, String lkpOrderC, String priority, String recordtypeid, String origin, String txtVisitWeeksC, Date dttInitCallRouteC, String accountid, Boolean chkClientWithoutCallRouteC, String subject, String ownerid, Boolean isdeleted, Date systemmodstamp, String pckCaseSubtypeC, String status, String txtCallWeeksC, Date createddate, String caseTypeC, String type, String contactid, String caseSubTypeC, String description, String sfid, String hcLastop, String hcErr, String lkpContactPersonC) {
       this.id = id;
       this.petxCaseTypeC = petxCaseTypeC;
       this.chkClientWithoutVisitRouteC = chkClientWithoutVisitRouteC;
       this.dttInitVisitRouteC = dttInitVisitRouteC;
       this.lkpOrderC = lkpOrderC;
       this.priority = priority;
       this.recordtypeid = recordtypeid;
       this.origin = origin;
       this.txtVisitWeeksC = txtVisitWeeksC;
       this.dttInitCallRouteC = dttInitCallRouteC;
       this.accountid = accountid;
       this.chkClientWithoutCallRouteC = chkClientWithoutCallRouteC;
       this.subject = subject;
       this.ownerid = ownerid;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.pckCaseSubtypeC = pckCaseSubtypeC;
       this.status = status;
       this.txtCallWeeksC = txtCallWeeksC;
       this.createddate = createddate;
       this.caseTypeC = caseTypeC;
       this.type = type;
       this.contactid = contactid;
       this.caseSubTypeC = caseSubTypeC;
       this.description = description;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.lkpContactPersonC = lkpContactPersonC;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="petx_case_type__c")
    public String getPetxCaseTypeC() {
        return this.petxCaseTypeC;
    }
    
    public void setPetxCaseTypeC(String petxCaseTypeC) {
        this.petxCaseTypeC = petxCaseTypeC;
    }

    
    @Column(name="chk_client_without_visit_route__c")
    public Boolean getChkClientWithoutVisitRouteC() {
        return this.chkClientWithoutVisitRouteC;
    }
    
    public void setChkClientWithoutVisitRouteC(Boolean chkClientWithoutVisitRouteC) {
        this.chkClientWithoutVisitRouteC = chkClientWithoutVisitRouteC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_init_visit_route__c", length=29)
    public Date getDttInitVisitRouteC() {
        return this.dttInitVisitRouteC;
    }
    
    public void setDttInitVisitRouteC(Date dttInitVisitRouteC) {
        this.dttInitVisitRouteC = dttInitVisitRouteC;
    }

    
    @Column(name="lkp_order__c", length=18)
    public String getLkpOrderC() {
        return this.lkpOrderC;
    }
    
    public void setLkpOrderC(String lkpOrderC) {
        this.lkpOrderC = lkpOrderC;
    }

    
    @Column(name="priority", length=40)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="recordtypeid", length=18)
    public String getRecordtypeid() {
        return this.recordtypeid;
    }
    
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }

    
    @Column(name="origin", length=40)
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    
    @Column(name="txt_visit_weeks__c", length=12)
    public String getTxtVisitWeeksC() {
        return this.txtVisitWeeksC;
    }
    
    public void setTxtVisitWeeksC(String txtVisitWeeksC) {
        this.txtVisitWeeksC = txtVisitWeeksC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_init_call_route__c", length=29)
    public Date getDttInitCallRouteC() {
        return this.dttInitCallRouteC;
    }
    
    public void setDttInitCallRouteC(Date dttInitCallRouteC) {
        this.dttInitCallRouteC = dttInitCallRouteC;
    }

    
    @Column(name="accountid", length=18)
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    
    @Column(name="chk_client_without_call_route__c")
    public Boolean getChkClientWithoutCallRouteC() {
        return this.chkClientWithoutCallRouteC;
    }
    
    public void setChkClientWithoutCallRouteC(Boolean chkClientWithoutCallRouteC) {
        this.chkClientWithoutCallRouteC = chkClientWithoutCallRouteC;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="pck_case_subtype__c")
    public String getPckCaseSubtypeC() {
        return this.pckCaseSubtypeC;
    }
    
    public void setPckCaseSubtypeC(String pckCaseSubtypeC) {
        this.pckCaseSubtypeC = pckCaseSubtypeC;
    }

    
    @Column(name="status", length=40)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="txt_call_weeks__c", length=12)
    public String getTxtCallWeeksC() {
        return this.txtCallWeeksC;
    }
    
    public void setTxtCallWeeksC(String txtCallWeeksC) {
        this.txtCallWeeksC = txtCallWeeksC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="case_type__c")
    public String getCaseTypeC() {
        return this.caseTypeC;
    }
    
    public void setCaseTypeC(String caseTypeC) {
        this.caseTypeC = caseTypeC;
    }

    
    @Column(name="type", length=40)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="contactid", length=18)
    public String getContactid() {
        return this.contactid;
    }
    
    public void setContactid(String contactid) {
        this.contactid = contactid;
    }

    
    @Column(name="case_sub_type__c")
    public String getCaseSubTypeC() {
        return this.caseSubTypeC;
    }
    
    public void setCaseSubTypeC(String caseSubTypeC) {
        this.caseSubTypeC = caseSubTypeC;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="lkp_contact_person__c", length=18)
    public String getLkpContactPersonC() {
        return this.lkpContactPersonC;
    }
    
    public void setLkpContactPersonC(String lkpContactPersonC) {
        this.lkpContactPersonC = lkpContactPersonC;
    }




}


