package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CheckAssortedProductC generated by hbm2java
 */
@Entity
@Table(name="check_assorted_product__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class CheckAssortedProductC  implements java.io.Serializable {


     private Integer id;
     private String accountC;
     private Date createddate;
     private Date fechaFinC;
     private Date fechaInicioC;
     private String hcErr;
     private String hcLastop;
     private Boolean isdeleted;
     private String name;
     private String sfid;
     private Date systemmodstamp;

    public CheckAssortedProductC() {
    }

	
    public CheckAssortedProductC(Integer id) {
        this.id = id;
    }
    public CheckAssortedProductC(Integer id, String accountC, Date createddate, Date fechaFinC, Date fechaInicioC, String hcErr, String hcLastop, Boolean isdeleted, String name, String sfid, Date systemmodstamp) {
       this.id = id;
       this.accountC = accountC;
       this.createddate = createddate;
       this.fechaFinC = fechaFinC;
       this.fechaInicioC = fechaInicioC;
       this.hcErr = hcErr;
       this.hcLastop = hcLastop;
       this.isdeleted = isdeleted;
       this.name = name;
       this.sfid = sfid;
       this.systemmodstamp = systemmodstamp;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="account__c", length=18)
    public String getAccountC() {
        return this.accountC;
    }
    
    public void setAccountC(String accountC) {
        this.accountC = accountC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin__c", length=13)
    public Date getFechaFinC() {
        return this.fechaFinC;
    }
    
    public void setFechaFinC(Date fechaFinC) {
        this.fechaFinC = fechaFinC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio__c", length=13)
    public Date getFechaInicioC() {
        return this.fechaInicioC;
    }
    
    public void setFechaInicioC(Date fechaInicioC) {
        this.fechaInicioC = fechaInicioC;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }




}


