package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CheckProductC generated by hbm2java
 */
@Entity
@Table(name="check_product__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class CheckProductC  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean promocionadoC;
     private Boolean folletoC;
     private String checkAssortedProductC;
     private Double numeroDeFacingC;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private Boolean cabeceraC;
     private Boolean enTiendaC;
     private String productC;
     private Double descuentoPromociNC;
     private Date createddate;
     private Double precioC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String checkPromotionProductC;
     private Boolean chkRoturaC;

    public CheckProductC() {
    }

	
    public CheckProductC(Integer id) {
        this.id = id;
    }
    public CheckProductC(Integer id, String name, Boolean promocionadoC, Boolean folletoC, String checkAssortedProductC, Double numeroDeFacingC, Boolean isdeleted, Date systemmodstamp, Boolean cabeceraC, Boolean enTiendaC, String productC, Double descuentoPromociNC, Date createddate, Double precioC, String sfid, String hcLastop, String hcErr, String checkPromotionProductC, Boolean chkRoturaC) {
       this.id = id;
       this.name = name;
       this.promocionadoC = promocionadoC;
       this.folletoC = folletoC;
       this.checkAssortedProductC = checkAssortedProductC;
       this.numeroDeFacingC = numeroDeFacingC;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.cabeceraC = cabeceraC;
       this.enTiendaC = enTiendaC;
       this.productC = productC;
       this.descuentoPromociNC = descuentoPromociNC;
       this.createddate = createddate;
       this.precioC = precioC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.checkPromotionProductC = checkPromotionProductC;
       this.chkRoturaC = chkRoturaC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="promocionado__c")
    public Boolean getPromocionadoC() {
        return this.promocionadoC;
    }
    
    public void setPromocionadoC(Boolean promocionadoC) {
        this.promocionadoC = promocionadoC;
    }

    
    @Column(name="folleto__c")
    public Boolean getFolletoC() {
        return this.folletoC;
    }
    
    public void setFolletoC(Boolean folletoC) {
        this.folletoC = folletoC;
    }

    
    @Column(name="check_assorted_product__c", length=18)
    public String getCheckAssortedProductC() {
        return this.checkAssortedProductC;
    }
    
    public void setCheckAssortedProductC(String checkAssortedProductC) {
        this.checkAssortedProductC = checkAssortedProductC;
    }

    
    @Column(name="numero_de_facing__c", precision=17, scale=17)
    public Double getNumeroDeFacingC() {
        return this.numeroDeFacingC;
    }
    
    public void setNumeroDeFacingC(Double numeroDeFacingC) {
        this.numeroDeFacingC = numeroDeFacingC;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="cabecera__c")
    public Boolean getCabeceraC() {
        return this.cabeceraC;
    }
    
    public void setCabeceraC(Boolean cabeceraC) {
        this.cabeceraC = cabeceraC;
    }

    
    @Column(name="en_tienda__c")
    public Boolean getEnTiendaC() {
        return this.enTiendaC;
    }
    
    public void setEnTiendaC(Boolean enTiendaC) {
        this.enTiendaC = enTiendaC;
    }

    
    @Column(name="product__c", length=18)
    public String getProductC() {
        return this.productC;
    }
    
    public void setProductC(String productC) {
        this.productC = productC;
    }

    
    @Column(name="descuento_promoci_n__c", precision=17, scale=17)
    public Double getDescuentoPromociNC() {
        return this.descuentoPromociNC;
    }
    
    public void setDescuentoPromociNC(Double descuentoPromociNC) {
        this.descuentoPromociNC = descuentoPromociNC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="precio__c", precision=17, scale=17)
    public Double getPrecioC() {
        return this.precioC;
    }
    
    public void setPrecioC(Double precioC) {
        this.precioC = precioC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="check_promotion_product__c", length=18)
    public String getCheckPromotionProductC() {
        return this.checkPromotionProductC;
    }
    
    public void setCheckPromotionProductC(String checkPromotionProductC) {
        this.checkPromotionProductC = checkPromotionProductC;
    }

    
    @Column(name="chk_rotura__c")
    public Boolean getChkRoturaC() {
        return this.chkRoturaC;
    }
    
    public void setChkRoturaC(Boolean chkRoturaC) {
        this.chkRoturaC = chkRoturaC;
    }




}


