package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,schema="salesforce"
)
public class Cliente  implements java.io.Serializable {


     private ClienteId id;

    public Cliente() {
    }

    public Cliente(ClienteId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="baseRef", column=@Column(name="base_ref", nullable=false) ), 
        @AttributeOverride(name="customercode", column=@Column(name="customercode", nullable=false) ), 
        @AttributeOverride(name="pais", column=@Column(name="pais", nullable=false) ), 
        @AttributeOverride(name="valor", column=@Column(name="valor", nullable=false) ) } )
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }




}


