package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Contact  implements java.io.Serializable {


     private Integer id;
     private String lastname;
     private String pckTypeC;
     private String recordtypeid;
     private String accountid;
     private Boolean mainContactC;
     private String name;
     private String mobilephone;
     private String phone;
     private String ownerid;
     private Boolean isdeleted;
     private String homephone;
     private Date systemmodstamp;
     private Date createddate;
     private String firstname;
     private String email;
     private String otherphone;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public Contact() {
    }

	
    public Contact(Integer id) {
        this.id = id;
    }
    public Contact(Integer id, String lastname, String pckTypeC, String recordtypeid, String accountid, Boolean mainContactC, String name, String mobilephone, String phone, String ownerid, Boolean isdeleted, String homephone, Date systemmodstamp, Date createddate, String firstname, String email, String otherphone, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.lastname = lastname;
       this.pckTypeC = pckTypeC;
       this.recordtypeid = recordtypeid;
       this.accountid = accountid;
       this.mainContactC = mainContactC;
       this.name = name;
       this.mobilephone = mobilephone;
       this.phone = phone;
       this.ownerid = ownerid;
       this.isdeleted = isdeleted;
       this.homephone = homephone;
       this.systemmodstamp = systemmodstamp;
       this.createddate = createddate;
       this.firstname = firstname;
       this.email = email;
       this.otherphone = otherphone;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="lastname", length=80)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="pck_type__c")
    public String getPckTypeC() {
        return this.pckTypeC;
    }
    
    public void setPckTypeC(String pckTypeC) {
        this.pckTypeC = pckTypeC;
    }

    
    @Column(name="recordtypeid", length=18)
    public String getRecordtypeid() {
        return this.recordtypeid;
    }
    
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }

    
    @Column(name="accountid", length=18)
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    
    @Column(name="main_contact__c")
    public Boolean getMainContactC() {
        return this.mainContactC;
    }
    
    public void setMainContactC(Boolean mainContactC) {
        this.mainContactC = mainContactC;
    }

    
    @Column(name="name", length=121)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="mobilephone", length=40)
    public String getMobilephone() {
        return this.mobilephone;
    }
    
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    
    @Column(name="phone", length=40)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="homephone", length=40)
    public String getHomephone() {
        return this.homephone;
    }
    
    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="firstname", length=40)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="email", length=80)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="otherphone", length=40)
    public String getOtherphone() {
        return this.otherphone;
    }
    
    public void setOtherphone(String otherphone) {
        this.otherphone = otherphone;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


