package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Event  implements java.io.Serializable {


     private Integer id;
     private String activityStatusC;
     private String recordtypeid;
     private String accountid;
     private String txtCommercialReportC;
     private Date enddate;
     private String txtCommercialIncidentC;
     private String subject;
     private String ownerid;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private Date enddatetime;
     private Date createddate;
     private String type;
     private String description;
     private Date startdatetime;
     private Date activitydate;
     private String whatid;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public Event() {
    }

	
    public Event(Integer id) {
        this.id = id;
    }
    public Event(Integer id, String activityStatusC, String recordtypeid, String accountid, String txtCommercialReportC, Date enddate, String txtCommercialIncidentC, String subject, String ownerid, Boolean isdeleted, Date systemmodstamp, Date enddatetime, Date createddate, String type, String description, Date startdatetime, Date activitydate, String whatid, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.activityStatusC = activityStatusC;
       this.recordtypeid = recordtypeid;
       this.accountid = accountid;
       this.txtCommercialReportC = txtCommercialReportC;
       this.enddate = enddate;
       this.txtCommercialIncidentC = txtCommercialIncidentC;
       this.subject = subject;
       this.ownerid = ownerid;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.enddatetime = enddatetime;
       this.createddate = createddate;
       this.type = type;
       this.description = description;
       this.startdatetime = startdatetime;
       this.activitydate = activitydate;
       this.whatid = whatid;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="activity_status__c")
    public String getActivityStatusC() {
        return this.activityStatusC;
    }
    
    public void setActivityStatusC(String activityStatusC) {
        this.activityStatusC = activityStatusC;
    }

    
    @Column(name="recordtypeid", length=18)
    public String getRecordtypeid() {
        return this.recordtypeid;
    }
    
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }

    
    @Column(name="accountid", length=18)
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    
    @Column(name="txt_commercial_report__c")
    public String getTxtCommercialReportC() {
        return this.txtCommercialReportC;
    }
    
    public void setTxtCommercialReportC(String txtCommercialReportC) {
        this.txtCommercialReportC = txtCommercialReportC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="enddate", length=13)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    
    @Column(name="txt_commercial_incident__c")
    public String getTxtCommercialIncidentC() {
        return this.txtCommercialIncidentC;
    }
    
    public void setTxtCommercialIncidentC(String txtCommercialIncidentC) {
        this.txtCommercialIncidentC = txtCommercialIncidentC;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="enddatetime", length=29)
    public Date getEnddatetime() {
        return this.enddatetime;
    }
    
    public void setEnddatetime(Date enddatetime) {
        this.enddatetime = enddatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="type", length=40)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="startdatetime", length=29)
    public Date getStartdatetime() {
        return this.startdatetime;
    }
    
    public void setStartdatetime(Date startdatetime) {
        this.startdatetime = startdatetime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="activitydate", length=13)
    public Date getActivitydate() {
        return this.activitydate;
    }
    
    public void setActivitydate(Date activitydate) {
        this.activitydate = activitydate;
    }

    
    @Column(name="whatid", length=18)
    public String getWhatid() {
        return this.whatid;
    }
    
    public void setWhatid(String whatid) {
        this.whatid = whatid;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


