package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EvolutionC generated by hbm2java
 */
@Entity
@Table(name="evolution__c"
    ,schema="salesforce"
    , uniqueConstraints = {@UniqueConstraint(columnNames="heroku_rdc_id__c"), @UniqueConstraint(columnNames="sfid")} 
)
public class EvolutionC  implements java.io.Serializable {


     private Integer id;
     private Date createddate;
     private Boolean isdeleted;
     private String name;
     private Date systemmodstamp;
     private Double lastyearsalesC;
     private String userC;
     private Double currentyearsalesC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String herokuRdcIdC;

    public EvolutionC() {
    }

	
    public EvolutionC(Integer id) {
        this.id = id;
    }
    public EvolutionC(Integer id, Date createddate, Boolean isdeleted, String name, Date systemmodstamp, Double lastyearsalesC, String userC, Double currentyearsalesC, String sfid, String hcLastop, String hcErr, String herokuRdcIdC) {
       this.id = id;
       this.createddate = createddate;
       this.isdeleted = isdeleted;
       this.name = name;
       this.systemmodstamp = systemmodstamp;
       this.lastyearsalesC = lastyearsalesC;
       this.userC = userC;
       this.currentyearsalesC = currentyearsalesC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.herokuRdcIdC = herokuRdcIdC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="lastyearsales__c", precision=17, scale=17)
    public Double getLastyearsalesC() {
        return this.lastyearsalesC;
    }
    
    public void setLastyearsalesC(Double lastyearsalesC) {
        this.lastyearsalesC = lastyearsalesC;
    }

    
    @Column(name="user__c", length=18)
    public String getUserC() {
        return this.userC;
    }
    
    public void setUserC(String userC) {
        this.userC = userC;
    }

    
    @Column(name="currentyearsales__c", precision=17, scale=17)
    public Double getCurrentyearsalesC() {
        return this.currentyearsalesC;
    }
    
    public void setCurrentyearsalesC(Double currentyearsalesC) {
        this.currentyearsalesC = currentyearsalesC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="heroku_rdc_id__c", unique=true)
    public String getHerokuRdcIdC() {
        return this.herokuRdcIdC;
    }
    
    public void setHerokuRdcIdC(String herokuRdcIdC) {
        this.herokuRdcIdC = herokuRdcIdC;
    }




}


