package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FechaCompra generated by hbm2java
 */
@Entity
@Table(name="fecha_compra"
    ,schema="salesforce"
)
public class FechaCompra  implements java.io.Serializable {


     private FechaCompraId id;

    public FechaCompra() {
    }

    public FechaCompra(FechaCompraId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="baseRef", column=@Column(name="base_ref", nullable=false) ), 
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code", nullable=false) ), 
        @AttributeOverride(name="months", column=@Column(name="months", nullable=false) ), 
        @AttributeOverride(name="years", column=@Column(name="years", nullable=false) ) } )
    public FechaCompraId getId() {
        return this.id;
    }
    
    public void setId(FechaCompraId id) {
        this.id = id;
    }




}


