package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FechaCompraId generated by hbm2java
 */
@Embeddable
public class FechaCompraId  implements java.io.Serializable {


     private String baseRef;
     private String customerCode;
     private Integer months;
     private Integer years;

    public FechaCompraId() {
    }

    public FechaCompraId(String baseRef, String customerCode, Integer months, Integer years) {
       this.baseRef = baseRef;
       this.customerCode = customerCode;
       this.months = months;
       this.years = years;
    }
   


    @Column(name="base_ref", nullable=false)
    public String getBaseRef() {
        return this.baseRef;
    }
    
    public void setBaseRef(String baseRef) {
        this.baseRef = baseRef;
    }


    @Column(name="customer_code", nullable=false)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }


    @Column(name="months", nullable=false)
    public Integer getMonths() {
        return this.months;
    }
    
    public void setMonths(Integer months) {
        this.months = months;
    }


    @Column(name="years", nullable=false)
    public Integer getYears() {
        return this.years;
    }
    
    public void setYears(Integer years) {
        this.years = years;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FechaCompraId) ) return false;
		 FechaCompraId castOther = ( FechaCompraId ) other; 
         
		 return ( (this.getBaseRef()==castOther.getBaseRef()) || ( this.getBaseRef()!=null && castOther.getBaseRef()!=null && this.getBaseRef().equals(castOther.getBaseRef()) ) )
 && ( (this.getCustomerCode()==castOther.getCustomerCode()) || ( this.getCustomerCode()!=null && castOther.getCustomerCode()!=null && this.getCustomerCode().equals(castOther.getCustomerCode()) ) )
 && ( (this.getMonths()==castOther.getMonths()) || ( this.getMonths()!=null && castOther.getMonths()!=null && this.getMonths().equals(castOther.getMonths()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBaseRef() == null ? 0 : this.getBaseRef().hashCode() );
         result = 37 * result + ( getCustomerCode() == null ? 0 : this.getCustomerCode().hashCode() );
         result = 37 * result + ( getMonths() == null ? 0 : this.getMonths().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         return result;
   }   


}


