package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IntermediaCountry generated by hbm2java
 */
@Entity
@Table(name="intermedia_country"
    ,schema="salesforce"
)
public class IntermediaCountry  implements java.io.Serializable {


     private IntermediaCountryId id;

    public IntermediaCountry() {
    }

    public IntermediaCountry(IntermediaCountryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="country", column=@Column(name="country") ), 
        @AttributeOverride(name="numCustomers", column=@Column(name="num_customers") ), 
        @AttributeOverride(name="cadena", column=@Column(name="cadena") ), 
        @AttributeOverride(name="accType", column=@Column(name="acc_type") ), 
        @AttributeOverride(name="baseReference", column=@Column(name="base_reference") ) } )
    public IntermediaCountryId getId() {
        return this.id;
    }
    
    public void setId(IntermediaCountryId id) {
        this.id = id;
    }




}


