package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LightCampaignC generated by hbm2java
 */
@Entity
@Table(name="light_campaign__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class LightCampaignC  implements java.io.Serializable {


     private Integer id;
     private String pckTypeC;
     private Double numMaxQuantityC;
     private String recordtypeid;
     private String txtDiscountCodeC;
     private String discountLineCodeC;
     private Date datEndDateC;
     private Boolean frmlActiveC;
     private String name;
     private Boolean isdeleted;
     private Date datStartDateC;
     private Date systemmodstamp;
     private Double numMinQuantityC;
     private String pckUnitTypeC;
     private String txtDescriptionC;
     private Date createddate;
     private Double numDiscountLineValueC;
     private Double numPromoProductQuantityC;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public LightCampaignC() {
    }

	
    public LightCampaignC(Integer id) {
        this.id = id;
    }
    public LightCampaignC(Integer id, String pckTypeC, Double numMaxQuantityC, String recordtypeid, String txtDiscountCodeC, String discountLineCodeC, Date datEndDateC, Boolean frmlActiveC, String name, Boolean isdeleted, Date datStartDateC, Date systemmodstamp, Double numMinQuantityC, String pckUnitTypeC, String txtDescriptionC, Date createddate, Double numDiscountLineValueC, Double numPromoProductQuantityC, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.pckTypeC = pckTypeC;
       this.numMaxQuantityC = numMaxQuantityC;
       this.recordtypeid = recordtypeid;
       this.txtDiscountCodeC = txtDiscountCodeC;
       this.discountLineCodeC = discountLineCodeC;
       this.datEndDateC = datEndDateC;
       this.frmlActiveC = frmlActiveC;
       this.name = name;
       this.isdeleted = isdeleted;
       this.datStartDateC = datStartDateC;
       this.systemmodstamp = systemmodstamp;
       this.numMinQuantityC = numMinQuantityC;
       this.pckUnitTypeC = pckUnitTypeC;
       this.txtDescriptionC = txtDescriptionC;
       this.createddate = createddate;
       this.numDiscountLineValueC = numDiscountLineValueC;
       this.numPromoProductQuantityC = numPromoProductQuantityC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="pck_type__c")
    public String getPckTypeC() {
        return this.pckTypeC;
    }
    
    public void setPckTypeC(String pckTypeC) {
        this.pckTypeC = pckTypeC;
    }

    
    @Column(name="num_max_quantity__c", precision=17, scale=17)
    public Double getNumMaxQuantityC() {
        return this.numMaxQuantityC;
    }
    
    public void setNumMaxQuantityC(Double numMaxQuantityC) {
        this.numMaxQuantityC = numMaxQuantityC;
    }

    
    @Column(name="recordtypeid", length=18)
    public String getRecordtypeid() {
        return this.recordtypeid;
    }
    
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }

    
    @Column(name="txt_discount_code__c", length=6)
    public String getTxtDiscountCodeC() {
        return this.txtDiscountCodeC;
    }
    
    public void setTxtDiscountCodeC(String txtDiscountCodeC) {
        this.txtDiscountCodeC = txtDiscountCodeC;
    }

    
    @Column(name="discount_line_code__c", length=6)
    public String getDiscountLineCodeC() {
        return this.discountLineCodeC;
    }
    
    public void setDiscountLineCodeC(String discountLineCodeC) {
        this.discountLineCodeC = discountLineCodeC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dat_end_date__c", length=13)
    public Date getDatEndDateC() {
        return this.datEndDateC;
    }
    
    public void setDatEndDateC(Date datEndDateC) {
        this.datEndDateC = datEndDateC;
    }

    
    @Column(name="frml_active__c")
    public Boolean getFrmlActiveC() {
        return this.frmlActiveC;
    }
    
    public void setFrmlActiveC(Boolean frmlActiveC) {
        this.frmlActiveC = frmlActiveC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dat_start_date__c", length=13)
    public Date getDatStartDateC() {
        return this.datStartDateC;
    }
    
    public void setDatStartDateC(Date datStartDateC) {
        this.datStartDateC = datStartDateC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="num_min_quantity__c", precision=17, scale=17)
    public Double getNumMinQuantityC() {
        return this.numMinQuantityC;
    }
    
    public void setNumMinQuantityC(Double numMinQuantityC) {
        this.numMinQuantityC = numMinQuantityC;
    }

    
    @Column(name="pck_unit_type__c")
    public String getPckUnitTypeC() {
        return this.pckUnitTypeC;
    }
    
    public void setPckUnitTypeC(String pckUnitTypeC) {
        this.pckUnitTypeC = pckUnitTypeC;
    }

    
    @Column(name="txt_description__c")
    public String getTxtDescriptionC() {
        return this.txtDescriptionC;
    }
    
    public void setTxtDescriptionC(String txtDescriptionC) {
        this.txtDescriptionC = txtDescriptionC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="num_discount_line_value__c", precision=17, scale=17)
    public Double getNumDiscountLineValueC() {
        return this.numDiscountLineValueC;
    }
    
    public void setNumDiscountLineValueC(Double numDiscountLineValueC) {
        this.numDiscountLineValueC = numDiscountLineValueC;
    }

    
    @Column(name="num_promo_product_quantity__c", precision=17, scale=17)
    public Double getNumPromoProductQuantityC() {
        return this.numPromoProductQuantityC;
    }
    
    public void setNumPromoProductQuantityC(Double numPromoProductQuantityC) {
        this.numPromoProductQuantityC = numPromoProductQuantityC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


