package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LightProduct generated by hbm2java
 */
@Entity
@Table(name="light_product"
    ,schema="salesforce"
)
public class LightProduct  implements java.io.Serializable {


     private long id;
     private String name;
     private String account;
     private String product;

    public LightProduct() {
    }

	
    public LightProduct(long id) {
        this.id = id;
    }
    public LightProduct(long id, String name, String account, String product) {
       this.id = id;
       this.name = name;
       this.account = account;
       this.product = product;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="account")
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }

    
    @Column(name="product")
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }




}


