package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LightMessagesC generated by hbm2java
 */
@Entity
@Table(name="light_messages__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class LightMessagesC  implements java.io.Serializable {


     private Integer id;
     private String lightMessagebodyC;
     private Date lightEnddateC;
     private String lightRecipientuserC;
     private String name;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private String lightParentmsgC;
     private Date createddate;
     private Date lightStartdateC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String lightBodyC;

    public LightMessagesC() {
    }

	
    public LightMessagesC(Integer id) {
        this.id = id;
    }
    public LightMessagesC(Integer id, String lightMessagebodyC, Date lightEnddateC, String lightRecipientuserC, String name, Boolean isdeleted, Date systemmodstamp, String lightParentmsgC, Date createddate, Date lightStartdateC, String sfid, String hcLastop, String hcErr, String lightBodyC) {
       this.id = id;
       this.lightMessagebodyC = lightMessagebodyC;
       this.lightEnddateC = lightEnddateC;
       this.lightRecipientuserC = lightRecipientuserC;
       this.name = name;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.lightParentmsgC = lightParentmsgC;
       this.createddate = createddate;
       this.lightStartdateC = lightStartdateC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.lightBodyC = lightBodyC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="light_messagebody__c")
    public String getLightMessagebodyC() {
        return this.lightMessagebodyC;
    }
    
    public void setLightMessagebodyC(String lightMessagebodyC) {
        this.lightMessagebodyC = lightMessagebodyC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="light_enddate__c", length=13)
    public Date getLightEnddateC() {
        return this.lightEnddateC;
    }
    
    public void setLightEnddateC(Date lightEnddateC) {
        this.lightEnddateC = lightEnddateC;
    }

    
    @Column(name="light_recipientuser__c", length=18)
    public String getLightRecipientuserC() {
        return this.lightRecipientuserC;
    }
    
    public void setLightRecipientuserC(String lightRecipientuserC) {
        this.lightRecipientuserC = lightRecipientuserC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="light_parentmsg__c", length=18)
    public String getLightParentmsgC() {
        return this.lightParentmsgC;
    }
    
    public void setLightParentmsgC(String lightParentmsgC) {
        this.lightParentmsgC = lightParentmsgC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="light_startdate__c", length=13)
    public Date getLightStartdateC() {
        return this.lightStartdateC;
    }
    
    public void setLightStartdateC(Date lightStartdateC) {
        this.lightStartdateC = lightStartdateC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="light_body__c", length=100)
    public String getLightBodyC() {
        return this.lightBodyC;
    }
    
    public void setLightBodyC(String lightBodyC) {
        this.lightBodyC = lightBodyC;
    }




}


