package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LocalBudgetRdcC generated by hbm2java
 */
@Entity
@Table(name="local_budget_rdc__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class LocalBudgetRdcC  implements java.io.Serializable {


     private Integer id;
     private Date createddate;
     private Boolean isdeleted;
     private String name;
     private Date systemmodstamp;
     private Double presupuestoAsignadoC;
     private Double presupuestoConsumidoC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String ownerid;
     private Boolean activordcC;

    public LocalBudgetRdcC() {
    }

	
    public LocalBudgetRdcC(Integer id) {
        this.id = id;
    }
    public LocalBudgetRdcC(Integer id, Date createddate, Boolean isdeleted, String name, Date systemmodstamp, Double presupuestoAsignadoC, Double presupuestoConsumidoC, String sfid, String hcLastop, String hcErr, String ownerid, Boolean activordcC) {
       this.id = id;
       this.createddate = createddate;
       this.isdeleted = isdeleted;
       this.name = name;
       this.systemmodstamp = systemmodstamp;
       this.presupuestoAsignadoC = presupuestoAsignadoC;
       this.presupuestoConsumidoC = presupuestoConsumidoC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.ownerid = ownerid;
       this.activordcC = activordcC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="presupuesto_asignado__c", precision=17, scale=17)
    public Double getPresupuestoAsignadoC() {
        return this.presupuestoAsignadoC;
    }
    
    public void setPresupuestoAsignadoC(Double presupuestoAsignadoC) {
        this.presupuestoAsignadoC = presupuestoAsignadoC;
    }

    
    @Column(name="presupuesto_consumido__c", precision=17, scale=17)
    public Double getPresupuestoConsumidoC() {
        return this.presupuestoConsumidoC;
    }
    
    public void setPresupuestoConsumidoC(Double presupuestoConsumidoC) {
        this.presupuestoConsumidoC = presupuestoConsumidoC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="activordc__c")
    public Boolean getActivordcC() {
        return this.activordcC;
    }
    
    public void setActivordcC(Boolean activordcC) {
        this.activordcC = activordcC;
    }




}


