package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MarketCatalogsC generated by hbm2java
 */
@Entity
@Table(name="market_catalogs__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class MarketCatalogsC  implements java.io.Serializable {


     private Integer id;
     private Boolean longTermPromotionalC;
     private String pckSalesEntityC;
     private String pckChannelC;
     private Boolean chkActiveVisibilityDateC;
     private String txtStartDateC;
     private String name;
     private String pckItemStatusC;
     private Date datePromotionalEndDateC;
     private Boolean isdeleted;
     private String itemC;
     private Date systemmodstamp;
     private Boolean chkActivePromotionalC;
     private Date createddate;
     private Date datePromotionalStartDateC;
     private String txtVisibilityDateC;
     private String txtPromotionalPictureNameC;
     private String pckRoundingProfileC;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public MarketCatalogsC() {
    }

	
    public MarketCatalogsC(Integer id) {
        this.id = id;
    }
    public MarketCatalogsC(Integer id, Boolean longTermPromotionalC, String pckSalesEntityC, String pckChannelC, Boolean chkActiveVisibilityDateC, String txtStartDateC, String name, String pckItemStatusC, Date datePromotionalEndDateC, Boolean isdeleted, String itemC, Date systemmodstamp, Boolean chkActivePromotionalC, Date createddate, Date datePromotionalStartDateC, String txtVisibilityDateC, String txtPromotionalPictureNameC, String pckRoundingProfileC, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.longTermPromotionalC = longTermPromotionalC;
       this.pckSalesEntityC = pckSalesEntityC;
       this.pckChannelC = pckChannelC;
       this.chkActiveVisibilityDateC = chkActiveVisibilityDateC;
       this.txtStartDateC = txtStartDateC;
       this.name = name;
       this.pckItemStatusC = pckItemStatusC;
       this.datePromotionalEndDateC = datePromotionalEndDateC;
       this.isdeleted = isdeleted;
       this.itemC = itemC;
       this.systemmodstamp = systemmodstamp;
       this.chkActivePromotionalC = chkActivePromotionalC;
       this.createddate = createddate;
       this.datePromotionalStartDateC = datePromotionalStartDateC;
       this.txtVisibilityDateC = txtVisibilityDateC;
       this.txtPromotionalPictureNameC = txtPromotionalPictureNameC;
       this.pckRoundingProfileC = pckRoundingProfileC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="long_term_promotional__c")
    public Boolean getLongTermPromotionalC() {
        return this.longTermPromotionalC;
    }
    
    public void setLongTermPromotionalC(Boolean longTermPromotionalC) {
        this.longTermPromotionalC = longTermPromotionalC;
    }

    
    @Column(name="pck_sales_entity__c")
    public String getPckSalesEntityC() {
        return this.pckSalesEntityC;
    }
    
    public void setPckSalesEntityC(String pckSalesEntityC) {
        this.pckSalesEntityC = pckSalesEntityC;
    }

    
    @Column(name="pck_channel__c")
    public String getPckChannelC() {
        return this.pckChannelC;
    }
    
    public void setPckChannelC(String pckChannelC) {
        this.pckChannelC = pckChannelC;
    }

    
    @Column(name="chk_active_visibility_date__c")
    public Boolean getChkActiveVisibilityDateC() {
        return this.chkActiveVisibilityDateC;
    }
    
    public void setChkActiveVisibilityDateC(Boolean chkActiveVisibilityDateC) {
        this.chkActiveVisibilityDateC = chkActiveVisibilityDateC;
    }

    
    @Column(name="txt_start_date__c")
    public String getTxtStartDateC() {
        return this.txtStartDateC;
    }
    
    public void setTxtStartDateC(String txtStartDateC) {
        this.txtStartDateC = txtStartDateC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="pck_item_status__c")
    public String getPckItemStatusC() {
        return this.pckItemStatusC;
    }
    
    public void setPckItemStatusC(String pckItemStatusC) {
        this.pckItemStatusC = pckItemStatusC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_promotional_end_date__c", length=13)
    public Date getDatePromotionalEndDateC() {
        return this.datePromotionalEndDateC;
    }
    
    public void setDatePromotionalEndDateC(Date datePromotionalEndDateC) {
        this.datePromotionalEndDateC = datePromotionalEndDateC;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="item__c", length=18)
    public String getItemC() {
        return this.itemC;
    }
    
    public void setItemC(String itemC) {
        this.itemC = itemC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="chk_active_promotional__c")
    public Boolean getChkActivePromotionalC() {
        return this.chkActivePromotionalC;
    }
    
    public void setChkActivePromotionalC(Boolean chkActivePromotionalC) {
        this.chkActivePromotionalC = chkActivePromotionalC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_promotional_start_date__c", length=13)
    public Date getDatePromotionalStartDateC() {
        return this.datePromotionalStartDateC;
    }
    
    public void setDatePromotionalStartDateC(Date datePromotionalStartDateC) {
        this.datePromotionalStartDateC = datePromotionalStartDateC;
    }

    
    @Column(name="txt_visibility_date__c")
    public String getTxtVisibilityDateC() {
        return this.txtVisibilityDateC;
    }
    
    public void setTxtVisibilityDateC(String txtVisibilityDateC) {
        this.txtVisibilityDateC = txtVisibilityDateC;
    }

    
    @Column(name="txt_promotional_picture_name__c", length=100)
    public String getTxtPromotionalPictureNameC() {
        return this.txtPromotionalPictureNameC;
    }
    
    public void setTxtPromotionalPictureNameC(String txtPromotionalPictureNameC) {
        this.txtPromotionalPictureNameC = txtPromotionalPictureNameC;
    }

    
    @Column(name="pck_rounding_profile__c")
    public String getPckRoundingProfileC() {
        return this.pckRoundingProfileC;
    }
    
    public void setPckRoundingProfileC(String pckRoundingProfileC) {
        this.pckRoundingProfileC = pckRoundingProfileC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


