package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MtPicklist generated by hbm2java
 */
@Entity
@Table(name="mt_picklist"
    ,schema="salesforce"
)
public class MtPicklist  implements java.io.Serializable {


     private long id;
     private String nombrepicklist;
     private String valor;
     private String codigovalor;
     private String dependenciavalor;
     private String dependenciapck;
     private String dependenciapck2;
     private String dependenciavalor2;

    public MtPicklist() {
    }

	
    public MtPicklist(long id) {
        this.id = id;
    }
    public MtPicklist(long id, String nombrepicklist, String valor, String codigovalor, String dependenciavalor, String dependenciapck, String dependenciapck2, String dependenciavalor2) {
       this.id = id;
       this.nombrepicklist = nombrepicklist;
       this.valor = valor;
       this.codigovalor = codigovalor;
       this.dependenciavalor = dependenciavalor;
       this.dependenciapck = dependenciapck;
       this.dependenciapck2 = dependenciapck2;
       this.dependenciavalor2 = dependenciavalor2;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="nombrepicklist")
    public String getNombrepicklist() {
        return this.nombrepicklist;
    }
    
    public void setNombrepicklist(String nombrepicklist) {
        this.nombrepicklist = nombrepicklist;
    }

    
    @Column(name="valor")
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="codigovalor")
    public String getCodigovalor() {
        return this.codigovalor;
    }
    
    public void setCodigovalor(String codigovalor) {
        this.codigovalor = codigovalor;
    }

    
    @Column(name="dependenciavalor")
    public String getDependenciavalor() {
        return this.dependenciavalor;
    }
    
    public void setDependenciavalor(String dependenciavalor) {
        this.dependenciavalor = dependenciavalor;
    }

    
    @Column(name="dependenciapck")
    public String getDependenciapck() {
        return this.dependenciapck;
    }
    
    public void setDependenciapck(String dependenciapck) {
        this.dependenciapck = dependenciapck;
    }

    
    @Column(name="dependenciapck2")
    public String getDependenciapck2() {
        return this.dependenciapck2;
    }
    
    public void setDependenciapck2(String dependenciapck2) {
        this.dependenciapck2 = dependenciapck2;
    }

    
    @Column(name="dependenciavalor2")
    public String getDependenciavalor2() {
        return this.dependenciavalor2;
    }
    
    public void setDependenciavalor2(String dependenciavalor2) {
        this.dependenciavalor2 = dependenciavalor2;
    }




}


