package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MtReferenciasBaseId generated by hbm2java
 */
@Embeddable
public class MtReferenciasBaseId  implements java.io.Serializable {


     private String surtidos;
     private String refBase;
     private String chains;
     private String subchain;
     private String accType;
     private Boolean status;
     private String description;
     private String herarchies;

    public MtReferenciasBaseId() {
    }

    public MtReferenciasBaseId(String surtidos, String refBase, String chains, String subchain, String accType, Boolean status, String description, String herarchies) {
       this.surtidos = surtidos;
       this.refBase = refBase;
       this.chains = chains;
       this.subchain = subchain;
       this.accType = accType;
       this.status = status;
       this.description = description;
       this.herarchies = herarchies;
    }
   


    @Column(name="surtidos")
    public String getSurtidos() {
        return this.surtidos;
    }
    
    public void setSurtidos(String surtidos) {
        this.surtidos = surtidos;
    }


    @Column(name="ref_base")
    public String getRefBase() {
        return this.refBase;
    }
    
    public void setRefBase(String refBase) {
        this.refBase = refBase;
    }


    @Column(name="chains")
    public String getChains() {
        return this.chains;
    }
    
    public void setChains(String chains) {
        this.chains = chains;
    }


    @Column(name="subchain")
    public String getSubchain() {
        return this.subchain;
    }
    
    public void setSubchain(String subchain) {
        this.subchain = subchain;
    }


    @Column(name="acc_type")
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }


    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }


    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name="herarchies")
    public String getHerarchies() {
        return this.herarchies;
    }
    
    public void setHerarchies(String herarchies) {
        this.herarchies = herarchies;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MtReferenciasBaseId) ) return false;
		 MtReferenciasBaseId castOther = ( MtReferenciasBaseId ) other; 
         
		 return ( (this.getSurtidos()==castOther.getSurtidos()) || ( this.getSurtidos()!=null && castOther.getSurtidos()!=null && this.getSurtidos().equals(castOther.getSurtidos()) ) )
 && ( (this.getRefBase()==castOther.getRefBase()) || ( this.getRefBase()!=null && castOther.getRefBase()!=null && this.getRefBase().equals(castOther.getRefBase()) ) )
 && ( (this.getChains()==castOther.getChains()) || ( this.getChains()!=null && castOther.getChains()!=null && this.getChains().equals(castOther.getChains()) ) )
 && ( (this.getSubchain()==castOther.getSubchain()) || ( this.getSubchain()!=null && castOther.getSubchain()!=null && this.getSubchain().equals(castOther.getSubchain()) ) )
 && ( (this.getAccType()==castOther.getAccType()) || ( this.getAccType()!=null && castOther.getAccType()!=null && this.getAccType().equals(castOther.getAccType()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getHerarchies()==castOther.getHerarchies()) || ( this.getHerarchies()!=null && castOther.getHerarchies()!=null && this.getHerarchies().equals(castOther.getHerarchies()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSurtidos() == null ? 0 : this.getSurtidos().hashCode() );
         result = 37 * result + ( getRefBase() == null ? 0 : this.getRefBase().hashCode() );
         result = 37 * result + ( getChains() == null ? 0 : this.getChains().hashCode() );
         result = 37 * result + ( getSubchain() == null ? 0 : this.getSubchain().hashCode() );
         result = 37 * result + ( getAccType() == null ? 0 : this.getAccType().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getHerarchies() == null ? 0 : this.getHerarchies().hashCode() );
         return result;
   }   


}


