package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ObjetivoCualitativoC generated by hbm2java
 */
@Entity
@Table(name="objetivo_cualitativo__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class ObjetivoCualitativoC  implements java.io.Serializable {


     private Integer id;
     private Date datEnddateC;
     private Double numPdnaC;
     private String txtAccountTypeC;
     private String txtProfileC;
     private String lkpUserC;
     private String name;
     private String txtChannelC;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private String txtChainC;
     private Double achievementC;
     private Date createddate;
     private String txtBaseReferenceC;
     private Date datStartdateC;
     private String txtSalesEntityC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String pckChainC;
     private String pckAccountTypeC;
     private String lkpBaseReferenceC;
     private Date fechaFinCalculoC;
     private Date fechaInicioCalculoC;

    public ObjetivoCualitativoC() {
    }

	
    public ObjetivoCualitativoC(Integer id) {
        this.id = id;
    }
    public ObjetivoCualitativoC(Integer id, Date datEnddateC, Double numPdnaC, String txtAccountTypeC, String txtProfileC, String lkpUserC, String name, String txtChannelC, Boolean isdeleted, Date systemmodstamp, String txtChainC, Double achievementC, Date createddate, String txtBaseReferenceC, Date datStartdateC, String txtSalesEntityC, String sfid, String hcLastop, String hcErr, String pckChainC, String pckAccountTypeC, String lkpBaseReferenceC, Date fechaFinCalculoC, Date fechaInicioCalculoC) {
       this.id = id;
       this.datEnddateC = datEnddateC;
       this.numPdnaC = numPdnaC;
       this.txtAccountTypeC = txtAccountTypeC;
       this.txtProfileC = txtProfileC;
       this.lkpUserC = lkpUserC;
       this.name = name;
       this.txtChannelC = txtChannelC;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.txtChainC = txtChainC;
       this.achievementC = achievementC;
       this.createddate = createddate;
       this.txtBaseReferenceC = txtBaseReferenceC;
       this.datStartdateC = datStartdateC;
       this.txtSalesEntityC = txtSalesEntityC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.pckChainC = pckChainC;
       this.pckAccountTypeC = pckAccountTypeC;
       this.lkpBaseReferenceC = lkpBaseReferenceC;
       this.fechaFinCalculoC = fechaFinCalculoC;
       this.fechaInicioCalculoC = fechaInicioCalculoC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dat_enddate__c", length=13)
    public Date getDatEnddateC() {
        return this.datEnddateC;
    }
    
    public void setDatEnddateC(Date datEnddateC) {
        this.datEnddateC = datEnddateC;
    }

    
    @Column(name="num_pdna__c", precision=17, scale=17)
    public Double getNumPdnaC() {
        return this.numPdnaC;
    }
    
    public void setNumPdnaC(Double numPdnaC) {
        this.numPdnaC = numPdnaC;
    }

    
    @Column(name="txt_account_type__c", length=50)
    public String getTxtAccountTypeC() {
        return this.txtAccountTypeC;
    }
    
    public void setTxtAccountTypeC(String txtAccountTypeC) {
        this.txtAccountTypeC = txtAccountTypeC;
    }

    
    @Column(name="txt_profile__c", length=15)
    public String getTxtProfileC() {
        return this.txtProfileC;
    }
    
    public void setTxtProfileC(String txtProfileC) {
        this.txtProfileC = txtProfileC;
    }

    
    @Column(name="lkp_user__c", length=18)
    public String getLkpUserC() {
        return this.lkpUserC;
    }
    
    public void setLkpUserC(String lkpUserC) {
        this.lkpUserC = lkpUserC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="txt_channel__c", length=10)
    public String getTxtChannelC() {
        return this.txtChannelC;
    }
    
    public void setTxtChannelC(String txtChannelC) {
        this.txtChannelC = txtChannelC;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="txt_chain__c", length=50)
    public String getTxtChainC() {
        return this.txtChainC;
    }
    
    public void setTxtChainC(String txtChainC) {
        this.txtChainC = txtChainC;
    }

    
    @Column(name="achievement__c", precision=17, scale=17)
    public Double getAchievementC() {
        return this.achievementC;
    }
    
    public void setAchievementC(Double achievementC) {
        this.achievementC = achievementC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="txt_base_reference__c", length=15)
    public String getTxtBaseReferenceC() {
        return this.txtBaseReferenceC;
    }
    
    public void setTxtBaseReferenceC(String txtBaseReferenceC) {
        this.txtBaseReferenceC = txtBaseReferenceC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dat_startdate__c", length=13)
    public Date getDatStartdateC() {
        return this.datStartdateC;
    }
    
    public void setDatStartdateC(Date datStartdateC) {
        this.datStartdateC = datStartdateC;
    }

    
    @Column(name="txt_sales_entity__c", length=30)
    public String getTxtSalesEntityC() {
        return this.txtSalesEntityC;
    }
    
    public void setTxtSalesEntityC(String txtSalesEntityC) {
        this.txtSalesEntityC = txtSalesEntityC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="pck_chain__c")
    public String getPckChainC() {
        return this.pckChainC;
    }
    
    public void setPckChainC(String pckChainC) {
        this.pckChainC = pckChainC;
    }

    
    @Column(name="pck_account_type__c")
    public String getPckAccountTypeC() {
        return this.pckAccountTypeC;
    }
    
    public void setPckAccountTypeC(String pckAccountTypeC) {
        this.pckAccountTypeC = pckAccountTypeC;
    }

    
    @Column(name="lkp_base_reference__c", length=18)
    public String getLkpBaseReferenceC() {
        return this.lkpBaseReferenceC;
    }
    
    public void setLkpBaseReferenceC(String lkpBaseReferenceC) {
        this.lkpBaseReferenceC = lkpBaseReferenceC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin_calculo__c", length=13)
    public Date getFechaFinCalculoC() {
        return this.fechaFinCalculoC;
    }
    
    public void setFechaFinCalculoC(Date fechaFinCalculoC) {
        this.fechaFinCalculoC = fechaFinCalculoC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio_calculo__c", length=13)
    public Date getFechaInicioCalculoC() {
        return this.fechaInicioCalculoC;
    }
    
    public void setFechaInicioCalculoC(Date fechaInicioCalculoC) {
        this.fechaInicioCalculoC = fechaInicioCalculoC;
    }




}


