package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ObjetivoindiviscanalmarcaC generated by hbm2java
 */
@Entity
@Table(name="objetivoindiviscanalmarca__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class ObjetivoindiviscanalmarcaC  implements java.io.Serializable {


     private Integer id;
     private Double achievementC;
     private String channelC;
     private Date createddate;
     private String currencyisocode;
     private Date enddateC;
     private Double goalC;
     private String hcErr;
     private String hcLastop;
     private Boolean isdeleted;
     private String name;
     private String salesentityC;
     private String sfid;
     private Date startdateC;
     private String subbrandC;
     private Date systemmodstamp;
     private String usernameC;

    public ObjetivoindiviscanalmarcaC() {
    }

	
    public ObjetivoindiviscanalmarcaC(Integer id) {
        this.id = id;
    }
    public ObjetivoindiviscanalmarcaC(Integer id, Double achievementC, String channelC, Date createddate, String currencyisocode, Date enddateC, Double goalC, String hcErr, String hcLastop, Boolean isdeleted, String name, String salesentityC, String sfid, Date startdateC, String subbrandC, Date systemmodstamp, String usernameC) {
       this.id = id;
       this.achievementC = achievementC;
       this.channelC = channelC;
       this.createddate = createddate;
       this.currencyisocode = currencyisocode;
       this.enddateC = enddateC;
       this.goalC = goalC;
       this.hcErr = hcErr;
       this.hcLastop = hcLastop;
       this.isdeleted = isdeleted;
       this.name = name;
       this.salesentityC = salesentityC;
       this.sfid = sfid;
       this.startdateC = startdateC;
       this.subbrandC = subbrandC;
       this.systemmodstamp = systemmodstamp;
       this.usernameC = usernameC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="achievement__c", precision=17, scale=17)
    public Double getAchievementC() {
        return this.achievementC;
    }
    
    public void setAchievementC(Double achievementC) {
        this.achievementC = achievementC;
    }

    
    @Column(name="channel__c")
    public String getChannelC() {
        return this.channelC;
    }
    
    public void setChannelC(String channelC) {
        this.channelC = channelC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="currencyisocode", length=3)
    public String getCurrencyisocode() {
        return this.currencyisocode;
    }
    
    public void setCurrencyisocode(String currencyisocode) {
        this.currencyisocode = currencyisocode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="enddate__c", length=13)
    public Date getEnddateC() {
        return this.enddateC;
    }
    
    public void setEnddateC(Date enddateC) {
        this.enddateC = enddateC;
    }

    
    @Column(name="goal__c", precision=17, scale=17)
    public Double getGoalC() {
        return this.goalC;
    }
    
    public void setGoalC(Double goalC) {
        this.goalC = goalC;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="salesentity__c")
    public String getSalesentityC() {
        return this.salesentityC;
    }
    
    public void setSalesentityC(String salesentityC) {
        this.salesentityC = salesentityC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startdate__c", length=13)
    public Date getStartdateC() {
        return this.startdateC;
    }
    
    public void setStartdateC(Date startdateC) {
        this.startdateC = startdateC;
    }

    
    @Column(name="subbrand__c")
    public String getSubbrandC() {
        return this.subbrandC;
    }
    
    public void setSubbrandC(String subbrandC) {
        this.subbrandC = subbrandC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="username__c")
    public String getUsernameC() {
        return this.usernameC;
    }
    
    public void setUsernameC(String usernameC) {
        this.usernameC = usernameC;
    }




}


