package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Orderitem generated by hbm2java
 */
@Entity
@Table(name="orderitem"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Orderitem  implements java.io.Serializable {


     private Integer id;
     private Double totalprice;
     private Double unitprice;
     private Double curTotalCommercialDiscountC;
     private String orderid;
     private String orderitemnumber;
     private Double quantity;
     private Double numKgC;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private String frmPositionTypeC;
     private Double availablequantity;
     private Date createddate;
     private String pckUnitOfMeasureC;
     private Boolean chkPayableC;
     private String pricebookentryid;
     private String description;
     private String product2id;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public Orderitem() {
    }

	
    public Orderitem(Integer id) {
        this.id = id;
    }
    public Orderitem(Integer id, Double totalprice, Double unitprice, Double curTotalCommercialDiscountC, String orderid, String orderitemnumber, Double quantity, Double numKgC, Boolean isdeleted, Date systemmodstamp, String frmPositionTypeC, Double availablequantity, Date createddate, String pckUnitOfMeasureC, Boolean chkPayableC, String pricebookentryid, String description, String product2id, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.totalprice = totalprice;
       this.unitprice = unitprice;
       this.curTotalCommercialDiscountC = curTotalCommercialDiscountC;
       this.orderid = orderid;
       this.orderitemnumber = orderitemnumber;
       this.quantity = quantity;
       this.numKgC = numKgC;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.frmPositionTypeC = frmPositionTypeC;
       this.availablequantity = availablequantity;
       this.createddate = createddate;
       this.pckUnitOfMeasureC = pckUnitOfMeasureC;
       this.chkPayableC = chkPayableC;
       this.pricebookentryid = pricebookentryid;
       this.description = description;
       this.product2id = product2id;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="totalprice", precision=17, scale=17)
    public Double getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    
    @Column(name="unitprice", precision=17, scale=17)
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    
    @Column(name="cur_total_commercial_discount__c", precision=17, scale=17)
    public Double getCurTotalCommercialDiscountC() {
        return this.curTotalCommercialDiscountC;
    }
    
    public void setCurTotalCommercialDiscountC(Double curTotalCommercialDiscountC) {
        this.curTotalCommercialDiscountC = curTotalCommercialDiscountC;
    }

    
    @Column(name="orderid", length=18)
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    
    @Column(name="orderitemnumber", length=30)
    public String getOrderitemnumber() {
        return this.orderitemnumber;
    }
    
    public void setOrderitemnumber(String orderitemnumber) {
        this.orderitemnumber = orderitemnumber;
    }

    
    @Column(name="quantity", precision=17, scale=17)
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="num_kg__c", precision=17, scale=17)
    public Double getNumKgC() {
        return this.numKgC;
    }
    
    public void setNumKgC(Double numKgC) {
        this.numKgC = numKgC;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="frm_position_type__c", length=1300)
    public String getFrmPositionTypeC() {
        return this.frmPositionTypeC;
    }
    
    public void setFrmPositionTypeC(String frmPositionTypeC) {
        this.frmPositionTypeC = frmPositionTypeC;
    }

    
    @Column(name="availablequantity", precision=17, scale=17)
    public Double getAvailablequantity() {
        return this.availablequantity;
    }
    
    public void setAvailablequantity(Double availablequantity) {
        this.availablequantity = availablequantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="pck_unit_of_measure__c")
    public String getPckUnitOfMeasureC() {
        return this.pckUnitOfMeasureC;
    }
    
    public void setPckUnitOfMeasureC(String pckUnitOfMeasureC) {
        this.pckUnitOfMeasureC = pckUnitOfMeasureC;
    }

    
    @Column(name="chk_payable__c")
    public Boolean getChkPayableC() {
        return this.chkPayableC;
    }
    
    public void setChkPayableC(Boolean chkPayableC) {
        this.chkPayableC = chkPayableC;
    }

    
    @Column(name="pricebookentryid", length=18)
    public String getPricebookentryid() {
        return this.pricebookentryid;
    }
    
    public void setPricebookentryid(String pricebookentryid) {
        this.pricebookentryid = pricebookentryid;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="product2id", length=18)
    public String getProduct2id() {
        return this.product2id;
    }
    
    public void setProduct2id(String product2id) {
        this.product2id = product2id;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


