package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,schema="salesforce"
    , uniqueConstraints = {@UniqueConstraint(columnNames="heroku_external_id__c"), @UniqueConstraint(columnNames="sfid")} 
)
public class Order  implements java.io.Serializable {


     private Integer id;
     private Date dttPlannedDeliveryDateC;
     private String conditionTypeC;
     private String recordtypeid;
     private String txtCustomerorderidC;
     private String accountid;
     private Double numKgDeliveredC;
     private Double numKgPlannedC;
     private Boolean chkUrgentDeliveryC;
     private Double ruTotalUnitsC;
     private Boolean chkCollectionC;
     private String ownerid;
     private Boolean isdeleted;
     private Double ruTotalKgC;
     private Date systemmodstamp;
     private String status;
     private Double conditionTypeValueC;
     private String pckWarehouseCodeC;
     private String txtOrderToDoC;
     private Double numNumberOfProductsC;
     private Date effectivedate;
     private String orderCommentC;
     private String pckOriginC;
     private String pckOrderStatusSapC;
     private Date createddate;
     private String ordernumber;
     private String type;
     private String pricebook2id;
     private Double totalamount;
     private Double sumTotalCommercialDiscountC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String herokuExternalIdC;

     
    public Order() {
    }

	
    public Order(Integer id) {
        this.id = id;
    }
      public Order(Integer id, Date dttPlannedDeliveryDateC, String conditionTypeC, String recordtypeid, String txtCustomerorderidC, String accountid, Double numKgDeliveredC, Double numKgPlannedC, Boolean chkUrgentDeliveryC, Double ruTotalUnitsC, Boolean chkCollectionC, String ownerid, Boolean isdeleted, Double ruTotalKgC, Date systemmodstamp, String status, Double conditionTypeValueC, String pckWarehouseCodeC, String txtOrderToDoC, Double numNumberOfProductsC, Date effectivedate, String orderCommentC, String pckOriginC, String pckOrderStatusSapC, Date createddate, String ordernumber, String type, String pricebook2id, Double totalamount, Double sumTotalCommercialDiscountC, String sfid, String hcLastop, String hcErr, String herokuExternalIdC) {
       this.id = id;
       this.dttPlannedDeliveryDateC = dttPlannedDeliveryDateC;
       this.conditionTypeC = conditionTypeC;
       this.recordtypeid = recordtypeid;
       this.txtCustomerorderidC = txtCustomerorderidC;
       this.accountid = accountid;
       this.numKgDeliveredC = numKgDeliveredC;
       this.numKgPlannedC = numKgPlannedC;
       this.chkUrgentDeliveryC = chkUrgentDeliveryC;
       this.ruTotalUnitsC = ruTotalUnitsC;
       this.chkCollectionC = chkCollectionC;
       this.ownerid = ownerid;
       this.isdeleted = isdeleted;
       this.ruTotalKgC = ruTotalKgC;
       this.systemmodstamp = systemmodstamp;
       this.status = status;
       this.conditionTypeValueC = conditionTypeValueC;
       this.pckWarehouseCodeC = pckWarehouseCodeC;
       this.txtOrderToDoC = txtOrderToDoC;
       this.numNumberOfProductsC = numNumberOfProductsC;
       this.effectivedate = effectivedate;
       this.orderCommentC = orderCommentC;
       this.pckOriginC = pckOriginC;
       this.pckOrderStatusSapC = pckOrderStatusSapC;
       this.createddate = createddate;
       this.ordernumber = ordernumber;
       this.type = type;
       this.pricebook2id = pricebook2id;
       this.totalamount = totalamount;
       this.sumTotalCommercialDiscountC = sumTotalCommercialDiscountC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.herokuExternalIdC = herokuExternalIdC;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_planned_delivery_date__c", length=29)
    public Date getDttPlannedDeliveryDateC() {
        return this.dttPlannedDeliveryDateC;
    }
    
    public void setDttPlannedDeliveryDateC(Date dttPlannedDeliveryDateC) {
        this.dttPlannedDeliveryDateC = dttPlannedDeliveryDateC;
    }

    
    @Column(name="condition_type__c", length=50)
    public String getConditionTypeC() {
        return this.conditionTypeC;
    }
    
    public void setConditionTypeC(String conditionTypeC) {
        this.conditionTypeC = conditionTypeC;
    }

    
    @Column(name="recordtypeid", length=18)
    public String getRecordtypeid() {
        return this.recordtypeid;
    }
    
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }

    
    @Column(name="txt_customerorderid__c", length=20)
    public String getTxtCustomerorderidC() {
        return this.txtCustomerorderidC;
    }
    
    public void setTxtCustomerorderidC(String txtCustomerorderidC) {
        this.txtCustomerorderidC = txtCustomerorderidC;
    }

    
    @Column(name="accountid", length=18)
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    
    @Column(name="num_kg_delivered__c", precision=17, scale=17)
    public Double getNumKgDeliveredC() {
        return this.numKgDeliveredC;
    }
    
    public void setNumKgDeliveredC(Double numKgDeliveredC) {
        this.numKgDeliveredC = numKgDeliveredC;
    }

    
    @Column(name="num_kg_planned__c", precision=17, scale=17)
    public Double getNumKgPlannedC() {
        return this.numKgPlannedC;
    }
    
    public void setNumKgPlannedC(Double numKgPlannedC) {
        this.numKgPlannedC = numKgPlannedC;
    }

    
    @Column(name="chk_urgent_delivery__c")
    public Boolean getChkUrgentDeliveryC() {
        return this.chkUrgentDeliveryC;
    }
    
    public void setChkUrgentDeliveryC(Boolean chkUrgentDeliveryC) {
        this.chkUrgentDeliveryC = chkUrgentDeliveryC;
    }

    
    @Column(name="ru_total_units__c", precision=17, scale=17)
    public Double getRuTotalUnitsC() {
        return this.ruTotalUnitsC;
    }
    
    public void setRuTotalUnitsC(Double ruTotalUnitsC) {
        this.ruTotalUnitsC = ruTotalUnitsC;
    }

    
    @Column(name="chk_collection__c")
    public Boolean getChkCollectionC() {
        return this.chkCollectionC;
    }
    
    public void setChkCollectionC(Boolean chkCollectionC) {
        this.chkCollectionC = chkCollectionC;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="ru_total_kg__c", precision=17, scale=17)
    public Double getRuTotalKgC() {
        return this.ruTotalKgC;
    }
    
    public void setRuTotalKgC(Double ruTotalKgC) {
        this.ruTotalKgC = ruTotalKgC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="status", length=40)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="condition_type_value__c", precision=17, scale=17)
    public Double getConditionTypeValueC() {
        return this.conditionTypeValueC;
    }
    
    public void setConditionTypeValueC(Double conditionTypeValueC) {
        this.conditionTypeValueC = conditionTypeValueC;
    }

    
    @Column(name="pck_warehouse_code__c")
    public String getPckWarehouseCodeC() {
        return this.pckWarehouseCodeC;
    }
    
    public void setPckWarehouseCodeC(String pckWarehouseCodeC) {
        this.pckWarehouseCodeC = pckWarehouseCodeC;
    }

    
    @Column(name="txt_order_to_do__c")
    public String getTxtOrderToDoC() {
        return this.txtOrderToDoC;
    }
    
    public void setTxtOrderToDoC(String txtOrderToDoC) {
        this.txtOrderToDoC = txtOrderToDoC;
    }

    
    @Column(name="num_number_of_products__c", precision=17, scale=17)
    public Double getNumNumberOfProductsC() {
        return this.numNumberOfProductsC;
    }
    
    public void setNumNumberOfProductsC(Double numNumberOfProductsC) {
        this.numNumberOfProductsC = numNumberOfProductsC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="effectivedate", length=13)
    public Date getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(Date effectivedate) {
        this.effectivedate = effectivedate;
    }

    
    @Column(name="order_comment__c")
    public String getOrderCommentC() {
        return this.orderCommentC;
    }
    
    public void setOrderCommentC(String orderCommentC) {
        this.orderCommentC = orderCommentC;
    }

    
    @Column(name="pck_origin__c")
    public String getPckOriginC() {
        return this.pckOriginC;
    }
    
    public void setPckOriginC(String pckOriginC) {
        this.pckOriginC = pckOriginC;
    }

    
    @Column(name="pck_order_status_sap__c")
    public String getPckOrderStatusSapC() {
        return this.pckOrderStatusSapC;
    }
    
    public void setPckOrderStatusSapC(String pckOrderStatusSapC) {
        this.pckOrderStatusSapC = pckOrderStatusSapC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="ordernumber", length=30)
    public String getOrdernumber() {
        return this.ordernumber;
    }
    
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber;
    }

    
    @Column(name="type", length=40)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="pricebook2id", length=18)
    public String getPricebook2id() {
        return this.pricebook2id;
    }
    
    public void setPricebook2id(String pricebook2id) {
        this.pricebook2id = pricebook2id;
    }

    
    @Column(name="totalamount", precision=17, scale=17)
    public Double getTotalamount() {
        return this.totalamount;
    }
    
    public void setTotalamount(Double totalamount) {
        this.totalamount = totalamount;
    }

    
    @Column(name="sum_total_commercial_discount__c", precision=17, scale=17)
    public Double getSumTotalCommercialDiscountC() {
        return this.sumTotalCommercialDiscountC;
    }
    
    public void setSumTotalCommercialDiscountC(Double sumTotalCommercialDiscountC) {
        this.sumTotalCommercialDiscountC = sumTotalCommercialDiscountC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="heroku_external_id__c", unique=true)
    public String getHerokuExternalIdC() {
        return this.herokuExternalIdC;
    }
    
    public void setHerokuExternalIdC(String herokuExternalIdC) {
        this.herokuExternalIdC = herokuExternalIdC;
    }




}


