package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PesoClientes generated by hbm2java
 */
@Entity
@Table(name="peso_clientes"
    ,schema="salesforce"
)
public class PesoClientes  implements java.io.Serializable {


     private PesoClientesId id;

    public PesoClientes() {
    }

    public PesoClientes(PesoClientesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customer", column=@Column(name="customer", nullable=false) ), 
        @AttributeOverride(name="peso", column=@Column(name="peso", nullable=false) ), 
        @AttributeOverride(name="porcentage", column=@Column(name="porcentage", nullable=false, precision=17, scale=17) ), 
        @AttributeOverride(name="rdc", column=@Column(name="rdc", nullable=false) ), 
        @AttributeOverride(name="totalVentas", column=@Column(name="total_ventas", nullable=false, precision=17, scale=17) ) } )
    public PesoClientesId getId() {
        return this.id;
    }
    
    public void setId(PesoClientesId id) {
        this.id = id;
    }




}


