package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PesoClientesId generated by hbm2java
 */
@Embeddable
public class PesoClientesId  implements java.io.Serializable {


     private String customer;
     private Integer peso;
     private double porcentage;
     private String rdc;
     private double totalVentas;

    public PesoClientesId() {
    }

    public PesoClientesId(String customer, Integer peso, double porcentage, String rdc, double totalVentas) {
       this.customer = customer;
       this.peso = peso;
       this.porcentage = porcentage;
       this.rdc = rdc;
       this.totalVentas = totalVentas;
    }
   


    @Column(name="customer", nullable=false)
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }


    @Column(name="peso", nullable=false)
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }


    @Column(name="porcentage", nullable=false, precision=17, scale=17)
    public double getPorcentage() {
        return this.porcentage;
    }
    
    public void setPorcentage(double porcentage) {
        this.porcentage = porcentage;
    }


    @Column(name="rdc", nullable=false)
    public String getRdc() {
        return this.rdc;
    }
    
    public void setRdc(String rdc) {
        this.rdc = rdc;
    }


    @Column(name="total_ventas", nullable=false, precision=17, scale=17)
    public double getTotalVentas() {
        return this.totalVentas;
    }
    
    public void setTotalVentas(double totalVentas) {
        this.totalVentas = totalVentas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PesoClientesId) ) return false;
		 PesoClientesId castOther = ( PesoClientesId ) other; 
         
		 return ( (this.getCustomer()==castOther.getCustomer()) || ( this.getCustomer()!=null && castOther.getCustomer()!=null && this.getCustomer().equals(castOther.getCustomer()) ) )
 && ( (this.getPeso()==castOther.getPeso()) || ( this.getPeso()!=null && castOther.getPeso()!=null && this.getPeso().equals(castOther.getPeso()) ) )
 && (this.getPorcentage()==castOther.getPorcentage())
 && ( (this.getRdc()==castOther.getRdc()) || ( this.getRdc()!=null && castOther.getRdc()!=null && this.getRdc().equals(castOther.getRdc()) ) )
 && (this.getTotalVentas()==castOther.getTotalVentas());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomer() == null ? 0 : this.getCustomer().hashCode() );
         result = 37 * result + ( getPeso() == null ? 0 : this.getPeso().hashCode() );
         result = 37 * result + (int) this.getPorcentage();
         result = 37 * result + ( getRdc() == null ? 0 : this.getRdc().hashCode() );
         result = 37 * result + (int) this.getTotalVentas();
         return result;
   }   


}


