package com.minsait.affinity.jpa.model;
// Generated 30-mar-2020 20:13:03 by Hibernate Tools 5.0.6.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgaJobclass generated by hbm2java
 */
@Entity
@Table(name="pga_jobclass"
    ,schema="pgagent"
    , uniqueConstraints = @UniqueConstraint(columnNames="jclname") 
)
public class PgaJobclass  implements java.io.Serializable {


     private Integer jclid;
     private String jclname;
     private Set<PgaJob> pgaJobs = new HashSet<PgaJob>(0);

    public PgaJobclass() {
    }

	
    public PgaJobclass(Integer jclid, String jclname) {
        this.jclid = jclid;
        this.jclname = jclname;
    }
    public PgaJobclass(Integer jclid, String jclname, Set<PgaJob> pgaJobs) {
       this.jclid = jclid;
       this.jclname = jclname;
       this.pgaJobs = pgaJobs;
    }
   
     @Id 

    
    @Column(name="jclid", unique=true, nullable=false)
    public Integer getJclid() {
        return this.jclid;
    }
    
    public void setJclid(Integer jclid) {
        this.jclid = jclid;
    }

    
    @Column(name="jclname", unique=true, nullable=false)
    public String getJclname() {
        return this.jclname;
    }
    
    public void setJclname(String jclname) {
        this.jclname = jclname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pgaJobclass")
    public Set<PgaJob> getPgaJobs() {
        return this.pgaJobs;
    }
    
    public void setPgaJobs(Set<PgaJob> pgaJobs) {
        this.pgaJobs = pgaJobs;
    }




}


