package com.minsait.affinity.jpa.model;
// Generated 30-mar-2020 20:13:03 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgaJobstep generated by hbm2java
 */
@Entity
@Table(name="pga_jobstep"
    ,schema="pgagent"
)
public class PgaJobstep  implements java.io.Serializable {


     private Integer jstid;
     private PgaJob pgaJob;
     private String jstname;
     private String jstdesc;
     private boolean jstenabled;
     private char jstkind;
     private String jstcode;
     private String jstconnstr;
     private String jstdbname;
     private char jstonerror;
     private Date jscnextrun;
     private Set<PgaJobsteplog> pgaJobsteplogs = new HashSet<PgaJobsteplog>(0);

    public PgaJobstep() {
    }

	
    public PgaJobstep(Integer jstid, PgaJob pgaJob, String jstname, String jstdesc, boolean jstenabled, char jstkind, String jstcode, String jstconnstr, String jstdbname, char jstonerror) {
        this.jstid = jstid;
        this.pgaJob = pgaJob;
        this.jstname = jstname;
        this.jstdesc = jstdesc;
        this.jstenabled = jstenabled;
        this.jstkind = jstkind;
        this.jstcode = jstcode;
        this.jstconnstr = jstconnstr;
        this.jstdbname = jstdbname;
        this.jstonerror = jstonerror;
    }
    public PgaJobstep(Integer jstid, PgaJob pgaJob, String jstname, String jstdesc, boolean jstenabled, char jstkind, String jstcode, String jstconnstr, String jstdbname, char jstonerror, Date jscnextrun, Set<PgaJobsteplog> pgaJobsteplogs) {
       this.jstid = jstid;
       this.pgaJob = pgaJob;
       this.jstname = jstname;
       this.jstdesc = jstdesc;
       this.jstenabled = jstenabled;
       this.jstkind = jstkind;
       this.jstcode = jstcode;
       this.jstconnstr = jstconnstr;
       this.jstdbname = jstdbname;
       this.jstonerror = jstonerror;
       this.jscnextrun = jscnextrun;
       this.pgaJobsteplogs = pgaJobsteplogs;
    }
   
     @Id 

    
    @Column(name="jstid", unique=true, nullable=false)
    public Integer getJstid() {
        return this.jstid;
    }
    
    public void setJstid(Integer jstid) {
        this.jstid = jstid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jstjobid", nullable=false)
    public PgaJob getPgaJob() {
        return this.pgaJob;
    }
    
    public void setPgaJob(PgaJob pgaJob) {
        this.pgaJob = pgaJob;
    }

    
    @Column(name="jstname", nullable=false)
    public String getJstname() {
        return this.jstname;
    }
    
    public void setJstname(String jstname) {
        this.jstname = jstname;
    }

    
    @Column(name="jstdesc", nullable=false)
    public String getJstdesc() {
        return this.jstdesc;
    }
    
    public void setJstdesc(String jstdesc) {
        this.jstdesc = jstdesc;
    }

    
    @Column(name="jstenabled", nullable=false)
    public boolean isJstenabled() {
        return this.jstenabled;
    }
    
    public void setJstenabled(boolean jstenabled) {
        this.jstenabled = jstenabled;
    }

    
    @Column(name="jstkind", nullable=false, length=1)
    public char getJstkind() {
        return this.jstkind;
    }
    
    public void setJstkind(char jstkind) {
        this.jstkind = jstkind;
    }

    
    @Column(name="jstcode", nullable=false)
    public String getJstcode() {
        return this.jstcode;
    }
    
    public void setJstcode(String jstcode) {
        this.jstcode = jstcode;
    }

    
    @Column(name="jstconnstr", nullable=false)
    public String getJstconnstr() {
        return this.jstconnstr;
    }
    
    public void setJstconnstr(String jstconnstr) {
        this.jstconnstr = jstconnstr;
    }

    
    @Column(name="jstdbname", nullable=false)
    public String getJstdbname() {
        return this.jstdbname;
    }
    
    public void setJstdbname(String jstdbname) {
        this.jstdbname = jstdbname;
    }

    
    @Column(name="jstonerror", nullable=false, length=1)
    public char getJstonerror() {
        return this.jstonerror;
    }
    
    public void setJstonerror(char jstonerror) {
        this.jstonerror = jstonerror;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jscnextrun", length=35)
    public Date getJscnextrun() {
        return this.jscnextrun;
    }
    
    public void setJscnextrun(Date jscnextrun) {
        this.jscnextrun = jscnextrun;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pgaJobstep")
    public Set<PgaJobsteplog> getPgaJobsteplogs() {
        return this.pgaJobsteplogs;
    }
    
    public void setPgaJobsteplogs(Set<PgaJobsteplog> pgaJobsteplogs) {
        this.pgaJobsteplogs = pgaJobsteplogs;
    }




}


