package com.minsait.affinity.jpa.model;
// Generated 30-mar-2020 20:13:03 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgaJobagent generated by hbm2java
 */
@Entity
@Table(name="pga_jobagent"
    ,schema="pgagent"
)
public class PgaJobagent  implements java.io.Serializable {


     private Integer jagpid;
     private Date jaglogintime;
     private String jagstation;
     private Set<PgaJob> pgaJobs = new HashSet<PgaJob>(0);

    public PgaJobagent() {
    }

	
    public PgaJobagent(Integer jagpid, Date jaglogintime, String jagstation) {
        this.jagpid = jagpid;
        this.jaglogintime = jaglogintime;
        this.jagstation = jagstation;
    }
    public PgaJobagent(Integer jagpid, Date jaglogintime, String jagstation, Set<PgaJob> pgaJobs) {
       this.jagpid = jagpid;
       this.jaglogintime = jaglogintime;
       this.jagstation = jagstation;
       this.pgaJobs = pgaJobs;
    }
   
     @Id 

    
    @Column(name="jagpid", unique=true, nullable=false)
    public Integer getJagpid() {
        return this.jagpid;
    }
    
    public void setJagpid(Integer jagpid) {
        this.jagpid = jagpid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jaglogintime", nullable=false, length=35)
    public Date getJaglogintime() {
        return this.jaglogintime;
    }
    
    public void setJaglogintime(Date jaglogintime) {
        this.jaglogintime = jaglogintime;
    }

    
    @Column(name="jagstation", nullable=false)
    public String getJagstation() {
        return this.jagstation;
    }
    
    public void setJagstation(String jagstation) {
        this.jagstation = jagstation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pgaJobagent")
    public Set<PgaJob> getPgaJobs() {
        return this.pgaJobs;
    }
    
    public void setPgaJobs(Set<PgaJob> pgaJobs) {
        this.pgaJobs = pgaJobs;
    }




}


