package com.minsait.affinity.jpa.model;
// Generated 30-mar-2020 20:13:03 by Hibernate Tools 5.0.6.Final


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgaJobsteplog generated by hbm2java
 */
@Entity
@Table(name="pga_jobsteplog"
    ,schema="pgagent"
)
public class PgaJobsteplog  implements java.io.Serializable {


     private Integer jslid;
     private PgaJoblog pgaJoblog;
     private PgaJobstep pgaJobstep;
     private char jslstatus;
     private Integer jslresult;
     private Date jslstart;
     private Serializable jslduration;
     private String jsloutput;

    public PgaJobsteplog() {
    }

	
    public PgaJobsteplog(Integer jslid, PgaJoblog pgaJoblog, PgaJobstep pgaJobstep, char jslstatus, Date jslstart) {
        this.jslid = jslid;
        this.pgaJoblog = pgaJoblog;
        this.pgaJobstep = pgaJobstep;
        this.jslstatus = jslstatus;
        this.jslstart = jslstart;
    }
    public PgaJobsteplog(Integer jslid, PgaJoblog pgaJoblog, PgaJobstep pgaJobstep, char jslstatus, Integer jslresult, Date jslstart, Serializable jslduration, String jsloutput) {
       this.jslid = jslid;
       this.pgaJoblog = pgaJoblog;
       this.pgaJobstep = pgaJobstep;
       this.jslstatus = jslstatus;
       this.jslresult = jslresult;
       this.jslstart = jslstart;
       this.jslduration = jslduration;
       this.jsloutput = jsloutput;
    }
   
     @Id 

    
    @Column(name="jslid", unique=true, nullable=false)
    public Integer getJslid() {
        return this.jslid;
    }
    
    public void setJslid(Integer jslid) {
        this.jslid = jslid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jsljlgid", nullable=false)
    public PgaJoblog getPgaJoblog() {
        return this.pgaJoblog;
    }
    
    public void setPgaJoblog(PgaJoblog pgaJoblog) {
        this.pgaJoblog = pgaJoblog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jsljstid", nullable=false)
    public PgaJobstep getPgaJobstep() {
        return this.pgaJobstep;
    }
    
    public void setPgaJobstep(PgaJobstep pgaJobstep) {
        this.pgaJobstep = pgaJobstep;
    }

    
    @Column(name="jslstatus", nullable=false, length=1)
    public char getJslstatus() {
        return this.jslstatus;
    }
    
    public void setJslstatus(char jslstatus) {
        this.jslstatus = jslstatus;
    }

    
    @Column(name="jslresult")
    public Integer getJslresult() {
        return this.jslresult;
    }
    
    public void setJslresult(Integer jslresult) {
        this.jslresult = jslresult;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jslstart", nullable=false, length=35)
    public Date getJslstart() {
        return this.jslstart;
    }
    
    public void setJslstart(Date jslstart) {
        this.jslstart = jslstart;
    }

    
    @Column(name="jslduration")
    public Serializable getJslduration() {
        return this.jslduration;
    }
    
    public void setJslduration(Serializable jslduration) {
        this.jslduration = jslduration;
    }

    
    @Column(name="jsloutput")
    public String getJsloutput() {
        return this.jsloutput;
    }
    
    public void setJsloutput(String jsloutput) {
        this.jsloutput = jsloutput;
    }




}


