package com.minsait.affinity.jpa.model;
// Generated 30-mar-2020 20:13:03 by Hibernate Tools 5.0.6.Final


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgaSchedule generated by hbm2java
 */
@Entity
@Table(name="pga_schedule"
    ,schema="pgagent"
)
public class PgaSchedule  implements java.io.Serializable {


     private Integer jscid;
     private PgaJob pgaJob;
     private String jscname;
     private String jscdesc;
     private boolean jscenabled;
     private Date jscstart;
     private Date jscend;
     private Serializable jscminutes;
     private Serializable jschours;
     private Serializable jscweekdays;
     private Serializable jscmonthdays;
     private Serializable jscmonths;
     private Set<PgaException> pgaExceptions = new HashSet<PgaException>(0);

    public PgaSchedule() {
    }

	
    public PgaSchedule(Integer jscid, PgaJob pgaJob, String jscname, String jscdesc, boolean jscenabled, Date jscstart, Serializable jscminutes, Serializable jschours, Serializable jscweekdays, Serializable jscmonthdays, Serializable jscmonths) {
        this.jscid = jscid;
        this.pgaJob = pgaJob;
        this.jscname = jscname;
        this.jscdesc = jscdesc;
        this.jscenabled = jscenabled;
        this.jscstart = jscstart;
        this.jscminutes = jscminutes;
        this.jschours = jschours;
        this.jscweekdays = jscweekdays;
        this.jscmonthdays = jscmonthdays;
        this.jscmonths = jscmonths;
    }
    public PgaSchedule(Integer jscid, PgaJob pgaJob, String jscname, String jscdesc, boolean jscenabled, Date jscstart, Date jscend, Serializable jscminutes, Serializable jschours, Serializable jscweekdays, Serializable jscmonthdays, Serializable jscmonths, Set<PgaException> pgaExceptions) {
       this.jscid = jscid;
       this.pgaJob = pgaJob;
       this.jscname = jscname;
       this.jscdesc = jscdesc;
       this.jscenabled = jscenabled;
       this.jscstart = jscstart;
       this.jscend = jscend;
       this.jscminutes = jscminutes;
       this.jschours = jschours;
       this.jscweekdays = jscweekdays;
       this.jscmonthdays = jscmonthdays;
       this.jscmonths = jscmonths;
       this.pgaExceptions = pgaExceptions;
    }
   
     @Id 

    
    @Column(name="jscid", unique=true, nullable=false)
    public Integer getJscid() {
        return this.jscid;
    }
    
    public void setJscid(Integer jscid) {
        this.jscid = jscid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jscjobid", nullable=false)
    public PgaJob getPgaJob() {
        return this.pgaJob;
    }
    
    public void setPgaJob(PgaJob pgaJob) {
        this.pgaJob = pgaJob;
    }

    
    @Column(name="jscname", nullable=false)
    public String getJscname() {
        return this.jscname;
    }
    
    public void setJscname(String jscname) {
        this.jscname = jscname;
    }

    
    @Column(name="jscdesc", nullable=false)
    public String getJscdesc() {
        return this.jscdesc;
    }
    
    public void setJscdesc(String jscdesc) {
        this.jscdesc = jscdesc;
    }

    
    @Column(name="jscenabled", nullable=false)
    public boolean isJscenabled() {
        return this.jscenabled;
    }
    
    public void setJscenabled(boolean jscenabled) {
        this.jscenabled = jscenabled;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jscstart", nullable=false, length=35)
    public Date getJscstart() {
        return this.jscstart;
    }
    
    public void setJscstart(Date jscstart) {
        this.jscstart = jscstart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jscend", length=35)
    public Date getJscend() {
        return this.jscend;
    }
    
    public void setJscend(Date jscend) {
        this.jscend = jscend;
    }

    
    @Column(name="jscminutes", nullable=false)
    public Serializable getJscminutes() {
        return this.jscminutes;
    }
    
    public void setJscminutes(Serializable jscminutes) {
        this.jscminutes = jscminutes;
    }

    
    @Column(name="jschours", nullable=false)
    public Serializable getJschours() {
        return this.jschours;
    }
    
    public void setJschours(Serializable jschours) {
        this.jschours = jschours;
    }

    
    @Column(name="jscweekdays", nullable=false)
    public Serializable getJscweekdays() {
        return this.jscweekdays;
    }
    
    public void setJscweekdays(Serializable jscweekdays) {
        this.jscweekdays = jscweekdays;
    }

    
    @Column(name="jscmonthdays", nullable=false)
    public Serializable getJscmonthdays() {
        return this.jscmonthdays;
    }
    
    public void setJscmonthdays(Serializable jscmonthdays) {
        this.jscmonthdays = jscmonthdays;
    }

    
    @Column(name="jscmonths", nullable=false)
    public Serializable getJscmonths() {
        return this.jscmonths;
    }
    
    public void setJscmonths(Serializable jscmonths) {
        this.jscmonths = jscmonths;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pgaSchedule")
    public Set<PgaException> getPgaExceptions() {
        return this.pgaExceptions;
    }
    
    public void setPgaExceptions(Set<PgaException> pgaExceptions) {
        this.pgaExceptions = pgaExceptions;
    }




}


