package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pricebook2 generated by hbm2java
 */
@Entity
@Table(name="pricebook2"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Pricebook2  implements java.io.Serializable {


     private Integer id;
     private Date createddate;
     private Boolean isdeleted;
     private String name;
     private Date systemmodstamp;
     private Boolean isactive;
     private Boolean isarchived;
     private Boolean isstandard;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String pckSalesEntityC;
     private String pckChannelC;

    public Pricebook2() {
    }

	
    public Pricebook2(Integer id) {
        this.id = id;
    }
    public Pricebook2(Integer id, Date createddate, Boolean isdeleted, String name, Date systemmodstamp, Boolean isactive, Boolean isarchived, Boolean isstandard, String sfid, String hcLastop, String hcErr, String pckSalesEntityC, String pckChannelC) {
       this.id = id;
       this.createddate = createddate;
       this.isdeleted = isdeleted;
       this.name = name;
       this.systemmodstamp = systemmodstamp;
       this.isactive = isactive;
       this.isarchived = isarchived;
       this.isstandard = isstandard;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.pckSalesEntityC = pckSalesEntityC;
       this.pckChannelC = pckChannelC;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="isarchived")
    public Boolean getIsarchived() {
        return this.isarchived;
    }
    
    public void setIsarchived(Boolean isarchived) {
        this.isarchived = isarchived;
    }

    
    @Column(name="isstandard")
    public Boolean getIsstandard() {
        return this.isstandard;
    }
    
    public void setIsstandard(Boolean isstandard) {
        this.isstandard = isstandard;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="pck_sales_entity__c")
    public String getPckSalesEntityC() {
        return this.pckSalesEntityC;
    }
    
    public void setPckSalesEntityC(String pckSalesEntityC) {
        this.pckSalesEntityC = pckSalesEntityC;
    }

    
    @Column(name="pck_channel__c")
    public String getPckChannelC() {
        return this.pckChannelC;
    }
    
    public void setPckChannelC(String pckChannelC) {
        this.pckChannelC = pckChannelC;
    }




}


