package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Product2 generated by hbm2java
 */
@Entity
@Table(name="product2"
    ,schema="salesforce"
    , uniqueConstraints = {@UniqueConstraint(columnNames="sfid"), @UniqueConstraint(columnNames="txt_item__c")} 
)
public class Product2  implements java.io.Serializable {


     private Integer id;
     private String frmBrandCodeC;
     private String txtItemC;
     private Double numUnitsBoxC;
     private String frmVarietyCodeC;
     private String pckVarietyC;
     private String frmlHierarchyC;
     private String pckPetTypeC;
     private Double frmLineOrderC;
     private String pckBrandC;
     private String txtSalesArgumentC;
     private String pckItemTypeC;
     private String txtOrderC;
     private String frmRangeC;
     private String frmBusinessC;
     private String baseReferenceC;
     private String frmBaseReferenceC;
     private String frmSubrangeC;
     private String pckLineC;
     private Double numEuroTonC;
     private String frmLineCodeC;
     private String name;
     private String frmHierarchyC;
     private String frmSegmentCodeC;
     private String pckRangeC;
     private String frmSegmentC;
     private Double frmSubbrandOrderC;
     private Boolean isdeleted;
     private String pckItemClassC;
     private Date systemmodstamp;
     private String frmLineC;
     private Double numWeightC;
     private String frmBaseReferenceCodeC;
     private String frmlOrderRankC;
     private String frmSubrangeCodeC;
     private String pckSubbrandC;
     private String frmBusinessCodeC;
     private Date createddate;
     private String frmRangeCodeC;
     private String pckSegmentC;
     private String frmVarietyC;
     private String frmBrandC;
     private String productcode;
     private String pckBusinessC;
     private String frmSubbrandCodeC;
     private String frmSubbrandC;
     private Double numBoxesXPaletC;
     private String pckSubrangeC;
     private Double numLWeightC;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public Product2() {
    }

	
    public Product2(Integer id) {
        this.id = id;
    }
    public Product2(Integer id, String frmBrandCodeC, String txtItemC, Double numUnitsBoxC, String frmVarietyCodeC, String pckVarietyC, String frmlHierarchyC, String pckPetTypeC, Double frmLineOrderC, String pckBrandC, String txtSalesArgumentC, String pckItemTypeC, String txtOrderC, String frmRangeC, String frmBusinessC, String baseReferenceC, String frmBaseReferenceC, String frmSubrangeC, String pckLineC, Double numEuroTonC, String frmLineCodeC, String name, String frmHierarchyC, String frmSegmentCodeC, String pckRangeC, String frmSegmentC, Double frmSubbrandOrderC, Boolean isdeleted, String pckItemClassC, Date systemmodstamp, String frmLineC, Double numWeightC, String frmBaseReferenceCodeC, String frmlOrderRankC, String frmSubrangeCodeC, String pckSubbrandC, String frmBusinessCodeC, Date createddate, String frmRangeCodeC, String pckSegmentC, String frmVarietyC, String frmBrandC, String productcode, String pckBusinessC, String frmSubbrandCodeC, String frmSubbrandC, Double numBoxesXPaletC, String pckSubrangeC, Double numLWeightC, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.frmBrandCodeC = frmBrandCodeC;
       this.txtItemC = txtItemC;
       this.numUnitsBoxC = numUnitsBoxC;
       this.frmVarietyCodeC = frmVarietyCodeC;
       this.pckVarietyC = pckVarietyC;
       this.frmlHierarchyC = frmlHierarchyC;
       this.pckPetTypeC = pckPetTypeC;
       this.frmLineOrderC = frmLineOrderC;
       this.pckBrandC = pckBrandC;
       this.txtSalesArgumentC = txtSalesArgumentC;
       this.pckItemTypeC = pckItemTypeC;
       this.txtOrderC = txtOrderC;
       this.frmRangeC = frmRangeC;
       this.frmBusinessC = frmBusinessC;
       this.baseReferenceC = baseReferenceC;
       this.frmBaseReferenceC = frmBaseReferenceC;
       this.frmSubrangeC = frmSubrangeC;
       this.pckLineC = pckLineC;
       this.numEuroTonC = numEuroTonC;
       this.frmLineCodeC = frmLineCodeC;
       this.name = name;
       this.frmHierarchyC = frmHierarchyC;
       this.frmSegmentCodeC = frmSegmentCodeC;
       this.pckRangeC = pckRangeC;
       this.frmSegmentC = frmSegmentC;
       this.frmSubbrandOrderC = frmSubbrandOrderC;
       this.isdeleted = isdeleted;
       this.pckItemClassC = pckItemClassC;
       this.systemmodstamp = systemmodstamp;
       this.frmLineC = frmLineC;
       this.numWeightC = numWeightC;
       this.frmBaseReferenceCodeC = frmBaseReferenceCodeC;
       this.frmlOrderRankC = frmlOrderRankC;
       this.frmSubrangeCodeC = frmSubrangeCodeC;
       this.pckSubbrandC = pckSubbrandC;
       this.frmBusinessCodeC = frmBusinessCodeC;
       this.createddate = createddate;
       this.frmRangeCodeC = frmRangeCodeC;
       this.pckSegmentC = pckSegmentC;
       this.frmVarietyC = frmVarietyC;
       this.frmBrandC = frmBrandC;
       this.productcode = productcode;
       this.pckBusinessC = pckBusinessC;
       this.frmSubbrandCodeC = frmSubbrandCodeC;
       this.frmSubbrandC = frmSubbrandC;
       this.numBoxesXPaletC = numBoxesXPaletC;
       this.pckSubrangeC = pckSubrangeC;
       this.numLWeightC = numLWeightC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="frm_brand_code__c", length=1300)
    public String getFrmBrandCodeC() {
        return this.frmBrandCodeC;
    }
    
    public void setFrmBrandCodeC(String frmBrandCodeC) {
        this.frmBrandCodeC = frmBrandCodeC;
    }

    
    @Column(name="txt_item__c", unique=true, length=18)
    public String getTxtItemC() {
        return this.txtItemC;
    }
    
    public void setTxtItemC(String txtItemC) {
        this.txtItemC = txtItemC;
    }

    
    @Column(name="num_units_box__c", precision=17, scale=17)
    public Double getNumUnitsBoxC() {
        return this.numUnitsBoxC;
    }
    
    public void setNumUnitsBoxC(Double numUnitsBoxC) {
        this.numUnitsBoxC = numUnitsBoxC;
    }

    
    @Column(name="frm_variety_code__c", length=1300)
    public String getFrmVarietyCodeC() {
        return this.frmVarietyCodeC;
    }
    
    public void setFrmVarietyCodeC(String frmVarietyCodeC) {
        this.frmVarietyCodeC = frmVarietyCodeC;
    }

    
    @Column(name="pck_variety__c")
    public String getPckVarietyC() {
        return this.pckVarietyC;
    }
    
    public void setPckVarietyC(String pckVarietyC) {
        this.pckVarietyC = pckVarietyC;
    }

    
    @Column(name="frml_hierarchy__c", length=1300)
    public String getFrmlHierarchyC() {
        return this.frmlHierarchyC;
    }
    
    public void setFrmlHierarchyC(String frmlHierarchyC) {
        this.frmlHierarchyC = frmlHierarchyC;
    }

    
    @Column(name="pck_pet_type__c")
    public String getPckPetTypeC() {
        return this.pckPetTypeC;
    }
    
    public void setPckPetTypeC(String pckPetTypeC) {
        this.pckPetTypeC = pckPetTypeC;
    }

    
    @Column(name="frm_line_order__c", precision=17, scale=17)
    public Double getFrmLineOrderC() {
        return this.frmLineOrderC;
    }
    
    public void setFrmLineOrderC(Double frmLineOrderC) {
        this.frmLineOrderC = frmLineOrderC;
    }

    
    @Column(name="pck_brand__c")
    public String getPckBrandC() {
        return this.pckBrandC;
    }
    
    public void setPckBrandC(String pckBrandC) {
        this.pckBrandC = pckBrandC;
    }

    
    @Column(name="txt_sales_argument__c")
    public String getTxtSalesArgumentC() {
        return this.txtSalesArgumentC;
    }
    
    public void setTxtSalesArgumentC(String txtSalesArgumentC) {
        this.txtSalesArgumentC = txtSalesArgumentC;
    }

    
    @Column(name="pck_item_type__c")
    public String getPckItemTypeC() {
        return this.pckItemTypeC;
    }
    
    public void setPckItemTypeC(String pckItemTypeC) {
        this.pckItemTypeC = pckItemTypeC;
    }

    
    @Column(name="txt_order__c", length=20)
    public String getTxtOrderC() {
        return this.txtOrderC;
    }
    
    public void setTxtOrderC(String txtOrderC) {
        this.txtOrderC = txtOrderC;
    }

    
    @Column(name="frm_range__c", length=1300)
    public String getFrmRangeC() {
        return this.frmRangeC;
    }
    
    public void setFrmRangeC(String frmRangeC) {
        this.frmRangeC = frmRangeC;
    }

    
    @Column(name="frm_business__c", length=1300)
    public String getFrmBusinessC() {
        return this.frmBusinessC;
    }
    
    public void setFrmBusinessC(String frmBusinessC) {
        this.frmBusinessC = frmBusinessC;
    }

    
    @Column(name="base_reference__c", length=18)
    public String getBaseReferenceC() {
        return this.baseReferenceC;
    }
    
    public void setBaseReferenceC(String baseReferenceC) {
        this.baseReferenceC = baseReferenceC;
    }

    
    @Column(name="frm_base_reference__c", length=1300)
    public String getFrmBaseReferenceC() {
        return this.frmBaseReferenceC;
    }
    
    public void setFrmBaseReferenceC(String frmBaseReferenceC) {
        this.frmBaseReferenceC = frmBaseReferenceC;
    }

    
    @Column(name="frm_subrange__c", length=1300)
    public String getFrmSubrangeC() {
        return this.frmSubrangeC;
    }
    
    public void setFrmSubrangeC(String frmSubrangeC) {
        this.frmSubrangeC = frmSubrangeC;
    }

    
    @Column(name="pck_line__c")
    public String getPckLineC() {
        return this.pckLineC;
    }
    
    public void setPckLineC(String pckLineC) {
        this.pckLineC = pckLineC;
    }

    
    @Column(name="num_euro_ton__c", precision=17, scale=17)
    public Double getNumEuroTonC() {
        return this.numEuroTonC;
    }
    
    public void setNumEuroTonC(Double numEuroTonC) {
        this.numEuroTonC = numEuroTonC;
    }

    
    @Column(name="frm_line_code__c", length=1300)
    public String getFrmLineCodeC() {
        return this.frmLineCodeC;
    }
    
    public void setFrmLineCodeC(String frmLineCodeC) {
        this.frmLineCodeC = frmLineCodeC;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="frm_hierarchy__c", length=1300)
    public String getFrmHierarchyC() {
        return this.frmHierarchyC;
    }
    
    public void setFrmHierarchyC(String frmHierarchyC) {
        this.frmHierarchyC = frmHierarchyC;
    }

    
    @Column(name="frm_segment_code__c", length=1300)
    public String getFrmSegmentCodeC() {
        return this.frmSegmentCodeC;
    }
    
    public void setFrmSegmentCodeC(String frmSegmentCodeC) {
        this.frmSegmentCodeC = frmSegmentCodeC;
    }

    
    @Column(name="pck_range__c")
    public String getPckRangeC() {
        return this.pckRangeC;
    }
    
    public void setPckRangeC(String pckRangeC) {
        this.pckRangeC = pckRangeC;
    }

    
    @Column(name="frm_segment__c", length=1300)
    public String getFrmSegmentC() {
        return this.frmSegmentC;
    }
    
    public void setFrmSegmentC(String frmSegmentC) {
        this.frmSegmentC = frmSegmentC;
    }

    
    @Column(name="frm_subbrand_order__c", precision=17, scale=17)
    public Double getFrmSubbrandOrderC() {
        return this.frmSubbrandOrderC;
    }
    
    public void setFrmSubbrandOrderC(Double frmSubbrandOrderC) {
        this.frmSubbrandOrderC = frmSubbrandOrderC;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="pck_item_class__c")
    public String getPckItemClassC() {
        return this.pckItemClassC;
    }
    
    public void setPckItemClassC(String pckItemClassC) {
        this.pckItemClassC = pckItemClassC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="frm_line__c", length=1300)
    public String getFrmLineC() {
        return this.frmLineC;
    }
    
    public void setFrmLineC(String frmLineC) {
        this.frmLineC = frmLineC;
    }

    
    @Column(name="num_weight__c", precision=17, scale=17)
    public Double getNumWeightC() {
        return this.numWeightC;
    }
    
    public void setNumWeightC(Double numWeightC) {
        this.numWeightC = numWeightC;
    }

    
    @Column(name="frm_base_reference_code__c", length=1300)
    public String getFrmBaseReferenceCodeC() {
        return this.frmBaseReferenceCodeC;
    }
    
    public void setFrmBaseReferenceCodeC(String frmBaseReferenceCodeC) {
        this.frmBaseReferenceCodeC = frmBaseReferenceCodeC;
    }

    
    @Column(name="frml_order_rank__c", length=1300)
    public String getFrmlOrderRankC() {
        return this.frmlOrderRankC;
    }
    
    public void setFrmlOrderRankC(String frmlOrderRankC) {
        this.frmlOrderRankC = frmlOrderRankC;
    }

    
    @Column(name="frm_subrange_code__c", length=1300)
    public String getFrmSubrangeCodeC() {
        return this.frmSubrangeCodeC;
    }
    
    public void setFrmSubrangeCodeC(String frmSubrangeCodeC) {
        this.frmSubrangeCodeC = frmSubrangeCodeC;
    }

    
    @Column(name="pck_subbrand__c")
    public String getPckSubbrandC() {
        return this.pckSubbrandC;
    }
    
    public void setPckSubbrandC(String pckSubbrandC) {
        this.pckSubbrandC = pckSubbrandC;
    }

    
    @Column(name="frm_business_code__c", length=1300)
    public String getFrmBusinessCodeC() {
        return this.frmBusinessCodeC;
    }
    
    public void setFrmBusinessCodeC(String frmBusinessCodeC) {
        this.frmBusinessCodeC = frmBusinessCodeC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="frm_range_code__c", length=1300)
    public String getFrmRangeCodeC() {
        return this.frmRangeCodeC;
    }
    
    public void setFrmRangeCodeC(String frmRangeCodeC) {
        this.frmRangeCodeC = frmRangeCodeC;
    }

    
    @Column(name="pck_segment__c")
    public String getPckSegmentC() {
        return this.pckSegmentC;
    }
    
    public void setPckSegmentC(String pckSegmentC) {
        this.pckSegmentC = pckSegmentC;
    }

    
    @Column(name="frm_variety__c", length=1300)
    public String getFrmVarietyC() {
        return this.frmVarietyC;
    }
    
    public void setFrmVarietyC(String frmVarietyC) {
        this.frmVarietyC = frmVarietyC;
    }

    
    @Column(name="frm_brand__c", length=1300)
    public String getFrmBrandC() {
        return this.frmBrandC;
    }
    
    public void setFrmBrandC(String frmBrandC) {
        this.frmBrandC = frmBrandC;
    }

    
    @Column(name="productcode")
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    
    @Column(name="pck_business__c")
    public String getPckBusinessC() {
        return this.pckBusinessC;
    }
    
    public void setPckBusinessC(String pckBusinessC) {
        this.pckBusinessC = pckBusinessC;
    }

    
    @Column(name="frm_subbrand_code__c", length=1300)
    public String getFrmSubbrandCodeC() {
        return this.frmSubbrandCodeC;
    }
    
    public void setFrmSubbrandCodeC(String frmSubbrandCodeC) {
        this.frmSubbrandCodeC = frmSubbrandCodeC;
    }

    
    @Column(name="frm_subbrand__c", length=1300)
    public String getFrmSubbrandC() {
        return this.frmSubbrandC;
    }
    
    public void setFrmSubbrandC(String frmSubbrandC) {
        this.frmSubbrandC = frmSubbrandC;
    }

    
    @Column(name="num_boxes_x_palet__c", precision=17, scale=17)
    public Double getNumBoxesXPaletC() {
        return this.numBoxesXPaletC;
    }
    
    public void setNumBoxesXPaletC(Double numBoxesXPaletC) {
        this.numBoxesXPaletC = numBoxesXPaletC;
    }

    
    @Column(name="pck_subrange__c")
    public String getPckSubrangeC() {
        return this.pckSubrangeC;
    }
    
    public void setPckSubrangeC(String pckSubrangeC) {
        this.pckSubrangeC = pckSubrangeC;
    }

    
    @Column(name="num_l_weight__c", precision=17, scale=17)
    public Double getNumLWeightC() {
        return this.numLWeightC;
    }
    
    public void setNumLWeightC(Double numLWeightC) {
        this.numLWeightC = numLWeightC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


