package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PromVentasRdcActivasId generated by hbm2java
 */
@Embeddable
public class PromVentasRdcActivasId  implements java.io.Serializable {


     private String baseReference;
     private Double promSales;
     private Double promSalesKg;
     private String cadena;
     private String accType;
     private String rdc;
     private Boolean status;

    public PromVentasRdcActivasId() {
    }

    public PromVentasRdcActivasId(String baseReference, Double promSales, Double promSalesKg, String cadena, String accType, String rdc, Boolean status) {
       this.baseReference = baseReference;
       this.promSales = promSales;
       this.promSalesKg = promSalesKg;
       this.cadena = cadena;
       this.accType = accType;
       this.rdc = rdc;
       this.status = status;
    }
   


    @Column(name="base_reference")
    public String getBaseReference() {
        return this.baseReference;
    }
    
    public void setBaseReference(String baseReference) {
        this.baseReference = baseReference;
    }


    @Column(name="prom_sales", precision=17, scale=17)
    public Double getPromSales() {
        return this.promSales;
    }
    
    public void setPromSales(Double promSales) {
        this.promSales = promSales;
    }


    @Column(name="prom_sales_kg", precision=17, scale=17)
    public Double getPromSalesKg() {
        return this.promSalesKg;
    }
    
    public void setPromSalesKg(Double promSalesKg) {
        this.promSalesKg = promSalesKg;
    }


    @Column(name="cadena")
    public String getCadena() {
        return this.cadena;
    }
    
    public void setCadena(String cadena) {
        this.cadena = cadena;
    }


    @Column(name="acc_type")
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }


    @Column(name="rdc")
    public String getRdc() {
        return this.rdc;
    }
    
    public void setRdc(String rdc) {
        this.rdc = rdc;
    }


    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PromVentasRdcActivasId) ) return false;
		 PromVentasRdcActivasId castOther = ( PromVentasRdcActivasId ) other; 
         
		 return ( (this.getBaseReference()==castOther.getBaseReference()) || ( this.getBaseReference()!=null && castOther.getBaseReference()!=null && this.getBaseReference().equals(castOther.getBaseReference()) ) )
 && ( (this.getPromSales()==castOther.getPromSales()) || ( this.getPromSales()!=null && castOther.getPromSales()!=null && this.getPromSales().equals(castOther.getPromSales()) ) )
 && ( (this.getPromSalesKg()==castOther.getPromSalesKg()) || ( this.getPromSalesKg()!=null && castOther.getPromSalesKg()!=null && this.getPromSalesKg().equals(castOther.getPromSalesKg()) ) )
 && ( (this.getCadena()==castOther.getCadena()) || ( this.getCadena()!=null && castOther.getCadena()!=null && this.getCadena().equals(castOther.getCadena()) ) )
 && ( (this.getAccType()==castOther.getAccType()) || ( this.getAccType()!=null && castOther.getAccType()!=null && this.getAccType().equals(castOther.getAccType()) ) )
 && ( (this.getRdc()==castOther.getRdc()) || ( this.getRdc()!=null && castOther.getRdc()!=null && this.getRdc().equals(castOther.getRdc()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBaseReference() == null ? 0 : this.getBaseReference().hashCode() );
         result = 37 * result + ( getPromSales() == null ? 0 : this.getPromSales().hashCode() );
         result = 37 * result + ( getPromSalesKg() == null ? 0 : this.getPromSalesKg().hashCode() );
         result = 37 * result + ( getCadena() == null ? 0 : this.getCadena().hashCode() );
         result = 37 * result + ( getAccType() == null ? 0 : this.getAccType().hashCode() );
         result = 37 * result + ( getRdc() == null ? 0 : this.getRdc().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         return result;
   }   


}


