package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PruebasId generated by hbm2java
 */
@Embeddable
public class PruebasId  implements java.io.Serializable {


     private Date fecha;
     private String months;
     private String years;

    public PruebasId() {
    }

    public PruebasId(Date fecha, String months, String years) {
       this.fecha = fecha;
       this.months = months;
       this.years = years;
    }
   


    @Column(name="fecha", nullable=false, length=29)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


    @Column(name="months", nullable=false)
    public String getMonths() {
        return this.months;
    }
    
    public void setMonths(String months) {
        this.months = months;
    }


    @Column(name="years", nullable=false)
    public String getYears() {
        return this.years;
    }
    
    public void setYears(String years) {
        this.years = years;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PruebasId) ) return false;
		 PruebasId castOther = ( PruebasId ) other; 
         
		 return ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getMonths()==castOther.getMonths()) || ( this.getMonths()!=null && castOther.getMonths()!=null && this.getMonths().equals(castOther.getMonths()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getMonths() == null ? 0 : this.getMonths().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         return result;
   }   


}


