package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pruebas generated by hbm2java
 */
@Entity
@Table(name="pruebas"
    ,schema="salesforce"
)
public class Pruebas  implements java.io.Serializable {


     private PruebasId id;

    public Pruebas() {
    }

    public Pruebas(PruebasId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fecha", column=@Column(name="fecha", nullable=false, length=29) ), 
        @AttributeOverride(name="months", column=@Column(name="months", nullable=false) ), 
        @AttributeOverride(name="years", column=@Column(name="years", nullable=false) ) } )
    public PruebasId getId() {
        return this.id;
    }
    
    public void setId(PruebasId id) {
        this.id = id;
    }




}


