package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResumenVentasRdc generated by hbm2java
 */
@Entity
@Table(name="resumen_ventas_rdc"
    ,schema="salesforce"
)
public class ResumenVentasRdc  implements java.io.Serializable {


     private long id;
     private String brand;
     private String brandName;
     private String months;
     private String rdc;
     private Long sumEur;
     private String years;

    public ResumenVentasRdc() {
    }

	
    public ResumenVentasRdc(long id) {
        this.id = id;
    }
    public ResumenVentasRdc(long id, String brand, String brandName, String months, String rdc, Long sumEur, String years) {
       this.id = id;
       this.brand = brand;
       this.brandName = brandName;
       this.months = months;
       this.rdc = rdc;
       this.sumEur = sumEur;
       this.years = years;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="brand")
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }

    
    @Column(name="brand_name")
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="months")
    public String getMonths() {
        return this.months;
    }
    
    public void setMonths(String months) {
        this.months = months;
    }

    
    @Column(name="rdc")
    public String getRdc() {
        return this.rdc;
    }
    
    public void setRdc(String rdc) {
        this.rdc = rdc;
    }

    
    @Column(name="sum_eur")
    public Long getSumEur() {
        return this.sumEur;
    }
    
    public void setSumEur(Long sumEur) {
        this.sumEur = sumEur;
    }

    
    @Column(name="years")
    public String getYears() {
        return this.years;
    }
    
    public void setYears(String years) {
        this.years = years;
    }




}


