package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ShipToPictureC generated by hbm2java
 */
@Entity
@Table(name="ship_to_picture__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class ShipToPictureC  implements java.io.Serializable {


     private Integer id;
     private Date createddate;
     private Boolean isdeleted;
     private String name;
     private Date systemmodstamp;
     private String lkpShipToC;
     private String pictureUrlC;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String pckPictureTypeC;

    public ShipToPictureC() {
    }

	
    public ShipToPictureC(Integer id) {
        this.id = id;
    }
    public ShipToPictureC(Integer id, Date createddate, Boolean isdeleted, String name, Date systemmodstamp, String lkpShipToC, String pictureUrlC, String sfid, String hcLastop, String hcErr, String pckPictureTypeC) {
       this.id = id;
       this.createddate = createddate;
       this.isdeleted = isdeleted;
       this.name = name;
       this.systemmodstamp = systemmodstamp;
       this.lkpShipToC = lkpShipToC;
       this.pictureUrlC = pictureUrlC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.pckPictureTypeC = pckPictureTypeC;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="lkp_ship_to__c", length=18)
    public String getLkpShipToC() {
        return this.lkpShipToC;
    }
    
    public void setLkpShipToC(String lkpShipToC) {
        this.lkpShipToC = lkpShipToC;
    }

    
    @Column(name="picture_url__c")
    public String getPictureUrlC() {
        return this.pictureUrlC;
    }
    
    public void setPictureUrlC(String pictureUrlC) {
        this.pictureUrlC = pictureUrlC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="pck_picture_type__c")
    public String getPckPictureTypeC() {
        return this.pckPictureTypeC;
    }
    
    public void setPckPictureTypeC(String pckPictureTypeC) {
        this.pckPictureTypeC = pckPictureTypeC;
    }




}


