package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SpotCheckC generated by hbm2java
 */
@Entity
@Table(name="spot_check__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class SpotCheckC  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private Date createddate;
     private String sfid;
     private String hcLastop;
     private String hcErr;
     private String txtOtrosElementosC;
     private String lkpPuntoDeEntregaC;
     private Double numMetrosC;
     private Boolean chkPresenciaC;
     private Double precioC;
     private String pckMarcaC;

    public SpotCheckC() {
    }

	
    public SpotCheckC(Integer id) {
        this.id = id;
    }
    public SpotCheckC(Integer id, String name, Boolean isdeleted, Date systemmodstamp, Date createddate, String sfid, String hcLastop, String hcErr, String txtOtrosElementosC, String lkpPuntoDeEntregaC, Double numMetrosC, Boolean chkPresenciaC, Double precioC, String pckMarcaC) {
       this.id = id;
       this.name = name;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.createddate = createddate;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
       this.txtOtrosElementosC = txtOtrosElementosC;
       this.lkpPuntoDeEntregaC = lkpPuntoDeEntregaC;
       this.numMetrosC = numMetrosC;
       this.chkPresenciaC = chkPresenciaC;
       this.precioC = precioC;
       this.pckMarcaC = pckMarcaC;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="txt_otros_elementos__c")
    public String getTxtOtrosElementosC() {
        return this.txtOtrosElementosC;
    }
    
    public void setTxtOtrosElementosC(String txtOtrosElementosC) {
        this.txtOtrosElementosC = txtOtrosElementosC;
    }

    
    @Column(name="lkp_punto_de_entrega__c", length=18)
    public String getLkpPuntoDeEntregaC() {
        return this.lkpPuntoDeEntregaC;
    }
    
    public void setLkpPuntoDeEntregaC(String lkpPuntoDeEntregaC) {
        this.lkpPuntoDeEntregaC = lkpPuntoDeEntregaC;
    }

    
    @Column(name="num_metros__c", precision=17, scale=17)
    public Double getNumMetrosC() {
        return this.numMetrosC;
    }
    
    public void setNumMetrosC(Double numMetrosC) {
        this.numMetrosC = numMetrosC;
    }

    
    @Column(name="chk_presencia__c")
    public Boolean getChkPresenciaC() {
        return this.chkPresenciaC;
    }
    
    public void setChkPresenciaC(Boolean chkPresenciaC) {
        this.chkPresenciaC = chkPresenciaC;
    }

    
    @Column(name="precio__c", precision=17, scale=17)
    public Double getPrecioC() {
        return this.precioC;
    }
    
    public void setPrecioC(Double precioC) {
        this.precioC = precioC;
    }

    
    @Column(name="pck_marca__c")
    public String getPckMarcaC() {
        return this.pckMarcaC;
    }
    
    public void setPckMarcaC(String pckMarcaC) {
        this.pckMarcaC = pckMarcaC;
    }




}


