package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SumVentasTop30CountryId generated by hbm2java
 */
@Embeddable
public class SumVentasTop30CountryId  implements java.io.Serializable {


     private String country;
     private String subBrand;
     private String baseReference;
     private String cadena;
     private String accType;
     private Double sumUnidades;
     private Double sumEuros;
     private Double sumKg;

    public SumVentasTop30CountryId() {
    }

    public SumVentasTop30CountryId(String country, String subBrand, String baseReference, String cadena, String accType, Double sumUnidades, Double sumEuros, Double sumKg) {
       this.country = country;
       this.subBrand = subBrand;
       this.baseReference = baseReference;
       this.cadena = cadena;
       this.accType = accType;
       this.sumUnidades = sumUnidades;
       this.sumEuros = sumEuros;
       this.sumKg = sumKg;
    }
   


    @Column(name="country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }


    @Column(name="sub_brand")
    public String getSubBrand() {
        return this.subBrand;
    }
    
    public void setSubBrand(String subBrand) {
        this.subBrand = subBrand;
    }


    @Column(name="base_reference")
    public String getBaseReference() {
        return this.baseReference;
    }
    
    public void setBaseReference(String baseReference) {
        this.baseReference = baseReference;
    }


    @Column(name="cadena")
    public String getCadena() {
        return this.cadena;
    }
    
    public void setCadena(String cadena) {
        this.cadena = cadena;
    }


    @Column(name="acc_type")
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }


    @Column(name="sum_unidades", precision=17, scale=17)
    public Double getSumUnidades() {
        return this.sumUnidades;
    }
    
    public void setSumUnidades(Double sumUnidades) {
        this.sumUnidades = sumUnidades;
    }


    @Column(name="sum_euros", precision=17, scale=17)
    public Double getSumEuros() {
        return this.sumEuros;
    }
    
    public void setSumEuros(Double sumEuros) {
        this.sumEuros = sumEuros;
    }


    @Column(name="sum_kg", precision=17, scale=17)
    public Double getSumKg() {
        return this.sumKg;
    }
    
    public void setSumKg(Double sumKg) {
        this.sumKg = sumKg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SumVentasTop30CountryId) ) return false;
		 SumVentasTop30CountryId castOther = ( SumVentasTop30CountryId ) other; 
         
		 return ( (this.getCountry()==castOther.getCountry()) || ( this.getCountry()!=null && castOther.getCountry()!=null && this.getCountry().equals(castOther.getCountry()) ) )
 && ( (this.getSubBrand()==castOther.getSubBrand()) || ( this.getSubBrand()!=null && castOther.getSubBrand()!=null && this.getSubBrand().equals(castOther.getSubBrand()) ) )
 && ( (this.getBaseReference()==castOther.getBaseReference()) || ( this.getBaseReference()!=null && castOther.getBaseReference()!=null && this.getBaseReference().equals(castOther.getBaseReference()) ) )
 && ( (this.getCadena()==castOther.getCadena()) || ( this.getCadena()!=null && castOther.getCadena()!=null && this.getCadena().equals(castOther.getCadena()) ) )
 && ( (this.getAccType()==castOther.getAccType()) || ( this.getAccType()!=null && castOther.getAccType()!=null && this.getAccType().equals(castOther.getAccType()) ) )
 && ( (this.getSumUnidades()==castOther.getSumUnidades()) || ( this.getSumUnidades()!=null && castOther.getSumUnidades()!=null && this.getSumUnidades().equals(castOther.getSumUnidades()) ) )
 && ( (this.getSumEuros()==castOther.getSumEuros()) || ( this.getSumEuros()!=null && castOther.getSumEuros()!=null && this.getSumEuros().equals(castOther.getSumEuros()) ) )
 && ( (this.getSumKg()==castOther.getSumKg()) || ( this.getSumKg()!=null && castOther.getSumKg()!=null && this.getSumKg().equals(castOther.getSumKg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountry() == null ? 0 : this.getCountry().hashCode() );
         result = 37 * result + ( getSubBrand() == null ? 0 : this.getSubBrand().hashCode() );
         result = 37 * result + ( getBaseReference() == null ? 0 : this.getBaseReference().hashCode() );
         result = 37 * result + ( getCadena() == null ? 0 : this.getCadena().hashCode() );
         result = 37 * result + ( getAccType() == null ? 0 : this.getAccType().hashCode() );
         result = 37 * result + ( getSumUnidades() == null ? 0 : this.getSumUnidades().hashCode() );
         result = 37 * result + ( getSumEuros() == null ? 0 : this.getSumEuros().hashCode() );
         result = 37 * result + ( getSumKg() == null ? 0 : this.getSumKg().hashCode() );
         return result;
   }   


}


