package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SumVentasTop30 generated by hbm2java
 */
@Entity
@Table(name="sum_ventas_top30"
    ,schema="salesforce"
)
public class SumVentasTop30  implements java.io.Serializable {


     private long id;
     private String customerCode;
     private String subBrand;
     private String baseReference;
     private String cadena;
     private String accType;
     private String rdc;
     private String tam;
     private String country;
     private Double sumUnidades;
     private Double sumEuros;
     private Double sumKg;
     private String productName;

    public SumVentasTop30() {
    }

	
    public SumVentasTop30(long id) {
        this.id = id;
    }
    public SumVentasTop30(long id, String customerCode, String subBrand, String baseReference, String cadena, String accType, String rdc, String tam, String country, Double sumUnidades, Double sumEuros, Double sumKg, String productName) {
       this.id = id;
       this.customerCode = customerCode;
       this.subBrand = subBrand;
       this.baseReference = baseReference;
       this.cadena = cadena;
       this.accType = accType;
       this.rdc = rdc;
       this.tam = tam;
       this.country = country;
       this.sumUnidades = sumUnidades;
       this.sumEuros = sumEuros;
       this.sumKg = sumKg;
       this.productName = productName;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="customer_code")
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="sub_brand")
    public String getSubBrand() {
        return this.subBrand;
    }
    
    public void setSubBrand(String subBrand) {
        this.subBrand = subBrand;
    }

    
    @Column(name="base_reference")
    public String getBaseReference() {
        return this.baseReference;
    }
    
    public void setBaseReference(String baseReference) {
        this.baseReference = baseReference;
    }

    
    @Column(name="cadena")
    public String getCadena() {
        return this.cadena;
    }
    
    public void setCadena(String cadena) {
        this.cadena = cadena;
    }

    
    @Column(name="acc_type")
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }

    
    @Column(name="rdc")
    public String getRdc() {
        return this.rdc;
    }
    
    public void setRdc(String rdc) {
        this.rdc = rdc;
    }

    
    @Column(name="tam")
    public String getTam() {
        return this.tam;
    }
    
    public void setTam(String tam) {
        this.tam = tam;
    }

    
    @Column(name="country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="sum_unidades", precision=17, scale=17)
    public Double getSumUnidades() {
        return this.sumUnidades;
    }
    
    public void setSumUnidades(Double sumUnidades) {
        this.sumUnidades = sumUnidades;
    }

    
    @Column(name="sum_euros", precision=17, scale=17)
    public Double getSumEuros() {
        return this.sumEuros;
    }
    
    public void setSumEuros(Double sumEuros) {
        this.sumEuros = sumEuros;
    }

    
    @Column(name="sum_kg", precision=17, scale=17)
    public Double getSumKg() {
        return this.sumKg;
    }
    
    public void setSumKg(Double sumKg) {
        this.sumKg = sumKg;
    }

    
    @Column(name="product_name")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }




}


