package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SumVentasPesocliente generated by hbm2java
 */
@Entity
@Table(name="sum_ventas_pesocliente"
    ,schema="salesforce"
)
public class SumVentasPesocliente  implements java.io.Serializable {


     private SumVentasPesoclienteId id;

    public SumVentasPesocliente() {
    }

    public SumVentasPesocliente(SumVentasPesoclienteId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code") ), 
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="sumVentas", column=@Column(name="sum_ventas", precision=17, scale=17) ) } )
    public SumVentasPesoclienteId getId() {
        return this.id;
    }
    
    public void setId(SumVentasPesoclienteId id) {
        this.id = id;
    }




}


