package com.minsait.affinity.jpa.model;




import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaEvolucionId generated by hbm2java
 */
@Embeddable
public class TablaEvolucionId  implements java.io.Serializable {


     private String rdc;
     private String valueIs;
     private Double ventas;
     private Integer years;

    public TablaEvolucionId() {
    }

    public TablaEvolucionId(String rdc, String valueIs, Double ventas, Integer years) {
       this.rdc = rdc;
       this.valueIs = valueIs;
       this.ventas = ventas;
       this.years = years;
    }
   


    @Column(name="rdc")
    public String getRdc() {
        return this.rdc;
    }
    
    public void setRdc(String rdc) {
        this.rdc = rdc;
    }


    @Column(name="value_is")
    public String getValueIs() {
        return this.valueIs;
    }
    
    public void setValueIs(String valueIs) {
        this.valueIs = valueIs;
    }


    @Column(name="ventas", precision=17, scale=17)
    public Double getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Double ventas) {
        this.ventas = ventas;
    }


    @Column(name="years")
    public Integer getYears() {
        return this.years;
    }
    
    public void setYears(Integer years) {
        this.years = years;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TablaEvolucionId) ) return false;
		 TablaEvolucionId castOther = ( TablaEvolucionId ) other; 
         
		 return ( (this.getRdc()==castOther.getRdc()) || ( this.getRdc()!=null && castOther.getRdc()!=null && this.getRdc().equals(castOther.getRdc()) ) )
 && ( (this.getValueIs()==castOther.getValueIs()) || ( this.getValueIs()!=null && castOther.getValueIs()!=null && this.getValueIs().equals(castOther.getValueIs()) ) )
 && ( (this.getVentas()==castOther.getVentas()) || ( this.getVentas()!=null && castOther.getVentas()!=null && this.getVentas().equals(castOther.getVentas()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRdc() == null ? 0 : this.getRdc().hashCode() );
         result = 37 * result + ( getValueIs() == null ? 0 : this.getValueIs().hashCode() );
         result = 37 * result + ( getVentas() == null ? 0 : this.getVentas().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         return result;
   }   


}


