package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablaVentas generated by hbm2java
 */
@Entity
@Table(name="tabla_ventas"
    ,schema="salesforce"
)
public class TablaVentas  implements java.io.Serializable {


     private long id;
     private Integer years;
     private Integer monthNum;
     private String customerCode;
     private String basereferencecode;
     private Double salesUnits;
     private Double salesPetfoodkgwithloading;
     private Double totalgrosssales;
     private Double netsales;
     private Double netnetsales;
     private Double netcustomersales;

    public TablaVentas() {
    }

	
    public TablaVentas(long id) {
        this.id = id;
    }
    public TablaVentas(long id, Integer years, Integer monthNum, String customerCode, String basereferencecode, Double salesUnits, Double salesPetfoodkgwithloading, Double totalgrosssales, Double netsales, Double netnetsales, Double netcustomersales) {
       this.id = id;
       this.years = years;
       this.monthNum = monthNum;
       this.customerCode = customerCode;
       this.basereferencecode = basereferencecode;
       this.salesUnits = salesUnits;
       this.salesPetfoodkgwithloading = salesPetfoodkgwithloading;
       this.totalgrosssales = totalgrosssales;
       this.netsales = netsales;
       this.netnetsales = netnetsales;
       this.netcustomersales = netcustomersales;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="years")
    public Integer getYears() {
        return this.years;
    }
    
    public void setYears(Integer years) {
        this.years = years;
    }

    
    @Column(name="month_num")
    public Integer getMonthNum() {
        return this.monthNum;
    }
    
    public void setMonthNum(Integer monthNum) {
        this.monthNum = monthNum;
    }

    
    @Column(name="customer_code")
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="basereferencecode")
    public String getBasereferencecode() {
        return this.basereferencecode;
    }
    
    public void setBasereferencecode(String basereferencecode) {
        this.basereferencecode = basereferencecode;
    }

    
    @Column(name="sales_units", precision=17, scale=17)
    public Double getSalesUnits() {
        return this.salesUnits;
    }
    
    public void setSalesUnits(Double salesUnits) {
        this.salesUnits = salesUnits;
    }

    
    @Column(name="sales_petfoodkgwithloading", precision=17, scale=17)
    public Double getSalesPetfoodkgwithloading() {
        return this.salesPetfoodkgwithloading;
    }
    
    public void setSalesPetfoodkgwithloading(Double salesPetfoodkgwithloading) {
        this.salesPetfoodkgwithloading = salesPetfoodkgwithloading;
    }

    
    @Column(name="totalgrosssales", precision=17, scale=17)
    public Double getTotalgrosssales() {
        return this.totalgrosssales;
    }
    
    public void setTotalgrosssales(Double totalgrosssales) {
        this.totalgrosssales = totalgrosssales;
    }

    
    @Column(name="netsales", precision=17, scale=17)
    public Double getNetsales() {
        return this.netsales;
    }
    
    public void setNetsales(Double netsales) {
        this.netsales = netsales;
    }

    
    @Column(name="netnetsales", precision=17, scale=17)
    public Double getNetnetsales() {
        return this.netnetsales;
    }
    
    public void setNetnetsales(Double netnetsales) {
        this.netnetsales = netnetsales;
    }

    
    @Column(name="netcustomersales", precision=17, scale=17)
    public Double getNetcustomersales() {
        return this.netcustomersales;
    }
    
    public void setNetcustomersales(Double netcustomersales) {
        this.netcustomersales = netcustomersales;
    }




}


