package com.minsait.affinity.jpa.model;

// Generated 26-mar-2020 13:26:37 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaEvolucion generated by hbm2java
 */
@Entity
@Table(name="tabla_evolucion"
    ,schema="salesforce"
)
public class TablaEvolucion  implements java.io.Serializable {


     private TablaEvolucionId id;

    public TablaEvolucion() {
    }

    public TablaEvolucion(TablaEvolucionId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="valueIs", column=@Column(name="value_is") ), 
        @AttributeOverride(name="ventas", column=@Column(name="ventas", precision=17, scale=17) ), 
        @AttributeOverride(name="years", column=@Column(name="years") ) } )
    public TablaEvolucionId getId() {
        return this.id;
    }
    
    public void setId(TablaEvolucionId id) {
        this.id = id;
    }




}


