package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaEvolucionIs generated by hbm2java
 */
@Entity
@Table(name="tabla_evolucion_is"
    ,schema="salesforce"
)
public class TablaEvolucionIs  implements java.io.Serializable {


     private TablaEvolucionIsId id;

    public TablaEvolucionIs() {
    }

    public TablaEvolucionIs(TablaEvolucionIsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userIs", column=@Column(name="user_is") ), 
        @AttributeOverride(name="ventas", column=@Column(name="ventas", precision=17, scale=17) ), 
        @AttributeOverride(name="years", column=@Column(name="years") ), 
        @AttributeOverride(name="updated", column=@Column(name="updated") ) } )
    public TablaEvolucionIsId getId() {
        return this.id;
    }
    
    public void setId(TablaEvolucionIsId id) {
        this.id = id;
    }




}


