package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaVentasInicialId generated by hbm2java
 */
@Embeddable
public class TablaVentasInicialId  implements java.io.Serializable {


     private String customerCode;
     private String basereferencecode;
     private Double salesUnits;
     private Double salesPetfoodkgwithloading;
     private Double totalgrosssales;
     private Double netsales;
     private Double netnetsales;
     private Double netcustomersales;
     private String years;
     private String monthNum;

    public TablaVentasInicialId() {
    }

    public TablaVentasInicialId(String customerCode, String basereferencecode, Double salesUnits, Double salesPetfoodkgwithloading, Double totalgrosssales, Double netsales, Double netnetsales, Double netcustomersales, String years, String monthNum) {
       this.customerCode = customerCode;
       this.basereferencecode = basereferencecode;
       this.salesUnits = salesUnits;
       this.salesPetfoodkgwithloading = salesPetfoodkgwithloading;
       this.totalgrosssales = totalgrosssales;
       this.netsales = netsales;
       this.netnetsales = netnetsales;
       this.netcustomersales = netcustomersales;
       this.years = years;
       this.monthNum = monthNum;
    }
   


    @Column(name="customer_code")
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }


    @Column(name="basereferencecode")
    public String getBasereferencecode() {
        return this.basereferencecode;
    }
    
    public void setBasereferencecode(String basereferencecode) {
        this.basereferencecode = basereferencecode;
    }


    @Column(name="sales_units", precision=17, scale=17)
    public Double getSalesUnits() {
        return this.salesUnits;
    }
    
    public void setSalesUnits(Double salesUnits) {
        this.salesUnits = salesUnits;
    }


    @Column(name="sales_petfoodkgwithloading", precision=17, scale=17)
    public Double getSalesPetfoodkgwithloading() {
        return this.salesPetfoodkgwithloading;
    }
    
    public void setSalesPetfoodkgwithloading(Double salesPetfoodkgwithloading) {
        this.salesPetfoodkgwithloading = salesPetfoodkgwithloading;
    }


    @Column(name="totalgrosssales", precision=17, scale=17)
    public Double getTotalgrosssales() {
        return this.totalgrosssales;
    }
    
    public void setTotalgrosssales(Double totalgrosssales) {
        this.totalgrosssales = totalgrosssales;
    }


    @Column(name="netsales", precision=17, scale=17)
    public Double getNetsales() {
        return this.netsales;
    }
    
    public void setNetsales(Double netsales) {
        this.netsales = netsales;
    }


    @Column(name="netnetsales", precision=17, scale=17)
    public Double getNetnetsales() {
        return this.netnetsales;
    }
    
    public void setNetnetsales(Double netnetsales) {
        this.netnetsales = netnetsales;
    }


    @Column(name="netcustomersales", precision=17, scale=17)
    public Double getNetcustomersales() {
        return this.netcustomersales;
    }
    
    public void setNetcustomersales(Double netcustomersales) {
        this.netcustomersales = netcustomersales;
    }


    @Column(name="years")
    public String getYears() {
        return this.years;
    }
    
    public void setYears(String years) {
        this.years = years;
    }


    @Column(name="month_num")
    public String getMonthNum() {
        return this.monthNum;
    }
    
    public void setMonthNum(String monthNum) {
        this.monthNum = monthNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TablaVentasInicialId) ) return false;
		 TablaVentasInicialId castOther = ( TablaVentasInicialId ) other; 
         
		 return ( (this.getCustomerCode()==castOther.getCustomerCode()) || ( this.getCustomerCode()!=null && castOther.getCustomerCode()!=null && this.getCustomerCode().equals(castOther.getCustomerCode()) ) )
 && ( (this.getBasereferencecode()==castOther.getBasereferencecode()) || ( this.getBasereferencecode()!=null && castOther.getBasereferencecode()!=null && this.getBasereferencecode().equals(castOther.getBasereferencecode()) ) )
 && ( (this.getSalesUnits()==castOther.getSalesUnits()) || ( this.getSalesUnits()!=null && castOther.getSalesUnits()!=null && this.getSalesUnits().equals(castOther.getSalesUnits()) ) )
 && ( (this.getSalesPetfoodkgwithloading()==castOther.getSalesPetfoodkgwithloading()) || ( this.getSalesPetfoodkgwithloading()!=null && castOther.getSalesPetfoodkgwithloading()!=null && this.getSalesPetfoodkgwithloading().equals(castOther.getSalesPetfoodkgwithloading()) ) )
 && ( (this.getTotalgrosssales()==castOther.getTotalgrosssales()) || ( this.getTotalgrosssales()!=null && castOther.getTotalgrosssales()!=null && this.getTotalgrosssales().equals(castOther.getTotalgrosssales()) ) )
 && ( (this.getNetsales()==castOther.getNetsales()) || ( this.getNetsales()!=null && castOther.getNetsales()!=null && this.getNetsales().equals(castOther.getNetsales()) ) )
 && ( (this.getNetnetsales()==castOther.getNetnetsales()) || ( this.getNetnetsales()!=null && castOther.getNetnetsales()!=null && this.getNetnetsales().equals(castOther.getNetnetsales()) ) )
 && ( (this.getNetcustomersales()==castOther.getNetcustomersales()) || ( this.getNetcustomersales()!=null && castOther.getNetcustomersales()!=null && this.getNetcustomersales().equals(castOther.getNetcustomersales()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) )
 && ( (this.getMonthNum()==castOther.getMonthNum()) || ( this.getMonthNum()!=null && castOther.getMonthNum()!=null && this.getMonthNum().equals(castOther.getMonthNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomerCode() == null ? 0 : this.getCustomerCode().hashCode() );
         result = 37 * result + ( getBasereferencecode() == null ? 0 : this.getBasereferencecode().hashCode() );
         result = 37 * result + ( getSalesUnits() == null ? 0 : this.getSalesUnits().hashCode() );
         result = 37 * result + ( getSalesPetfoodkgwithloading() == null ? 0 : this.getSalesPetfoodkgwithloading().hashCode() );
         result = 37 * result + ( getTotalgrosssales() == null ? 0 : this.getTotalgrosssales().hashCode() );
         result = 37 * result + ( getNetsales() == null ? 0 : this.getNetsales().hashCode() );
         result = 37 * result + ( getNetnetsales() == null ? 0 : this.getNetnetsales().hashCode() );
         result = 37 * result + ( getNetcustomersales() == null ? 0 : this.getNetcustomersales().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         result = 37 * result + ( getMonthNum() == null ? 0 : this.getMonthNum().hashCode() );
         return result;
   }   


}


