package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaVentasTop30Affinity generated by hbm2java
 */
@Entity
@Table(name="tabla_ventas_top30_affinity"
    ,schema="salesforce"
)
public class TablaVentasTop30Affinity  implements java.io.Serializable {


     private TablaVentasTop30AffinityId id;

    public TablaVentasTop30Affinity() {
    }

    public TablaVentasTop30Affinity(TablaVentasTop30AffinityId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code") ), 
        @AttributeOverride(name="subBrand", column=@Column(name="sub_brand") ), 
        @AttributeOverride(name="baseReference", column=@Column(name="base_reference") ), 
        @AttributeOverride(name="netSales", column=@Column(name="net_sales", precision=17, scale=17) ), 
        @AttributeOverride(name="kgSales", column=@Column(name="kg_sales", precision=17, scale=17) ), 
        @AttributeOverride(name="cadena", column=@Column(name="cadena") ), 
        @AttributeOverride(name="accType", column=@Column(name="acc_type") ), 
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="tam", column=@Column(name="tam") ), 
        @AttributeOverride(name="country", column=@Column(name="country") ), 
        @AttributeOverride(name="units", column=@Column(name="units", precision=17, scale=17) ), 
        @AttributeOverride(name="productName", column=@Column(name="product_name") ) } )
    public TablaVentasTop30AffinityId getId() {
        return this.id;
    }
    
    public void setId(TablaVentasTop30AffinityId id) {
        this.id = id;
    }




}


