package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaEvolucionRdc generated by hbm2java
 */
@Entity
@Table(name="tabla_evolucion_rdc"
    ,schema="salesforce"
)
public class TablaEvolucionRdc  implements java.io.Serializable {


     private TablaEvolucionRdcId id;

    public TablaEvolucionRdc() {
    }

    public TablaEvolucionRdc(TablaEvolucionRdcId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="ventas", column=@Column(name="ventas", precision=17, scale=17) ), 
        @AttributeOverride(name="years", column=@Column(name="years") ), 
        @AttributeOverride(name="updated", column=@Column(name="updated") ) } )
    public TablaEvolucionRdcId getId() {
        return this.id;
    }
    
    public void setId(TablaEvolucionRdcId id) {
        this.id = id;
    }




}


