package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaEvolucionIsId generated by hbm2java
 */
@Embeddable
public class TablaEvolucionIsId  implements java.io.Serializable {


     private String userIs;
     private Double ventas;
     private Integer years;
     private Boolean updated;

    public TablaEvolucionIsId() {
    }

    public TablaEvolucionIsId(String userIs, Double ventas, Integer years, Boolean updated) {
       this.userIs = userIs;
       this.ventas = ventas;
       this.years = years;
       this.updated = updated;
    }
   


    @Column(name="user_is")
    public String getUserIs() {
        return this.userIs;
    }
    
    public void setUserIs(String userIs) {
        this.userIs = userIs;
    }


    @Column(name="ventas", precision=17, scale=17)
    public Double getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Double ventas) {
        this.ventas = ventas;
    }


    @Column(name="years")
    public Integer getYears() {
        return this.years;
    }
    
    public void setYears(Integer years) {
        this.years = years;
    }


    @Column(name="updated")
    public Boolean getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Boolean updated) {
        this.updated = updated;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TablaEvolucionIsId) ) return false;
		 TablaEvolucionIsId castOther = ( TablaEvolucionIsId ) other; 
         
		 return ( (this.getUserIs()==castOther.getUserIs()) || ( this.getUserIs()!=null && castOther.getUserIs()!=null && this.getUserIs().equals(castOther.getUserIs()) ) )
 && ( (this.getVentas()==castOther.getVentas()) || ( this.getVentas()!=null && castOther.getVentas()!=null && this.getVentas().equals(castOther.getVentas()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) )
 && ( (this.getUpdated()==castOther.getUpdated()) || ( this.getUpdated()!=null && castOther.getUpdated()!=null && this.getUpdated().equals(castOther.getUpdated()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserIs() == null ? 0 : this.getUserIs().hashCode() );
         result = 37 * result + ( getVentas() == null ? 0 : this.getVentas().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         result = 37 * result + ( getUpdated() == null ? 0 : this.getUpdated().hashCode() );
         return result;
   }   


}


