package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaVentasObjetivo generated by hbm2java
 */
@Entity
@Table(name="tabla_ventas_objetivo"
    ,schema="salesforce"
)
public class TablaVentasObjetivo  implements java.io.Serializable {


     private TablaVentasObjetivoId id;

    public TablaVentasObjetivo() {
    }

    public TablaVentasObjetivo(TablaVentasObjetivoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="valueIs", column=@Column(name="value_is") ), 
        @AttributeOverride(name="sumKg", column=@Column(name="sum_kg", precision=17, scale=17) ), 
        @AttributeOverride(name="subbrand", column=@Column(name="subbrand") ), 
        @AttributeOverride(name="fechaCompra", column=@Column(name="fecha_compra", length=13) ), 
        @AttributeOverride(name="salesEntity", column=@Column(name="sales_entity") ), 
        @AttributeOverride(name="baseReference", column=@Column(name="base_reference") ), 
        @AttributeOverride(name="cadena", column=@Column(name="cadena") ), 
        @AttributeOverride(name="accType", column=@Column(name="acc_type") ), 
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code") ) } )
    public TablaVentasObjetivoId getId() {
        return this.id;
    }
    
    public void setId(TablaVentasObjetivoId id) {
        this.id = id;
    }




}


