package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaVentasRefClaveActivas generated by hbm2java
 */
@Entity
@Table(name="tabla_ventas_ref_clave_activas"
    ,schema="salesforce"
)
public class TablaVentasRefClaveActivas  implements java.io.Serializable {


     private TablaVentasRefClaveActivasId id;

    public TablaVentasRefClaveActivas() {
    }

    public TablaVentasRefClaveActivas(TablaVentasRefClaveActivasId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code") ), 
        @AttributeOverride(name="years", column=@Column(name="years") ), 
        @AttributeOverride(name="months", column=@Column(name="months") ), 
        @AttributeOverride(name="baseReference", column=@Column(name="base_reference") ), 
        @AttributeOverride(name="salesUnits", column=@Column(name="sales_units", precision=17, scale=17) ), 
        @AttributeOverride(name="salesKg", column=@Column(name="sales_kg", precision=17, scale=17) ), 
        @AttributeOverride(name="cadena", column=@Column(name="cadena") ), 
        @AttributeOverride(name="subcadena", column=@Column(name="subcadena") ), 
        @AttributeOverride(name="accType", column=@Column(name="acc_type") ), 
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="tam", column=@Column(name="tam") ), 
        @AttributeOverride(name="billingcountry", column=@Column(name="billingcountry") ), 
        @AttributeOverride(name="status", column=@Column(name="status") ), 
        @AttributeOverride(name="herarchies", column=@Column(name="herarchies") ) } )
    public TablaVentasRefClaveActivasId getId() {
        return this.id;
    }
    
    public void setId(TablaVentasRefClaveActivasId id) {
        this.id = id;
    }




}


