package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaVentasCualitativos generated by hbm2java
 */
@Entity
@Table(name="tabla_ventas_cualitativos"
    ,schema="salesforce"
)
public class TablaVentasCualitativos  implements java.io.Serializable {


     private TablaVentasCualitativosId id;

    public TablaVentasCualitativos() {
    }

    public TablaVentasCualitativos(TablaVentasCualitativosId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rdc", column=@Column(name="rdc") ), 
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code") ), 
        @AttributeOverride(name="baseReference", column=@Column(name="base_reference") ), 
        @AttributeOverride(name="cadena", column=@Column(name="cadena") ), 
        @AttributeOverride(name="tipo", column=@Column(name="tipo") ), 
        @AttributeOverride(name="kg", column=@Column(name="kg", precision=17, scale=17) ), 
        @AttributeOverride(name="fecha", column=@Column(name="fecha", length=13) ) } )
    public TablaVentasCualitativosId getId() {
        return this.id;
    }
    
    public void setId(TablaVentasCualitativosId id) {
        this.id = id;
    }




}


