package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Task  implements java.io.Serializable {


     private Integer id;
     private String accountid;
     private Date dttVisitStartTimeC;
     private String subject;
     private String pckVisitTypeC;
     private String ownerid;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private String status;
     private Date odigoctiCallStartTimeC;
     private Date createddate;
     private String whoid;
     private String type;
     private String description;
     private Date activitydate;
     private String whatid;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public Task() {
    }

	
    public Task(Integer id) {
        this.id = id;
    }
    public Task(Integer id, String accountid, Date dttVisitStartTimeC, String subject, String pckVisitTypeC, String ownerid, Boolean isdeleted, Date systemmodstamp, String status, Date odigoctiCallStartTimeC, Date createddate, String whoid, String type, String description, Date activitydate, String whatid, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.accountid = accountid;
       this.dttVisitStartTimeC = dttVisitStartTimeC;
       this.subject = subject;
       this.pckVisitTypeC = pckVisitTypeC;
       this.ownerid = ownerid;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.status = status;
       this.odigoctiCallStartTimeC = odigoctiCallStartTimeC;
       this.createddate = createddate;
       this.whoid = whoid;
       this.type = type;
       this.description = description;
       this.activitydate = activitydate;
       this.whatid = whatid;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="accountid", length=18)
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtt_visit_start_time__c", length=29)
    public Date getDttVisitStartTimeC() {
        return this.dttVisitStartTimeC;
    }
    
    public void setDttVisitStartTimeC(Date dttVisitStartTimeC) {
        this.dttVisitStartTimeC = dttVisitStartTimeC;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="pck_visit_type__c")
    public String getPckVisitTypeC() {
        return this.pckVisitTypeC;
    }
    
    public void setPckVisitTypeC(String pckVisitTypeC) {
        this.pckVisitTypeC = pckVisitTypeC;
    }

    
    @Column(name="ownerid", length=18)
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="status", length=40)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="odigocti__call_start_time__c", length=29)
    public Date getOdigoctiCallStartTimeC() {
        return this.odigoctiCallStartTimeC;
    }
    
    public void setOdigoctiCallStartTimeC(Date odigoctiCallStartTimeC) {
        this.odigoctiCallStartTimeC = odigoctiCallStartTimeC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="whoid", length=18)
    public String getWhoid() {
        return this.whoid;
    }
    
    public void setWhoid(String whoid) {
        this.whoid = whoid;
    }

    
    @Column(name="type", length=40)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="activitydate", length=13)
    public Date getActivitydate() {
        return this.activitydate;
    }
    
    public void setActivitydate(Date activitydate) {
        this.activitydate = activitydate;
    }

    
    @Column(name="whatid", length=18)
    public String getWhatid() {
        return this.whatid;
    }
    
    public void setWhatid(String whatid) {
        this.whatid = whatid;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


