package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TestLoop generated by hbm2java
 */
@Entity
@Table(name="test_loop"
    ,schema="salesforce"
)
public class TestLoop  implements java.io.Serializable {


     private TestLoopId id;

    public TestLoop() {
    }

    public TestLoop(TestLoopId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="accType", column=@Column(name="acc_type", nullable=false) ), 
        @AttributeOverride(name="baseReference", column=@Column(name="base_reference", nullable=false) ), 
        @AttributeOverride(name="cadena", column=@Column(name="cadena", nullable=false) ), 
        @AttributeOverride(name="country", column=@Column(name="country", nullable=false) ), 
        @AttributeOverride(name="customerCode", column=@Column(name="customer_code", nullable=false) ), 
        @AttributeOverride(name="rdc", column=@Column(name="rdc", nullable=false) ), 
        @AttributeOverride(name="sumEuros", column=@Column(name="sum_euros", nullable=false) ), 
        @AttributeOverride(name="sumEuros2", column=@Column(name="sum_euros_2", nullable=false) ), 
        @AttributeOverride(name="sumKg", column=@Column(name="sum_kg", nullable=false) ), 
        @AttributeOverride(name="sumKg2", column=@Column(name="sum_kg_2", nullable=false) ), 
        @AttributeOverride(name="tam", column=@Column(name="tam", nullable=false) ) } )
    public TestLoopId getId() {
        return this.id;
    }
    
    public void setId(TestLoopId id) {
        this.id = id;
    }




}


