package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Top30FinalKgAffinity generated by hbm2java
 */
@Entity
@Table(name="top_30_final_kg_affinity"
    ,schema="salesforce"
)
public class Top30FinalKgAffinity  implements java.io.Serializable {


     private Integer id;
     private String baseReference;
     private String customerCode;
     private String productName;
     private String subBrand;
     private Long sumKg;
     private Long sumKgCountry;
     private Long sumKgRdc;
     private Long sumKgTam;

    public Top30FinalKgAffinity() {
    }

	
    public Top30FinalKgAffinity(Integer id) {
        this.id = id;
    }
    public Top30FinalKgAffinity(Integer id, String baseReference, String customerCode, String productName, String subBrand, Long sumKg, Long sumKgCountry, Long sumKgRdc, Long sumKgTam) {
       this.id = id;
       this.baseReference = baseReference;
       this.customerCode = customerCode;
       this.productName = productName;
       this.subBrand = subBrand;
       this.sumKg = sumKg;
       this.sumKgCountry = sumKgCountry;
       this.sumKgRdc = sumKgRdc;
       this.sumKgTam = sumKgTam;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="base_reference")
    public String getBaseReference() {
        return this.baseReference;
    }
    
    public void setBaseReference(String baseReference) {
        this.baseReference = baseReference;
    }

    
    @Column(name="customer_code")
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="product_name")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="sub_brand")
    public String getSubBrand() {
        return this.subBrand;
    }
    
    public void setSubBrand(String subBrand) {
        this.subBrand = subBrand;
    }

    
    @Column(name="sum_kg")
    public Long getSumKg() {
        return this.sumKg;
    }
    
    public void setSumKg(Long sumKg) {
        this.sumKg = sumKg;
    }

    
    @Column(name="sum_kg_country")
    public Long getSumKgCountry() {
        return this.sumKgCountry;
    }
    
    public void setSumKgCountry(Long sumKgCountry) {
        this.sumKgCountry = sumKgCountry;
    }

    
    @Column(name="sum_kg_rdc")
    public Long getSumKgRdc() {
        return this.sumKgRdc;
    }
    
    public void setSumKgRdc(Long sumKgRdc) {
        this.sumKgRdc = sumKgRdc;
    }

    
    @Column(name="sum_kg_tam")
    public Long getSumKgTam() {
        return this.sumKgTam;
    }
    
    public void setSumKgTam(Long sumKgTam) {
        this.sumKgTam = sumKgTam;
    }




}


