package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Top30FinalEurAffinity generated by hbm2java
 */
@Entity
@Table(name="top_30_final_eur_affinity"
    ,schema="salesforce"
)
public class Top30FinalEurAffinity  implements java.io.Serializable {


     private Integer id;
     private String baseReference;
     private String customerCode;
     private String productName;
     private String subBrand;
     private Long sumEur;
     private Long sumEurCountry;
     private Long sumEurRdc;
     private Long sumEurTam;

    public Top30FinalEurAffinity() {
    }

	
    public Top30FinalEurAffinity(Integer id) {
        this.id = id;
    }
    public Top30FinalEurAffinity(Integer id, String baseReference, String customerCode, String productName, String subBrand, Long sumEur, Long sumEurCountry, Long sumEurRdc, Long sumEurTam) {
       this.id = id;
       this.baseReference = baseReference;
       this.customerCode = customerCode;
       this.productName = productName;
       this.subBrand = subBrand;
       this.sumEur = sumEur;
       this.sumEurCountry = sumEurCountry;
       this.sumEurRdc = sumEurRdc;
       this.sumEurTam = sumEurTam;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="base_reference")
    public String getBaseReference() {
        return this.baseReference;
    }
    
    public void setBaseReference(String baseReference) {
        this.baseReference = baseReference;
    }

    
    @Column(name="customer_code")
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="product_name")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="sub_brand")
    public String getSubBrand() {
        return this.subBrand;
    }
    
    public void setSubBrand(String subBrand) {
        this.subBrand = subBrand;
    }

    
    @Column(name="sum_eur")
    public Long getSumEur() {
        return this.sumEur;
    }
    
    public void setSumEur(Long sumEur) {
        this.sumEur = sumEur;
    }

    
    @Column(name="sum_eur_country")
    public Long getSumEurCountry() {
        return this.sumEurCountry;
    }
    
    public void setSumEurCountry(Long sumEurCountry) {
        this.sumEurCountry = sumEurCountry;
    }

    
    @Column(name="sum_eur_rdc")
    public Long getSumEurRdc() {
        return this.sumEurRdc;
    }
    
    public void setSumEurRdc(Long sumEurRdc) {
        this.sumEurRdc = sumEurRdc;
    }

    
    @Column(name="sum_eur_tam")
    public Long getSumEurTam() {
        return this.sumEurTam;
    }
    
    public void setSumEurTam(Long sumEurTam) {
        this.sumEurTam = sumEurTam;
    }




}


