package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Top30FinalEurKg generated by hbm2java
 */
@Entity
@Table(name="top_30_final_eur_kg"
    ,schema="salesforce"
)
public class Top30FinalEurKg  implements java.io.Serializable {


     private long id;
     private String customerCode;
     private String subBrand;
     private String productName;
     private String baseReference;
     private Double sumEuros;
     private Double sumEurRdc;
     private Double sumEurTam;
     private Double sumEurCountry;
     private Double sumKg;
     private Double sumKgRdc;
     private Double sumKgTam;
     private Double sumKgCountry;

    public Top30FinalEurKg() {
    }

	
    public Top30FinalEurKg(long id) {
        this.id = id;
    }
    public Top30FinalEurKg(long id, String customerCode, String subBrand, String productName, String baseReference, Double sumEuros, Double sumEurRdc, Double sumEurTam, Double sumEurCountry, Double sumKg, Double sumKgRdc, Double sumKgTam, Double sumKgCountry) {
       this.id = id;
       this.customerCode = customerCode;
       this.subBrand = subBrand;
       this.productName = productName;
       this.baseReference = baseReference;
       this.sumEuros = sumEuros;
       this.sumEurRdc = sumEurRdc;
       this.sumEurTam = sumEurTam;
       this.sumEurCountry = sumEurCountry;
       this.sumKg = sumKg;
       this.sumKgRdc = sumKgRdc;
       this.sumKgTam = sumKgTam;
       this.sumKgCountry = sumKgCountry;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="customer_code")
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="sub_brand")
    public String getSubBrand() {
        return this.subBrand;
    }
    
    public void setSubBrand(String subBrand) {
        this.subBrand = subBrand;
    }

    
    @Column(name="product_name")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="base_reference")
    public String getBaseReference() {
        return this.baseReference;
    }
    
    public void setBaseReference(String baseReference) {
        this.baseReference = baseReference;
    }

    
    @Column(name="sum_euros", precision=17, scale=17)
    public Double getSumEuros() {
        return this.sumEuros;
    }
    
    public void setSumEuros(Double sumEuros) {
        this.sumEuros = sumEuros;
    }

    
    @Column(name="sum_eur_rdc", precision=17, scale=17)
    public Double getSumEurRdc() {
        return this.sumEurRdc;
    }
    
    public void setSumEurRdc(Double sumEurRdc) {
        this.sumEurRdc = sumEurRdc;
    }

    
    @Column(name="sum_eur_tam", precision=17, scale=17)
    public Double getSumEurTam() {
        return this.sumEurTam;
    }
    
    public void setSumEurTam(Double sumEurTam) {
        this.sumEurTam = sumEurTam;
    }

    
    @Column(name="sum_eur_country", precision=17, scale=17)
    public Double getSumEurCountry() {
        return this.sumEurCountry;
    }
    
    public void setSumEurCountry(Double sumEurCountry) {
        this.sumEurCountry = sumEurCountry;
    }

    
    @Column(name="sum_kg", precision=17, scale=17)
    public Double getSumKg() {
        return this.sumKg;
    }
    
    public void setSumKg(Double sumKg) {
        this.sumKg = sumKg;
    }

    
    @Column(name="sum_kg_rdc", precision=17, scale=17)
    public Double getSumKgRdc() {
        return this.sumKgRdc;
    }
    
    public void setSumKgRdc(Double sumKgRdc) {
        this.sumKgRdc = sumKgRdc;
    }

    
    @Column(name="sum_kg_tam", precision=17, scale=17)
    public Double getSumKgTam() {
        return this.sumKgTam;
    }
    
    public void setSumKgTam(Double sumKgTam) {
        this.sumKgTam = sumKgTam;
    }

    
    @Column(name="sum_kg_country", precision=17, scale=17)
    public Double getSumKgCountry() {
        return this.sumKgCountry;
    }
    
    public void setSumKgCountry(Double sumKgCountry) {
        this.sumKgCountry = sumKgCountry;
    }




}


