package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Translation generated by hbm2java
 */
@Entity
@Table(name="translation"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class Translation  implements java.io.Serializable {


     private Integer id;
     private Boolean canmanage;
     private String createdbyid;
     private Date createddate;
     private String hcErr;
     private String hcLastop;
     private Boolean isactive;
     private String language;
     private String lastmodifiedbyid;
     private Date lastmodifieddate;
     private String sfid;
     private Date systemmodstamp;

    public Translation() {
    }

	
    public Translation(Integer id) {
        this.id = id;
    }
    public Translation(Integer id, Boolean canmanage, String createdbyid, Date createddate, String hcErr, String hcLastop, Boolean isactive, String language, String lastmodifiedbyid, Date lastmodifieddate, String sfid, Date systemmodstamp) {
       this.id = id;
       this.canmanage = canmanage;
       this.createdbyid = createdbyid;
       this.createddate = createddate;
       this.hcErr = hcErr;
       this.hcLastop = hcLastop;
       this.isactive = isactive;
       this.language = language;
       this.lastmodifiedbyid = lastmodifiedbyid;
       this.lastmodifieddate = lastmodifieddate;
       this.sfid = sfid;
       this.systemmodstamp = systemmodstamp;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="canmanage")
    public Boolean getCanmanage() {
        return this.canmanage;
    }
    
    public void setCanmanage(Boolean canmanage) {
        this.canmanage = canmanage;
    }

    
    @Column(name="createdbyid", length=18)
    public String getCreatedbyid() {
        return this.createdbyid;
    }
    
    public void setCreatedbyid(String createdbyid) {
        this.createdbyid = createdbyid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="language", length=40)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    
    @Column(name="lastmodifiedbyid", length=18)
    public String getLastmodifiedbyid() {
        return this.lastmodifiedbyid;
    }
    
    public void setLastmodifiedbyid(String lastmodifiedbyid) {
        this.lastmodifiedbyid = lastmodifiedbyid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmodifieddate", length=29)
    public Date getLastmodifieddate() {
        return this.lastmodifieddate;
    }
    
    public void setLastmodifieddate(Date lastmodifieddate) {
        this.lastmodifieddate = lastmodifieddate;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }




}


