package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,schema="salesforce"
    , uniqueConstraints = {@UniqueConstraint(columnNames="sfid"), @UniqueConstraint(columnNames="txt_sap_id__c")} 
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String lastname;
     private String profileid;
     private String managerid;
     private String timezonesidkey;
     private String localesidkey;
     private String name;
     private String staffCountryC;
     private String languagelocalekey;
     private String phone;
     private Boolean isactive;
     private Date systemmodstamp;
     private String alias;
     private String emailencodingkey;
     private String username;
     private Date createddate;
     private String title;
     private String firstname;
     private String email;
     private String txtSapIdC;
     private String userroleid;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public User() {
    }

	
    public User(Integer id) {
        this.id = id;
    }
    public User(Integer id, String lastname, String profileid, String managerid, String timezonesidkey, String localesidkey, String name, String staffCountryC, String languagelocalekey, String phone, Boolean isactive, Date systemmodstamp, String alias, String emailencodingkey, String username, Date createddate, String title, String firstname, String email, String txtSapIdC, String userroleid, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.lastname = lastname;
       this.profileid = profileid;
       this.managerid = managerid;
       this.timezonesidkey = timezonesidkey;
       this.localesidkey = localesidkey;
       this.name = name;
       this.staffCountryC = staffCountryC;
       this.languagelocalekey = languagelocalekey;
       this.phone = phone;
       this.isactive = isactive;
       this.systemmodstamp = systemmodstamp;
       this.alias = alias;
       this.emailencodingkey = emailencodingkey;
       this.username = username;
       this.createddate = createddate;
       this.title = title;
       this.firstname = firstname;
       this.email = email;
       this.txtSapIdC = txtSapIdC;
       this.userroleid = userroleid;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="lastname", length=80)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="profileid", length=18)
    public String getProfileid() {
        return this.profileid;
    }
    
    public void setProfileid(String profileid) {
        this.profileid = profileid;
    }

    
    @Column(name="managerid", length=18)
    public String getManagerid() {
        return this.managerid;
    }
    
    public void setManagerid(String managerid) {
        this.managerid = managerid;
    }

    
    @Column(name="timezonesidkey", length=40)
    public String getTimezonesidkey() {
        return this.timezonesidkey;
    }
    
    public void setTimezonesidkey(String timezonesidkey) {
        this.timezonesidkey = timezonesidkey;
    }

    
    @Column(name="localesidkey", length=40)
    public String getLocalesidkey() {
        return this.localesidkey;
    }
    
    public void setLocalesidkey(String localesidkey) {
        this.localesidkey = localesidkey;
    }

    
    @Column(name="name", length=121)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="staff_country__c")
    public String getStaffCountryC() {
        return this.staffCountryC;
    }
    
    public void setStaffCountryC(String staffCountryC) {
        this.staffCountryC = staffCountryC;
    }

    
    @Column(name="languagelocalekey", length=40)
    public String getLanguagelocalekey() {
        return this.languagelocalekey;
    }
    
    public void setLanguagelocalekey(String languagelocalekey) {
        this.languagelocalekey = languagelocalekey;
    }

    
    @Column(name="phone", length=40)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="alias", length=8)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    
    @Column(name="emailencodingkey", length=40)
    public String getEmailencodingkey() {
        return this.emailencodingkey;
    }
    
    public void setEmailencodingkey(String emailencodingkey) {
        this.emailencodingkey = emailencodingkey;
    }

    
    @Column(name="username", length=80)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="title", length=80)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="firstname", length=40)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="email", length=128)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="txt_sap_id__c", unique=true, length=10)
    public String getTxtSapIdC() {
        return this.txtSapIdC;
    }
    
    public void setTxtSapIdC(String txtSapIdC) {
        this.txtSapIdC = txtSapIdC;
    }

    
    @Column(name="userroleid", length=18)
    public String getUserroleid() {
        return this.userroleid;
    }
    
    public void setUserroleid(String userroleid) {
        this.userroleid = userroleid;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


