package com.minsait.affinity.jpa.model;
// Generated 23-jul-2020 13:06:59 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserBackupC generated by hbm2java
 */
@Entity
@Table(name="user_backup__c"
    ,schema="salesforce"
    , uniqueConstraints = @UniqueConstraint(columnNames="sfid") 
)
public class UserBackupC  implements java.io.Serializable {


     private Integer id;
     private Date dtEndDateC;
     private Date dtStartDateC;
     private String name;
     private Boolean isdeleted;
     private Date systemmodstamp;
     private Boolean chkIsSubstitutingC;
     private String lkpMissingUserC;
     private Date createddate;
     private String lkpSubstituteC;
     private String sfid;
     private String hcLastop;
     private String hcErr;

    public UserBackupC() {
    }

	
    public UserBackupC(Integer id) {
        this.id = id;
    }
    public UserBackupC(Integer id, Date dtEndDateC, Date dtStartDateC, String name, Boolean isdeleted, Date systemmodstamp, Boolean chkIsSubstitutingC, String lkpMissingUserC, Date createddate, String lkpSubstituteC, String sfid, String hcLastop, String hcErr) {
       this.id = id;
       this.dtEndDateC = dtEndDateC;
       this.dtStartDateC = dtStartDateC;
       this.name = name;
       this.isdeleted = isdeleted;
       this.systemmodstamp = systemmodstamp;
       this.chkIsSubstitutingC = chkIsSubstitutingC;
       this.lkpMissingUserC = lkpMissingUserC;
       this.createddate = createddate;
       this.lkpSubstituteC = lkpSubstituteC;
       this.sfid = sfid;
       this.hcLastop = hcLastop;
       this.hcErr = hcErr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_end_date__c", length=13)
    public Date getDtEndDateC() {
        return this.dtEndDateC;
    }
    
    public void setDtEndDateC(Date dtEndDateC) {
        this.dtEndDateC = dtEndDateC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dt_start_date__c", length=13)
    public Date getDtStartDateC() {
        return this.dtStartDateC;
    }
    
    public void setDtStartDateC(Date dtStartDateC) {
        this.dtStartDateC = dtStartDateC;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp", length=29)
    public Date getSystemmodstamp() {
        return this.systemmodstamp;
    }
    
    public void setSystemmodstamp(Date systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    
    @Column(name="chk_is_substituting__c")
    public Boolean getChkIsSubstitutingC() {
        return this.chkIsSubstitutingC;
    }
    
    public void setChkIsSubstitutingC(Boolean chkIsSubstitutingC) {
        this.chkIsSubstitutingC = chkIsSubstitutingC;
    }

    
    @Column(name="lkp_missing_user__c", length=18)
    public String getLkpMissingUserC() {
        return this.lkpMissingUserC;
    }
    
    public void setLkpMissingUserC(String lkpMissingUserC) {
        this.lkpMissingUserC = lkpMissingUserC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    
    @Column(name="lkp_substitute__c", length=18)
    public String getLkpSubstituteC() {
        return this.lkpSubstituteC;
    }
    
    public void setLkpSubstituteC(String lkpSubstituteC) {
        this.lkpSubstituteC = lkpSubstituteC;
    }

    
    @Column(name="sfid", unique=true, length=18)
    public String getSfid() {
        return this.sfid;
    }
    
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    
    @Column(name="_hc_lastop", length=32)
    public String getHcLastop() {
        return this.hcLastop;
    }
    
    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    
    @Column(name="_hc_err")
    public String getHcErr() {
        return this.hcErr;
    }
    
    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }




}


