//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.22 at 05:16:48 PM CET 
//


package com.minsait.affinity.soap.price;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DT_ZSDF_SALESORDER_SIMULATE3_RESPONSE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DT_ZSDF_SALESORDER_SIMULATE3_RESPONSE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="E_ERROR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="E_MESSAGE" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="MSGTY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MSGID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MSGNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MSSPC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MSGTX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LT_ORDER_ITEMS_OUT" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ITM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PO_ITM_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MATERIAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_ENTRD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SHORT_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="NET_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBTOTAL_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBTOTAL_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBTOTAL_3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBTOTAL_4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBTOTAL_5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBTOTAL_6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SALES_UNIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="QTY_REQ_DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="DLV_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="REPL_TIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CONFIGURED" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PURCH_NO_C" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PURCH_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="PO_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="REF_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PURCH_NO_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PO_DAT_S" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="PO_METH_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="REF_1_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PO_ITM_NO_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="NET_VALUE1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="CURR_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="S_UNIT_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="REQ_QTY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="PLANT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="TX_DOC_CUR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_EXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_GUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_VERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_E_EXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_E_GUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MAT_E_VERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="TARGET_QTY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="TARGET_QU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="T_UNIT_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ITEM_CATEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SHIP_POINT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="HG_LV_ITEM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CUST_MAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PART_DLV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="REASON_REJ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="BILL_BLOCK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="STGE_LOC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PROD_HIER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MATL_GROUP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SUBT1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="SUBT2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="SUBT3" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="SUBT4" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="SUBT5" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="SUBT6" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DT_ZSDF_SALESORDER_SIMULATE3_RESPONSE", propOrder = {
    "eerror",
    "emessage",
    "ltorderitemsout"
})
public class DTZSDFSALESORDERSIMULATE3RESPONSE {

    @XmlElement(name = "E_ERROR")
    protected String eerror;
    @XmlElement(name = "E_MESSAGE")
    protected DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE emessage;
    @XmlElement(name = "LT_ORDER_ITEMS_OUT")
    protected DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT ltorderitemsout;

    /**
     * Gets the value of the eerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEERROR() {
        return eerror;
    }

    /**
     * Sets the value of the eerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEERROR(String value) {
        this.eerror = value;
    }

    /**
     * Gets the value of the emessage property.
     * 
     * @return
     *     possible object is
     *     {@link DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE }
     *     
     */
    public DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE getEMESSAGE() {
        return emessage;
    }

    /**
     * Sets the value of the emessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE }
     *     
     */
    public void setEMESSAGE(DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE value) {
        this.emessage = value;
    }

    /**
     * Gets the value of the ltorderitemsout property.
     * 
     * @return
     *     possible object is
     *     {@link DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT }
     *     
     */
    public DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT getLTORDERITEMSOUT() {
        return ltorderitemsout;
    }

    /**
     * Sets the value of the ltorderitemsout property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT }
     *     
     */
    public void setLTORDERITEMSOUT(DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT value) {
        this.ltorderitemsout = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="MSGTY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MSGID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MSGNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MSSPC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MSGTX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msgty",
        "msgid",
        "msgno",
        "msspc",
        "msgtx"
    })
    public static class EMESSAGE {

        @XmlElement(name = "MSGTY")
        protected String msgty;
        @XmlElement(name = "MSGID")
        protected String msgid;
        @XmlElement(name = "MSGNO")
        protected String msgno;
        @XmlElement(name = "MSSPC")
        protected String msspc;
        @XmlElement(name = "MSGTX")
        protected String msgtx;

        /**
         * Gets the value of the msgty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSGTY() {
            return msgty;
        }

        /**
         * Sets the value of the msgty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSGTY(String value) {
            this.msgty = value;
        }

        /**
         * Gets the value of the msgid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSGID() {
            return msgid;
        }

        /**
         * Sets the value of the msgid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSGID(String value) {
            this.msgid = value;
        }

        /**
         * Gets the value of the msgno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSGNO() {
            return msgno;
        }

        /**
         * Sets the value of the msgno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSGNO(String value) {
            this.msgno = value;
        }

        /**
         * Gets the value of the msspc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSSPC() {
            return msspc;
        }

        /**
         * Sets the value of the msspc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSSPC(String value) {
            this.msspc = value;
        }

        /**
         * Gets the value of the msgtx property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSGTX() {
            return msgtx;
        }

        /**
         * Sets the value of the msgtx property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSGTX(String value) {
            this.msgtx = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ITM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PO_ITM_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MATERIAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_ENTRD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SHORT_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="NET_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBTOTAL_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBTOTAL_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBTOTAL_3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBTOTAL_4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBTOTAL_5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBTOTAL_6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SALES_UNIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="QTY_REQ_DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="DLV_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="REPL_TIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CONFIGURED" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PURCH_NO_C" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PURCH_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="PO_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="REF_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PURCH_NO_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PO_DAT_S" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="PO_METH_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="REF_1_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PO_ITM_NO_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="NET_VALUE1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="CURR_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="S_UNIT_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="REQ_QTY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="PLANT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="TX_DOC_CUR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_EXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_GUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_VERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_E_EXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_E_GUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MAT_E_VERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="TARGET_QTY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="TARGET_QU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="T_UNIT_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ITEM_CATEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SHIP_POINT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="HG_LV_ITEM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CUST_MAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PART_DLV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="REASON_REJ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="BILL_BLOCK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="STGE_LOC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PROD_HIER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MATL_GROUP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SUBT1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="SUBT2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="SUBT3" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="SUBT4" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="SUBT5" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="SUBT6" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class LTORDERITEMSOUT {

        protected List<DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item }
         * 
         * 
         */
        public List<DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item> getItem() {
            if (item == null) {
                item = new ArrayList<DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ITM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PO_ITM_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MATERIAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MAT_ENTRD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SHORT_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="NET_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBTOTAL_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBTOTAL_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBTOTAL_3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBTOTAL_4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBTOTAL_5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBTOTAL_6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SALES_UNIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="QTY_REQ_DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="DLV_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="REPL_TIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CONFIGURED" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PURCH_NO_C" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PURCH_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="PO_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="REF_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PURCH_NO_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PO_DAT_S" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="PO_METH_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="REF_1_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PO_ITM_NO_S" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="NET_VALUE1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="CURR_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="S_UNIT_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="REQ_QTY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="PLANT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="TX_DOC_CUR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="MAT_EXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MAT_GUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MAT_VERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MAT_E_EXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MAT_E_GUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MAT_E_VERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="TARGET_QTY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="TARGET_QU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="T_UNIT_ISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ITEM_CATEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SHIP_POINT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="HG_LV_ITEM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CUST_MAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PART_DLV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="REASON_REJ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="BILL_BLOCK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="STGE_LOC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PROD_HIER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MATL_GROUP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SUBT1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="SUBT2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="SUBT3" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="SUBT4" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="SUBT5" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="SUBT6" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itmnumber",
            "poitmno",
            "material",
            "matentrd",
            "shorttext",
            "netvalue",
            "currency",
            "subtotal1",
            "subtotal2",
            "subtotal3",
            "subtotal4",
            "subtotal5",
            "subtotal6",
            "salesunit",
            "qtyreqdt",
            "dlvdate",
            "repltime",
            "configured",
            "purchnoc",
            "purchdate",
            "pomethod",
            "ref1",
            "purchnos",
            "podats",
            "pomeths",
            "ref1S",
            "poitmnos",
            "netvalue1",
            "curriso",
            "sunitiso",
            "reqqty",
            "plant",
            "txdoccur",
            "matext",
            "matguid",
            "matvers",
            "mateext",
            "mateguid",
            "matevers",
            "targetqty",
            "targetqu",
            "tunitiso",
            "itemcateg",
            "shippoint",
            "hglvitem",
            "custmat",
            "partdlv",
            "reasonrej",
            "billblock",
            "stgeloc",
            "prodhier",
            "matlgroup",
            "subt1",
            "subt2",
            "subt3",
            "subt4",
            "subt5",
            "subt6"
        })
        public static class Item {

            @XmlElement(name = "ITM_NUMBER")
            protected String itmnumber;
            @XmlElement(name = "PO_ITM_NO")
            protected String poitmno;
            @XmlElement(name = "MATERIAL")
            protected String material;
            @XmlElement(name = "MAT_ENTRD")
            protected String matentrd;
            @XmlElement(name = "SHORT_TEXT")
            protected String shorttext;
            @XmlElement(name = "NET_VALUE")
            protected String netvalue;
            @XmlElement(name = "CURRENCY")
            protected String currency;
            @XmlElement(name = "SUBTOTAL_1")
            protected String subtotal1;
            @XmlElement(name = "SUBTOTAL_2")
            protected String subtotal2;
            @XmlElement(name = "SUBTOTAL_3")
            protected String subtotal3;
            @XmlElement(name = "SUBTOTAL_4")
            protected String subtotal4;
            @XmlElement(name = "SUBTOTAL_5")
            protected String subtotal5;
            @XmlElement(name = "SUBTOTAL_6")
            protected String subtotal6;
            @XmlElement(name = "SALES_UNIT")
            protected String salesunit;
            @XmlElement(name = "QTY_REQ_DT")
            protected String qtyreqdt;
            @XmlElement(name = "DLV_DATE")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dlvdate;
            @XmlElement(name = "REPL_TIME")
            protected String repltime;
            @XmlElement(name = "CONFIGURED")
            protected String configured;
            @XmlElement(name = "PURCH_NO_C")
            protected String purchnoc;
            @XmlElement(name = "PURCH_DATE")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar purchdate;
            @XmlElement(name = "PO_METHOD")
            protected String pomethod;
            @XmlElement(name = "REF_1")
            protected String ref1;
            @XmlElement(name = "PURCH_NO_S")
            protected String purchnos;
            @XmlElement(name = "PO_DAT_S")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar podats;
            @XmlElement(name = "PO_METH_S")
            protected String pomeths;
            @XmlElement(name = "REF_1_S")
            protected String ref1S;
            @XmlElement(name = "PO_ITM_NO_S")
            protected String poitmnos;
            @XmlElement(name = "NET_VALUE1")
            protected BigDecimal netvalue1;
            @XmlElement(name = "CURR_ISO")
            protected String curriso;
            @XmlElement(name = "S_UNIT_ISO")
            protected String sunitiso;
            @XmlElement(name = "REQ_QTY")
            protected BigDecimal reqqty;
            @XmlElement(name = "PLANT")
            protected String plant;
            @XmlElement(name = "TX_DOC_CUR")
            protected BigDecimal txdoccur;
            @XmlElement(name = "MAT_EXT")
            protected String matext;
            @XmlElement(name = "MAT_GUID")
            protected String matguid;
            @XmlElement(name = "MAT_VERS")
            protected String matvers;
            @XmlElement(name = "MAT_E_EXT")
            protected String mateext;
            @XmlElement(name = "MAT_E_GUID")
            protected String mateguid;
            @XmlElement(name = "MAT_E_VERS")
            protected String matevers;
            @XmlElement(name = "TARGET_QTY")
            protected BigDecimal targetqty;
            @XmlElement(name = "TARGET_QU")
            protected String targetqu;
            @XmlElement(name = "T_UNIT_ISO")
            protected String tunitiso;
            @XmlElement(name = "ITEM_CATEG")
            protected String itemcateg;
            @XmlElement(name = "SHIP_POINT")
            protected String shippoint;
            @XmlElement(name = "HG_LV_ITEM")
            protected String hglvitem;
            @XmlElement(name = "CUST_MAT")
            protected String custmat;
            @XmlElement(name = "PART_DLV")
            protected String partdlv;
            @XmlElement(name = "REASON_REJ")
            protected String reasonrej;
            @XmlElement(name = "BILL_BLOCK")
            protected String billblock;
            @XmlElement(name = "STGE_LOC")
            protected String stgeloc;
            @XmlElement(name = "PROD_HIER")
            protected String prodhier;
            @XmlElement(name = "MATL_GROUP")
            protected String matlgroup;
            @XmlElement(name = "SUBT1")
            protected BigDecimal subt1;
            @XmlElement(name = "SUBT2")
            protected BigDecimal subt2;
            @XmlElement(name = "SUBT3")
            protected BigDecimal subt3;
            @XmlElement(name = "SUBT4")
            protected BigDecimal subt4;
            @XmlElement(name = "SUBT5")
            protected BigDecimal subt5;
            @XmlElement(name = "SUBT6")
            protected BigDecimal subt6;

            /**
             * Gets the value of the itmnumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getITMNUMBER() {
                return itmnumber;
            }

            /**
             * Sets the value of the itmnumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setITMNUMBER(String value) {
                this.itmnumber = value;
            }

            /**
             * Gets the value of the poitmno property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPOITMNO() {
                return poitmno;
            }

            /**
             * Sets the value of the poitmno property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPOITMNO(String value) {
                this.poitmno = value;
            }

            /**
             * Gets the value of the material property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATERIAL() {
                return material;
            }

            /**
             * Sets the value of the material property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATERIAL(String value) {
                this.material = value;
            }

            /**
             * Gets the value of the matentrd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATENTRD() {
                return matentrd;
            }

            /**
             * Sets the value of the matentrd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATENTRD(String value) {
                this.matentrd = value;
            }

            /**
             * Gets the value of the shorttext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSHORTTEXT() {
                return shorttext;
            }

            /**
             * Sets the value of the shorttext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSHORTTEXT(String value) {
                this.shorttext = value;
            }

            /**
             * Gets the value of the netvalue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNETVALUE() {
                return netvalue;
            }

            /**
             * Sets the value of the netvalue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNETVALUE(String value) {
                this.netvalue = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCURRENCY() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCURRENCY(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the subtotal1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUBTOTAL1() {
                return subtotal1;
            }

            /**
             * Sets the value of the subtotal1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUBTOTAL1(String value) {
                this.subtotal1 = value;
            }

            /**
             * Gets the value of the subtotal2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUBTOTAL2() {
                return subtotal2;
            }

            /**
             * Sets the value of the subtotal2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUBTOTAL2(String value) {
                this.subtotal2 = value;
            }

            /**
             * Gets the value of the subtotal3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUBTOTAL3() {
                return subtotal3;
            }

            /**
             * Sets the value of the subtotal3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUBTOTAL3(String value) {
                this.subtotal3 = value;
            }

            /**
             * Gets the value of the subtotal4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUBTOTAL4() {
                return subtotal4;
            }

            /**
             * Sets the value of the subtotal4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUBTOTAL4(String value) {
                this.subtotal4 = value;
            }

            /**
             * Gets the value of the subtotal5 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUBTOTAL5() {
                return subtotal5;
            }

            /**
             * Sets the value of the subtotal5 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUBTOTAL5(String value) {
                this.subtotal5 = value;
            }

            /**
             * Gets the value of the subtotal6 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUBTOTAL6() {
                return subtotal6;
            }

            /**
             * Sets the value of the subtotal6 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUBTOTAL6(String value) {
                this.subtotal6 = value;
            }

            /**
             * Gets the value of the salesunit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSALESUNIT() {
                return salesunit;
            }

            /**
             * Sets the value of the salesunit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSALESUNIT(String value) {
                this.salesunit = value;
            }

            /**
             * Gets the value of the qtyreqdt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQTYREQDT() {
                return qtyreqdt;
            }

            /**
             * Sets the value of the qtyreqdt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQTYREQDT(String value) {
                this.qtyreqdt = value;
            }

            /**
             * Gets the value of the dlvdate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDLVDATE() {
                return dlvdate;
            }

            /**
             * Sets the value of the dlvdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDLVDATE(XMLGregorianCalendar value) {
                this.dlvdate = value;
            }

            /**
             * Gets the value of the repltime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREPLTIME() {
                return repltime;
            }

            /**
             * Sets the value of the repltime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREPLTIME(String value) {
                this.repltime = value;
            }

            /**
             * Gets the value of the configured property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCONFIGURED() {
                return configured;
            }

            /**
             * Sets the value of the configured property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCONFIGURED(String value) {
                this.configured = value;
            }

            /**
             * Gets the value of the purchnoc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPURCHNOC() {
                return purchnoc;
            }

            /**
             * Sets the value of the purchnoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPURCHNOC(String value) {
                this.purchnoc = value;
            }

            /**
             * Gets the value of the purchdate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPURCHDATE() {
                return purchdate;
            }

            /**
             * Sets the value of the purchdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPURCHDATE(XMLGregorianCalendar value) {
                this.purchdate = value;
            }

            /**
             * Gets the value of the pomethod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPOMETHOD() {
                return pomethod;
            }

            /**
             * Sets the value of the pomethod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPOMETHOD(String value) {
                this.pomethod = value;
            }

            /**
             * Gets the value of the ref1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREF1() {
                return ref1;
            }

            /**
             * Sets the value of the ref1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREF1(String value) {
                this.ref1 = value;
            }

            /**
             * Gets the value of the purchnos property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPURCHNOS() {
                return purchnos;
            }

            /**
             * Sets the value of the purchnos property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPURCHNOS(String value) {
                this.purchnos = value;
            }

            /**
             * Gets the value of the podats property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPODATS() {
                return podats;
            }

            /**
             * Sets the value of the podats property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPODATS(XMLGregorianCalendar value) {
                this.podats = value;
            }

            /**
             * Gets the value of the pomeths property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPOMETHS() {
                return pomeths;
            }

            /**
             * Sets the value of the pomeths property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPOMETHS(String value) {
                this.pomeths = value;
            }

            /**
             * Gets the value of the ref1S property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREF1S() {
                return ref1S;
            }

            /**
             * Sets the value of the ref1S property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREF1S(String value) {
                this.ref1S = value;
            }

            /**
             * Gets the value of the poitmnos property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPOITMNOS() {
                return poitmnos;
            }

            /**
             * Sets the value of the poitmnos property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPOITMNOS(String value) {
                this.poitmnos = value;
            }

            /**
             * Gets the value of the netvalue1 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getNETVALUE1() {
                return netvalue1;
            }

            /**
             * Sets the value of the netvalue1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setNETVALUE1(BigDecimal value) {
                this.netvalue1 = value;
            }

            /**
             * Gets the value of the curriso property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCURRISO() {
                return curriso;
            }

            /**
             * Sets the value of the curriso property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCURRISO(String value) {
                this.curriso = value;
            }

            /**
             * Gets the value of the sunitiso property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUNITISO() {
                return sunitiso;
            }

            /**
             * Sets the value of the sunitiso property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUNITISO(String value) {
                this.sunitiso = value;
            }

            /**
             * Gets the value of the reqqty property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getREQQTY() {
                return reqqty;
            }

            /**
             * Sets the value of the reqqty property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setREQQTY(BigDecimal value) {
                this.reqqty = value;
            }

            /**
             * Gets the value of the plant property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPLANT() {
                return plant;
            }

            /**
             * Sets the value of the plant property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPLANT(String value) {
                this.plant = value;
            }

            /**
             * Gets the value of the txdoccur property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTXDOCCUR() {
                return txdoccur;
            }

            /**
             * Sets the value of the txdoccur property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTXDOCCUR(BigDecimal value) {
                this.txdoccur = value;
            }

            /**
             * Gets the value of the matext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATEXT() {
                return matext;
            }

            /**
             * Sets the value of the matext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATEXT(String value) {
                this.matext = value;
            }

            /**
             * Gets the value of the matguid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATGUID() {
                return matguid;
            }

            /**
             * Sets the value of the matguid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATGUID(String value) {
                this.matguid = value;
            }

            /**
             * Gets the value of the matvers property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATVERS() {
                return matvers;
            }

            /**
             * Sets the value of the matvers property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATVERS(String value) {
                this.matvers = value;
            }

            /**
             * Gets the value of the mateext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATEEXT() {
                return mateext;
            }

            /**
             * Sets the value of the mateext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATEEXT(String value) {
                this.mateext = value;
            }

            /**
             * Gets the value of the mateguid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATEGUID() {
                return mateguid;
            }

            /**
             * Sets the value of the mateguid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATEGUID(String value) {
                this.mateguid = value;
            }

            /**
             * Gets the value of the matevers property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATEVERS() {
                return matevers;
            }

            /**
             * Sets the value of the matevers property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATEVERS(String value) {
                this.matevers = value;
            }

            /**
             * Gets the value of the targetqty property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTARGETQTY() {
                return targetqty;
            }

            /**
             * Sets the value of the targetqty property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTARGETQTY(BigDecimal value) {
                this.targetqty = value;
            }

            /**
             * Gets the value of the targetqu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTARGETQU() {
                return targetqu;
            }

            /**
             * Sets the value of the targetqu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTARGETQU(String value) {
                this.targetqu = value;
            }

            /**
             * Gets the value of the tunitiso property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTUNITISO() {
                return tunitiso;
            }

            /**
             * Sets the value of the tunitiso property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTUNITISO(String value) {
                this.tunitiso = value;
            }

            /**
             * Gets the value of the itemcateg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getITEMCATEG() {
                return itemcateg;
            }

            /**
             * Sets the value of the itemcateg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setITEMCATEG(String value) {
                this.itemcateg = value;
            }

            /**
             * Gets the value of the shippoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSHIPPOINT() {
                return shippoint;
            }

            /**
             * Sets the value of the shippoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSHIPPOINT(String value) {
                this.shippoint = value;
            }

            /**
             * Gets the value of the hglvitem property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHGLVITEM() {
                return hglvitem;
            }

            /**
             * Sets the value of the hglvitem property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHGLVITEM(String value) {
                this.hglvitem = value;
            }

            /**
             * Gets the value of the custmat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCUSTMAT() {
                return custmat;
            }

            /**
             * Sets the value of the custmat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCUSTMAT(String value) {
                this.custmat = value;
            }

            /**
             * Gets the value of the partdlv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPARTDLV() {
                return partdlv;
            }

            /**
             * Sets the value of the partdlv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPARTDLV(String value) {
                this.partdlv = value;
            }

            /**
             * Gets the value of the reasonrej property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREASONREJ() {
                return reasonrej;
            }

            /**
             * Sets the value of the reasonrej property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREASONREJ(String value) {
                this.reasonrej = value;
            }

            /**
             * Gets the value of the billblock property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBILLBLOCK() {
                return billblock;
            }

            /**
             * Sets the value of the billblock property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBILLBLOCK(String value) {
                this.billblock = value;
            }

            /**
             * Gets the value of the stgeloc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTGELOC() {
                return stgeloc;
            }

            /**
             * Sets the value of the stgeloc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTGELOC(String value) {
                this.stgeloc = value;
            }

            /**
             * Gets the value of the prodhier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPRODHIER() {
                return prodhier;
            }

            /**
             * Sets the value of the prodhier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPRODHIER(String value) {
                this.prodhier = value;
            }

            /**
             * Gets the value of the matlgroup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMATLGROUP() {
                return matlgroup;
            }

            /**
             * Sets the value of the matlgroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMATLGROUP(String value) {
                this.matlgroup = value;
            }

            /**
             * Gets the value of the subt1 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSUBT1() {
                return subt1;
            }

            /**
             * Sets the value of the subt1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSUBT1(BigDecimal value) {
                this.subt1 = value;
            }

            /**
             * Gets the value of the subt2 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSUBT2() {
                return subt2;
            }

            /**
             * Sets the value of the subt2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSUBT2(BigDecimal value) {
                this.subt2 = value;
            }

            /**
             * Gets the value of the subt3 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSUBT3() {
                return subt3;
            }

            /**
             * Sets the value of the subt3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSUBT3(BigDecimal value) {
                this.subt3 = value;
            }

            /**
             * Gets the value of the subt4 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSUBT4() {
                return subt4;
            }

            /**
             * Sets the value of the subt4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSUBT4(BigDecimal value) {
                this.subt4 = value;
            }

            /**
             * Gets the value of the subt5 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSUBT5() {
                return subt5;
            }

            /**
             * Sets the value of the subt5 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSUBT5(BigDecimal value) {
                this.subt5 = value;
            }

            /**
             * Gets the value of the subt6 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSUBT6() {
                return subt6;
            }

            /**
             * Sets the value of the subt6 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSUBT6(BigDecimal value) {
                this.subt6 = value;
            }

        }

    }

}
