//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.22 at 05:16:48 PM CET 
//


package com.minsait.affinity.soap.price;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.minsait.affinity.soap.price package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MTZSDFSALESORDERSIMULATE3_QNAME = new QName("http://affinity-petcare.es/sales_force/sd/valoracion_pedido", "MT_ZSDF_SALESORDER_SIMULATE3");
    private final static QName _MTZSDFSALESORDERSIMULATE3RESPONSE_QNAME = new QName("http://affinity-petcare.es/sales_force/sd/valoracion_pedido", "MT_ZSDF_SALESORDER_SIMULATE3_RESPONSE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.minsait.affinity.soap.price
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3RESPONSE }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3RESPONSE createDTZSDFSALESORDERSIMULATE3RESPONSE() {
        return new DTZSDFSALESORDERSIMULATE3RESPONSE();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT createDTZSDFSALESORDERSIMULATE3RESPONSELTORDERITEMSOUT() {
        return new DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3 }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3 createDTZSDFSALESORDERSIMULATE3() {
        return new DTZSDFSALESORDERSIMULATE3();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3 .LTORDERITEMSOUT }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3 .LTORDERITEMSOUT createDTZSDFSALESORDERSIMULATE3LTORDERITEMSOUT() {
        return new DTZSDFSALESORDERSIMULATE3 .LTORDERITEMSOUT();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3 .ITDETAIL }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3 .ITDETAIL createDTZSDFSALESORDERSIMULATE3ITDETAIL() {
        return new DTZSDFSALESORDERSIMULATE3 .ITDETAIL();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE createDTZSDFSALESORDERSIMULATE3RESPONSEEMESSAGE() {
        return new DTZSDFSALESORDERSIMULATE3RESPONSE.EMESSAGE();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item createDTZSDFSALESORDERSIMULATE3RESPONSELTORDERITEMSOUTItem() {
        return new DTZSDFSALESORDERSIMULATE3RESPONSE.LTORDERITEMSOUT.Item();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3 .LTORDERITEMSOUT.Item }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3 .LTORDERITEMSOUT.Item createDTZSDFSALESORDERSIMULATE3LTORDERITEMSOUTItem() {
        return new DTZSDFSALESORDERSIMULATE3 .LTORDERITEMSOUT.Item();
    }

    /**
     * Create an instance of {@link DTZSDFSALESORDERSIMULATE3 .ITDETAIL.Item }
     * 
     */
    public DTZSDFSALESORDERSIMULATE3 .ITDETAIL.Item createDTZSDFSALESORDERSIMULATE3ITDETAILItem() {
        return new DTZSDFSALESORDERSIMULATE3 .ITDETAIL.Item();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTZSDFSALESORDERSIMULATE3 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DTZSDFSALESORDERSIMULATE3 }{@code >}
     */
    @XmlElementDecl(namespace = "http://affinity-petcare.es/sales_force/sd/valoracion_pedido", name = "MT_ZSDF_SALESORDER_SIMULATE3")
    public JAXBElement<DTZSDFSALESORDERSIMULATE3> createMTZSDFSALESORDERSIMULATE3(DTZSDFSALESORDERSIMULATE3 value) {
        return new JAXBElement<DTZSDFSALESORDERSIMULATE3>(_MTZSDFSALESORDERSIMULATE3_QNAME, DTZSDFSALESORDERSIMULATE3 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTZSDFSALESORDERSIMULATE3RESPONSE }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DTZSDFSALESORDERSIMULATE3RESPONSE }{@code >}
     */
    @XmlElementDecl(namespace = "http://affinity-petcare.es/sales_force/sd/valoracion_pedido", name = "MT_ZSDF_SALESORDER_SIMULATE3_RESPONSE")
    public JAXBElement<DTZSDFSALESORDERSIMULATE3RESPONSE> createMTZSDFSALESORDERSIMULATE3RESPONSE(DTZSDFSALESORDERSIMULATE3RESPONSE value) {
        return new JAXBElement<DTZSDFSALESORDERSIMULATE3RESPONSE>(_MTZSDFSALESORDERSIMULATE3RESPONSE_QNAME, DTZSDFSALESORDERSIMULATE3RESPONSE.class, null, value);
    }

}
